// Code generated by hduhelp-sdk-gen; DO NOT EDIT.

package subscription

import (
	"context"
	"strconv"

	"github.com/hduhelp/hduhelp-neo-sdk-go/core"
	"github.com/hduhelp/hduhelp-neo-sdk-go/models"
)

// Service groups the Subscription endpoints.
type Service struct{ config *core.Config }

// NewService binds the Subscription service to a client config.
func NewService(config *core.Config) *Service { return &Service{config: config} }

// SubscribeReq is the request for Subscribe.
type SubscribeReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// SubscribeReqBuilder builds a SubscribeReq with a fluent setter per field.
type SubscribeReqBuilder struct{ req *SubscribeReq }

// NewSubscribeReqBuilder creates a request builder for Subscribe.
func NewSubscribeReqBuilder() *SubscribeReqBuilder {
	return &SubscribeReqBuilder{req: &SubscribeReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Channel sets the "channel" query parameter.
func (b *SubscribeReqBuilder) Channel(v string) *SubscribeReqBuilder {
	b.req.queryParams["channel"] = v
	return b
}

// Body sets the request body.
func (b *SubscribeReqBuilder) Body(body *models.SubscribeRequestBody) *SubscribeReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *SubscribeReqBuilder) Build() *SubscribeReq { return b.req }

// SubscribeResp is the response for Subscribe.
type SubscribeResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// Subscribe: 订阅提醒渠道
func (s *Service) Subscribe(ctx context.Context, req *SubscribeReq, opts ...core.RequestOption) (*SubscribeResp, error) {
	resp := &SubscribeResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/subscription",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// UpdateSubscriptionReq is the request for UpdateSubscription.
type UpdateSubscriptionReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// UpdateSubscriptionReqBuilder builds a UpdateSubscriptionReq with a fluent setter per field.
type UpdateSubscriptionReqBuilder struct{ req *UpdateSubscriptionReq }

// NewUpdateSubscriptionReqBuilder creates a request builder for UpdateSubscription.
func NewUpdateSubscriptionReqBuilder() *UpdateSubscriptionReqBuilder {
	return &UpdateSubscriptionReqBuilder{req: &UpdateSubscriptionReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *UpdateSubscriptionReqBuilder) Body(body *models.UpdateSubscriptionRequestBody) *UpdateSubscriptionReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *UpdateSubscriptionReqBuilder) Build() *UpdateSubscriptionReq { return b.req }

// UpdateSubscriptionResp is the response for UpdateSubscription.
type UpdateSubscriptionResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// UpdateSubscription: 更新订阅渠道配置
func (s *Service) UpdateSubscription(ctx context.Context, req *UpdateSubscriptionReq, opts ...core.RequestOption) (*UpdateSubscriptionResp, error) {
	resp := &UpdateSubscriptionResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/subscription",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// UnsubscribeReq is the request for Unsubscribe.
type UnsubscribeReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// UnsubscribeReqBuilder builds a UnsubscribeReq with a fluent setter per field.
type UnsubscribeReqBuilder struct{ req *UnsubscribeReq }

// NewUnsubscribeReqBuilder creates a request builder for Unsubscribe.
func NewUnsubscribeReqBuilder() *UnsubscribeReqBuilder {
	return &UnsubscribeReqBuilder{req: &UnsubscribeReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Channel sets the "channel" query parameter.
func (b *UnsubscribeReqBuilder) Channel(v string) *UnsubscribeReqBuilder {
	b.req.queryParams["channel"] = v
	return b
}

// Build finalizes the request.
func (b *UnsubscribeReqBuilder) Build() *UnsubscribeReq { return b.req }

// UnsubscribeResp is the response for Unsubscribe.
type UnsubscribeResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// Unsubscribe: 退订提醒渠道
func (s *Service) Unsubscribe(ctx context.Context, req *UnsubscribeReq, opts ...core.RequestOption) (*UnsubscribeResp, error) {
	resp := &UnsubscribeResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "DELETE",
		PathTemplate: "/hduhelp-neo/subscription",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// SunrunDetailReq is the request for SunrunDetail.
type SunrunDetailReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// SunrunDetailReqBuilder builds a SunrunDetailReq with a fluent setter per field.
type SunrunDetailReqBuilder struct{ req *SunrunDetailReq }

// NewSunrunDetailReqBuilder creates a request builder for SunrunDetail.
func NewSunrunDetailReqBuilder() *SunrunDetailReqBuilder {
	return &SunrunDetailReqBuilder{req: &SunrunDetailReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Start sets the "start" query parameter: 起始序号(默认 1)
func (b *SunrunDetailReqBuilder) Start(v int32) *SunrunDetailReqBuilder {
	b.req.queryParams["start"] = strconv.FormatInt(int64(v), 10)
	return b
}

// End sets the "end" query parameter: 结束序号(默认 20)
func (b *SunrunDetailReqBuilder) End(v int32) *SunrunDetailReqBuilder {
	b.req.queryParams["end"] = strconv.FormatInt(int64(v), 10)
	return b
}

// StaffID sets the "X-Staff-Id" header parameter.
func (b *SunrunDetailReqBuilder) StaffID(v string) *SunrunDetailReqBuilder {
	b.req.headers["X-Staff-Id"] = v
	return b
}

// Build finalizes the request.
func (b *SunrunDetailReqBuilder) Build() *SunrunDetailReq { return b.req }

// SunrunDetailResp is the response for SunrunDetail.
type SunrunDetailResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.SunrunRecord `json:"data"`
}

// SunrunDetail: 阳光长跑跑步记录
func (s *Service) SunrunDetail(ctx context.Context, req *SunrunDetailReq, opts ...core.RequestOption) (*SunrunDetailResp, error) {
	resp := &SunrunDetailResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/subscription/sunrun/detail",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// SunrunGroupReq is the request for SunrunGroup.
type SunrunGroupReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// SunrunGroupReqBuilder builds a SunrunGroupReq with a fluent setter per field.
type SunrunGroupReqBuilder struct{ req *SunrunGroupReq }

// NewSunrunGroupReqBuilder creates a request builder for SunrunGroup.
func NewSunrunGroupReqBuilder() *SunrunGroupReqBuilder {
	return &SunrunGroupReqBuilder{req: &SunrunGroupReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// StaffID sets the "X-Staff-Id" header parameter.
func (b *SunrunGroupReqBuilder) StaffID(v string) *SunrunGroupReqBuilder {
	b.req.headers["X-Staff-Id"] = v
	return b
}

// Build finalizes the request.
func (b *SunrunGroupReqBuilder) Build() *SunrunGroupReq { return b.req }

// SunrunGroupResp is the response for SunrunGroup.
type SunrunGroupResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.SunrunGroup `json:"data"`
}

// SunrunGroup: 阳光长跑达标要求
func (s *Service) SunrunGroup(ctx context.Context, req *SunrunGroupReq, opts ...core.RequestOption) (*SunrunGroupResp, error) {
	resp := &SunrunGroupResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/subscription/sunrun/group",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// SunrunOverviewReq is the request for SunrunOverview.
type SunrunOverviewReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// SunrunOverviewReqBuilder builds a SunrunOverviewReq with a fluent setter per field.
type SunrunOverviewReqBuilder struct{ req *SunrunOverviewReq }

// NewSunrunOverviewReqBuilder creates a request builder for SunrunOverview.
func NewSunrunOverviewReqBuilder() *SunrunOverviewReqBuilder {
	return &SunrunOverviewReqBuilder{req: &SunrunOverviewReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// StaffID sets the "X-Staff-Id" header parameter.
func (b *SunrunOverviewReqBuilder) StaffID(v string) *SunrunOverviewReqBuilder {
	b.req.headers["X-Staff-Id"] = v
	return b
}

// Build finalizes the request.
func (b *SunrunOverviewReqBuilder) Build() *SunrunOverviewReq { return b.req }

// SunrunOverviewResp is the response for SunrunOverview.
type SunrunOverviewResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.SunrunOverview `json:"data"`
}

// SunrunOverview: 阳光长跑成绩概览
func (s *Service) SunrunOverview(ctx context.Context, req *SunrunOverviewReq, opts ...core.RequestOption) (*SunrunOverviewResp, error) {
	resp := &SunrunOverviewResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/subscription/sunrun/overview",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListSubscriptionsReq is the request for ListSubscriptions.
type ListSubscriptionsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListSubscriptionsReqBuilder builds a ListSubscriptionsReq with a fluent setter per field.
type ListSubscriptionsReqBuilder struct{ req *ListSubscriptionsReq }

// NewListSubscriptionsReqBuilder creates a request builder for ListSubscriptions.
func NewListSubscriptionsReqBuilder() *ListSubscriptionsReqBuilder {
	return &ListSubscriptionsReqBuilder{req: &ListSubscriptionsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *ListSubscriptionsReqBuilder) Build() *ListSubscriptionsReq { return b.req }

// ListSubscriptionsResp is the response for ListSubscriptions.
type ListSubscriptionsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.SubscriptionItem `json:"data"`
}

// ListSubscriptions: 获取全部提醒渠道订阅状态
func (s *Service) ListSubscriptions(ctx context.Context, req *ListSubscriptionsReq, opts ...core.RequestOption) (*ListSubscriptionsResp, error) {
	resp := &ListSubscriptionsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/subscriptions",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}
