// Code generated by hduhelp-sdk-gen; DO NOT EDIT.

package messaging

import (
	"context"
	"strconv"

	"github.com/hduhelp/hduhelp-neo-sdk-go/core"
	"github.com/hduhelp/hduhelp-neo-sdk-go/models"
)

// Service groups the Messaging endpoints.
type Service struct{ config *core.Config }

// NewService binds the Messaging service to a client config.
func NewService(config *core.Config) *Service { return &Service{config: config} }

// ListPigeonsReq is the request for ListPigeons.
type ListPigeonsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListPigeonsReqBuilder builds a ListPigeonsReq with a fluent setter per field.
type ListPigeonsReqBuilder struct{ req *ListPigeonsReq }

// NewListPigeonsReqBuilder creates a request builder for ListPigeons.
func NewListPigeonsReqBuilder() *ListPigeonsReqBuilder {
	return &ListPigeonsReqBuilder{req: &ListPigeonsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Box sets the "box" query parameter.
func (b *ListPigeonsReqBuilder) Box(v string) *ListPigeonsReqBuilder {
	b.req.queryParams["box"] = v
	return b
}

// Page sets the "page" query parameter.
func (b *ListPigeonsReqBuilder) Page(v int32) *ListPigeonsReqBuilder {
	b.req.queryParams["page"] = strconv.FormatInt(int64(v), 10)
	return b
}

// PageSize sets the "page_size" query parameter.
func (b *ListPigeonsReqBuilder) PageSize(v int32) *ListPigeonsReqBuilder {
	b.req.queryParams["page_size"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Build finalizes the request.
func (b *ListPigeonsReqBuilder) Build() *ListPigeonsReq { return b.req }

// ListPigeonsResp is the response for ListPigeons.
type ListPigeonsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.MessagePageData `json:"data"`
}

// ListPigeons: 校友传话收件箱或发件箱
func (s *Service) ListPigeons(ctx context.Context, req *ListPigeonsReq, opts ...core.RequestOption) (*ListPigeonsResp, error) {
	resp := &ListPigeonsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/messaging/pigeons",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// SendPigeonReq is the request for SendPigeon.
type SendPigeonReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// SendPigeonReqBuilder builds a SendPigeonReq with a fluent setter per field.
type SendPigeonReqBuilder struct{ req *SendPigeonReq }

// NewSendPigeonReqBuilder creates a request builder for SendPigeon.
func NewSendPigeonReqBuilder() *SendPigeonReqBuilder {
	return &SendPigeonReqBuilder{req: &SendPigeonReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *SendPigeonReqBuilder) Build() *SendPigeonReq { return b.req }

// SendPigeonResp is the response for SendPigeon.
type SendPigeonResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.MessageItem `json:"data"`
}

// SendPigeon: 发送校友传话
func (s *Service) SendPigeon(ctx context.Context, req *SendPigeonReq, opts ...core.RequestOption) (*SendPigeonResp, error) {
	resp := &SendPigeonResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/messaging/pigeons",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListBlacklistReq is the request for ListBlacklist.
type ListBlacklistReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListBlacklistReqBuilder builds a ListBlacklistReq with a fluent setter per field.
type ListBlacklistReqBuilder struct{ req *ListBlacklistReq }

// NewListBlacklistReqBuilder creates a request builder for ListBlacklist.
func NewListBlacklistReqBuilder() *ListBlacklistReqBuilder {
	return &ListBlacklistReqBuilder{req: &ListBlacklistReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Page sets the "page" query parameter.
func (b *ListBlacklistReqBuilder) Page(v int32) *ListBlacklistReqBuilder {
	b.req.queryParams["page"] = strconv.FormatInt(int64(v), 10)
	return b
}

// PageSize sets the "page_size" query parameter.
func (b *ListBlacklistReqBuilder) PageSize(v int32) *ListBlacklistReqBuilder {
	b.req.queryParams["page_size"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Build finalizes the request.
func (b *ListBlacklistReqBuilder) Build() *ListBlacklistReq { return b.req }

// ListBlacklistResp is the response for ListBlacklist.
type ListBlacklistResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.BlacklistData `json:"data"`
}

// ListBlacklist: 校友传话黑名单
func (s *Service) ListBlacklist(ctx context.Context, req *ListBlacklistReq, opts ...core.RequestOption) (*ListBlacklistResp, error) {
	resp := &ListBlacklistResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/messaging/pigeons/blacklist",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AddBlacklistReq is the request for AddBlacklist.
type AddBlacklistReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AddBlacklistReqBuilder builds a AddBlacklistReq with a fluent setter per field.
type AddBlacklistReqBuilder struct{ req *AddBlacklistReq }

// NewAddBlacklistReqBuilder creates a request builder for AddBlacklist.
func NewAddBlacklistReqBuilder() *AddBlacklistReqBuilder {
	return &AddBlacklistReqBuilder{req: &AddBlacklistReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *AddBlacklistReqBuilder) Build() *AddBlacklistReq { return b.req }

// AddBlacklistResp is the response for AddBlacklist.
type AddBlacklistResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// AddBlacklist: 添加校友传话黑名单
func (s *Service) AddBlacklist(ctx context.Context, req *AddBlacklistReq, opts ...core.RequestOption) (*AddBlacklistResp, error) {
	resp := &AddBlacklistResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/messaging/pigeons/blacklist",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// RemoveBlacklistReq is the request for RemoveBlacklist.
type RemoveBlacklistReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// RemoveBlacklistReqBuilder builds a RemoveBlacklistReq with a fluent setter per field.
type RemoveBlacklistReqBuilder struct{ req *RemoveBlacklistReq }

// NewRemoveBlacklistReqBuilder creates a request builder for RemoveBlacklist.
func NewRemoveBlacklistReqBuilder() *RemoveBlacklistReqBuilder {
	return &RemoveBlacklistReqBuilder{req: &RemoveBlacklistReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// StaffId sets the "staff_id" path parameter.
func (b *RemoveBlacklistReqBuilder) StaffId(v string) *RemoveBlacklistReqBuilder {
	b.req.pathParams["staff_id"] = v
	return b
}

// Build finalizes the request.
func (b *RemoveBlacklistReqBuilder) Build() *RemoveBlacklistReq { return b.req }

// RemoveBlacklistResp is the response for RemoveBlacklist.
type RemoveBlacklistResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// RemoveBlacklist: 移除校友传话黑名单
func (s *Service) RemoveBlacklist(ctx context.Context, req *RemoveBlacklistReq, opts ...core.RequestOption) (*RemoveBlacklistResp, error) {
	resp := &RemoveBlacklistResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "DELETE",
		PathTemplate: "/hduhelp-neo/messaging/pigeons/blacklist/{staff_id}",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// RecallPigeonReq is the request for RecallPigeon.
type RecallPigeonReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// RecallPigeonReqBuilder builds a RecallPigeonReq with a fluent setter per field.
type RecallPigeonReqBuilder struct{ req *RecallPigeonReq }

// NewRecallPigeonReqBuilder creates a request builder for RecallPigeon.
func NewRecallPigeonReqBuilder() *RecallPigeonReqBuilder {
	return &RecallPigeonReqBuilder{req: &RecallPigeonReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *RecallPigeonReqBuilder) Id(v string) *RecallPigeonReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Build finalizes the request.
func (b *RecallPigeonReqBuilder) Build() *RecallPigeonReq { return b.req }

// RecallPigeonResp is the response for RecallPigeon.
type RecallPigeonResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// RecallPigeon: 撤回校友传话
func (s *Service) RecallPigeon(ctx context.Context, req *RecallPigeonReq, opts ...core.RequestOption) (*RecallPigeonResp, error) {
	resp := &RecallPigeonResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "DELETE",
		PathTemplate: "/hduhelp-neo/messaging/pigeons/{id}",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListWishesReq is the request for ListWishes.
type ListWishesReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListWishesReqBuilder builds a ListWishesReq with a fluent setter per field.
type ListWishesReqBuilder struct{ req *ListWishesReq }

// NewListWishesReqBuilder creates a request builder for ListWishes.
func NewListWishesReqBuilder() *ListWishesReqBuilder {
	return &ListWishesReqBuilder{req: &ListWishesReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Kind sets the "kind" query parameter.
func (b *ListWishesReqBuilder) Kind(v string) *ListWishesReqBuilder {
	b.req.queryParams["kind"] = v
	return b
}

// Page sets the "page" query parameter.
func (b *ListWishesReqBuilder) Page(v int32) *ListWishesReqBuilder {
	b.req.queryParams["page"] = strconv.FormatInt(int64(v), 10)
	return b
}

// PageSize sets the "page_size" query parameter.
func (b *ListWishesReqBuilder) PageSize(v int32) *ListWishesReqBuilder {
	b.req.queryParams["page_size"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Build finalizes the request.
func (b *ListWishesReqBuilder) Build() *ListWishesReq { return b.req }

// ListWishesResp is the response for ListWishes.
type ListWishesResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.MessagePageData `json:"data"`
}

// ListWishes: 祝福历史
func (s *Service) ListWishes(ctx context.Context, req *ListWishesReq, opts ...core.RequestOption) (*ListWishesResp, error) {
	resp := &ListWishesResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/messaging/wishes",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// SendWishReq is the request for SendWish.
type SendWishReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// SendWishReqBuilder builds a SendWishReq with a fluent setter per field.
type SendWishReqBuilder struct{ req *SendWishReq }

// NewSendWishReqBuilder creates a request builder for SendWish.
func NewSendWishReqBuilder() *SendWishReqBuilder {
	return &SendWishReqBuilder{req: &SendWishReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *SendWishReqBuilder) Build() *SendWishReq { return b.req }

// SendWishResp is the response for SendWish.
type SendWishResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.SendWishData `json:"data"`
}

// SendWish: 发送生日或节日祝福
func (s *Service) SendWish(ctx context.Context, req *SendWishReq, opts ...core.RequestOption) (*SendWishResp, error) {
	resp := &SendWishResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/messaging/wishes",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// BirthdayBaseReq is the request for BirthdayBase.
type BirthdayBaseReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// BirthdayBaseReqBuilder builds a BirthdayBaseReq with a fluent setter per field.
type BirthdayBaseReqBuilder struct{ req *BirthdayBaseReq }

// NewBirthdayBaseReqBuilder creates a request builder for BirthdayBase.
func NewBirthdayBaseReqBuilder() *BirthdayBaseReqBuilder {
	return &BirthdayBaseReqBuilder{req: &BirthdayBaseReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *BirthdayBaseReqBuilder) Build() *BirthdayBaseReq { return b.req }

// BirthdayBaseResp is the response for BirthdayBase.
type BirthdayBaseResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.BirthdayBaseData `json:"data"`
}

// BirthdayBase: 生日祝福首页数据
func (s *Service) BirthdayBase(ctx context.Context, req *BirthdayBaseReq, opts ...core.RequestOption) (*BirthdayBaseResp, error) {
	resp := &BirthdayBaseResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/messaging/wishes/base",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}
