// Code generated by internal/gen; DO NOT EDIT.

package hduhelp

import (
	"github.com/hduhelp/hduhelp-neo-sdk-go/core"

	"github.com/hduhelp/hduhelp-neo-sdk-go/service/academic"
	"github.com/hduhelp/hduhelp-neo-sdk-go/service/admin"
	"github.com/hduhelp/hduhelp-neo-sdk-go/service/campuslife"
	"github.com/hduhelp/hduhelp-neo-sdk-go/service/emptyschedule"
	"github.com/hduhelp/hduhelp-neo-sdk-go/service/feed"
	"github.com/hduhelp/hduhelp-neo-sdk-go/service/graduate"
	"github.com/hduhelp/hduhelp-neo-sdk-go/service/groupchat"
	"github.com/hduhelp/hduhelp-neo-sdk-go/service/health"
	"github.com/hduhelp/hduhelp-neo-sdk-go/service/identity"
	"github.com/hduhelp/hduhelp-neo-sdk-go/service/subscription"
	"github.com/hduhelp/hduhelp-neo-sdk-go/service/upload"
)

// Client is a fully configured hduhelp-neo API client. Each field is a
// namespaced service; call endpoints as client.<Service>.<Method>(ctx, req, opts...).
type Client struct {
	config *core.Config

	Academic      *academic.Service
	Admin         *admin.Service
	CampusLife    *campuslife.Service
	EmptySchedule *emptyschedule.Service
	Feed          *feed.Service
	Graduate      *graduate.Service
	GroupChat     *groupchat.Service
	Health        *health.Service
	Identity      *identity.Service
	Subscription  *subscription.Service
	Upload        *upload.Service
}

// attachServices wires every generated service to the client config.
func attachServices(c *Client) {
	c.Academic = academic.NewService(c.config)
	c.Admin = admin.NewService(c.config)
	c.CampusLife = campuslife.NewService(c.config)
	c.EmptySchedule = emptyschedule.NewService(c.config)
	c.Feed = feed.NewService(c.config)
	c.Graduate = graduate.NewService(c.config)
	c.GroupChat = groupchat.NewService(c.config)
	c.Health = health.NewService(c.config)
	c.Identity = identity.NewService(c.config)
	c.Subscription = subscription.NewService(c.config)
	c.Upload = upload.NewService(c.config)
}
