// Code generated by hduhelp-sdk-gen; DO NOT EDIT.

package groupchat

import (
	"context"

	"github.com/hduhelp/hduhelp-neo-sdk-go/core"
	"github.com/hduhelp/hduhelp-neo-sdk-go/models"
)

// Service groups the GroupChat endpoints.
type Service struct{ config *core.Config }

// NewService binds the GroupChat service to a client config.
func NewService(config *core.Config) *Service { return &Service{config: config} }

// GetClassChatGroupReq is the request for GetClassChatGroup.
type GetClassChatGroupReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// GetClassChatGroupReqBuilder builds a GetClassChatGroupReq with a fluent setter per field.
type GetClassChatGroupReqBuilder struct{ req *GetClassChatGroupReq }

// NewGetClassChatGroupReqBuilder creates a request builder for GetClassChatGroup.
func NewGetClassChatGroupReqBuilder() *GetClassChatGroupReqBuilder {
	return &GetClassChatGroupReqBuilder{req: &GetClassChatGroupReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// ClassId sets the "class_id" query parameter.
func (b *GetClassChatGroupReqBuilder) ClassId(v string) *GetClassChatGroupReqBuilder {
	b.req.queryParams["class_id"] = v
	return b
}

// StaffID sets the "X-Staff-Id" header parameter.
func (b *GetClassChatGroupReqBuilder) StaffID(v string) *GetClassChatGroupReqBuilder {
	b.req.headers["X-Staff-Id"] = v
	return b
}

// Build finalizes the request.
func (b *GetClassChatGroupReqBuilder) Build() *GetClassChatGroupReq { return b.req }

// GetClassChatGroupResp is the response for GetClassChatGroup.
type GetClassChatGroupResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.ChatGroup `json:"data"`
}

// GetClassChatGroup: 查询班级群
func (s *Service) GetClassChatGroup(ctx context.Context, req *GetClassChatGroupReq, opts ...core.RequestOption) (*GetClassChatGroupResp, error) {
	resp := &GetClassChatGroupResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/groupchat/class",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// CreateClassChatGroupReq is the request for CreateClassChatGroup.
type CreateClassChatGroupReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// CreateClassChatGroupReqBuilder builds a CreateClassChatGroupReq with a fluent setter per field.
type CreateClassChatGroupReqBuilder struct{ req *CreateClassChatGroupReq }

// NewCreateClassChatGroupReqBuilder creates a request builder for CreateClassChatGroup.
func NewCreateClassChatGroupReqBuilder() *CreateClassChatGroupReqBuilder {
	return &CreateClassChatGroupReqBuilder{req: &CreateClassChatGroupReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// StaffID sets the "X-Staff-Id" header parameter.
func (b *CreateClassChatGroupReqBuilder) StaffID(v string) *CreateClassChatGroupReqBuilder {
	b.req.headers["X-Staff-Id"] = v
	return b
}

// Body sets the request body.
func (b *CreateClassChatGroupReqBuilder) Body(body *models.CreateClassChatGroupRequestBody) *CreateClassChatGroupReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *CreateClassChatGroupReqBuilder) Build() *CreateClassChatGroupReq { return b.req }

// CreateClassChatGroupResp is the response for CreateClassChatGroup.
type CreateClassChatGroupResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.ChatGroup `json:"data"`
}

// CreateClassChatGroup: 创建班级群
func (s *Service) CreateClassChatGroup(ctx context.Context, req *CreateClassChatGroupReq, opts ...core.RequestOption) (*CreateClassChatGroupResp, error) {
	resp := &CreateClassChatGroupResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/groupchat/class",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// MergeClassChatGroupReq is the request for MergeClassChatGroup.
type MergeClassChatGroupReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// MergeClassChatGroupReqBuilder builds a MergeClassChatGroupReq with a fluent setter per field.
type MergeClassChatGroupReqBuilder struct{ req *MergeClassChatGroupReq }

// NewMergeClassChatGroupReqBuilder creates a request builder for MergeClassChatGroup.
func NewMergeClassChatGroupReqBuilder() *MergeClassChatGroupReqBuilder {
	return &MergeClassChatGroupReqBuilder{req: &MergeClassChatGroupReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// StaffID sets the "X-Staff-Id" header parameter.
func (b *MergeClassChatGroupReqBuilder) StaffID(v string) *MergeClassChatGroupReqBuilder {
	b.req.headers["X-Staff-Id"] = v
	return b
}

// Body sets the request body.
func (b *MergeClassChatGroupReqBuilder) Body(body *models.MergeClassChatGroupRequestBody) *MergeClassChatGroupReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *MergeClassChatGroupReqBuilder) Build() *MergeClassChatGroupReq { return b.req }

// MergeClassChatGroupResp is the response for MergeClassChatGroup.
type MergeClassChatGroupResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// MergeClassChatGroup: 合并已有班级群
func (s *Service) MergeClassChatGroup(ctx context.Context, req *MergeClassChatGroupReq, opts ...core.RequestOption) (*MergeClassChatGroupResp, error) {
	resp := &MergeClassChatGroupResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/groupchat/class/merge",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// SyncClassChatGroupReq is the request for SyncClassChatGroup.
type SyncClassChatGroupReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// SyncClassChatGroupReqBuilder builds a SyncClassChatGroupReq with a fluent setter per field.
type SyncClassChatGroupReqBuilder struct{ req *SyncClassChatGroupReq }

// NewSyncClassChatGroupReqBuilder creates a request builder for SyncClassChatGroup.
func NewSyncClassChatGroupReqBuilder() *SyncClassChatGroupReqBuilder {
	return &SyncClassChatGroupReqBuilder{req: &SyncClassChatGroupReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// StaffID sets the "X-Staff-Id" header parameter.
func (b *SyncClassChatGroupReqBuilder) StaffID(v string) *SyncClassChatGroupReqBuilder {
	b.req.headers["X-Staff-Id"] = v
	return b
}

// Body sets the request body.
func (b *SyncClassChatGroupReqBuilder) Body(body *models.SyncClassChatGroupRequestBody) *SyncClassChatGroupReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *SyncClassChatGroupReqBuilder) Build() *SyncClassChatGroupReq { return b.req }

// SyncClassChatGroupResp is the response for SyncClassChatGroup.
type SyncClassChatGroupResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// SyncClassChatGroup: 同步班级群成员
func (s *Service) SyncClassChatGroup(ctx context.Context, req *SyncClassChatGroupReq, opts ...core.RequestOption) (*SyncClassChatGroupResp, error) {
	resp := &SyncClassChatGroupResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/groupchat/class/sync",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// CourseGroupsReq is the request for CourseGroups.
type CourseGroupsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// CourseGroupsReqBuilder builds a CourseGroupsReq with a fluent setter per field.
type CourseGroupsReqBuilder struct{ req *CourseGroupsReq }

// NewCourseGroupsReqBuilder creates a request builder for CourseGroups.
func NewCourseGroupsReqBuilder() *CourseGroupsReqBuilder {
	return &CourseGroupsReqBuilder{req: &CourseGroupsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// SchoolYear sets the "schoolYear" query parameter.
func (b *CourseGroupsReqBuilder) SchoolYear(v string) *CourseGroupsReqBuilder {
	b.req.queryParams["schoolYear"] = v
	return b
}

// Semester sets the "semester" query parameter.
func (b *CourseGroupsReqBuilder) Semester(v string) *CourseGroupsReqBuilder {
	b.req.queryParams["semester"] = v
	return b
}

// Build finalizes the request.
func (b *CourseGroupsReqBuilder) Build() *CourseGroupsReq { return b.req }

// CourseGroupsResp is the response for CourseGroups.
type CourseGroupsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.CourseGroupItem `json:"data"`
}

// CourseGroups: 我的课程群列表
func (s *Service) CourseGroups(ctx context.Context, req *CourseGroupsReq, opts ...core.RequestOption) (*CourseGroupsResp, error) {
	resp := &CourseGroupsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/groupchat/courses",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// GetGradeChatGroupReq is the request for GetGradeChatGroup.
type GetGradeChatGroupReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// GetGradeChatGroupReqBuilder builds a GetGradeChatGroupReq with a fluent setter per field.
type GetGradeChatGroupReqBuilder struct{ req *GetGradeChatGroupReq }

// NewGetGradeChatGroupReqBuilder creates a request builder for GetGradeChatGroup.
func NewGetGradeChatGroupReqBuilder() *GetGradeChatGroupReqBuilder {
	return &GetGradeChatGroupReqBuilder{req: &GetGradeChatGroupReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// UnitId sets the "unit_id" query parameter.
func (b *GetGradeChatGroupReqBuilder) UnitId(v string) *GetGradeChatGroupReqBuilder {
	b.req.queryParams["unit_id"] = v
	return b
}

// Grade sets the "grade" query parameter.
func (b *GetGradeChatGroupReqBuilder) Grade(v string) *GetGradeChatGroupReqBuilder {
	b.req.queryParams["grade"] = v
	return b
}

// StaffID sets the "X-Staff-Id" header parameter.
func (b *GetGradeChatGroupReqBuilder) StaffID(v string) *GetGradeChatGroupReqBuilder {
	b.req.headers["X-Staff-Id"] = v
	return b
}

// Build finalizes the request.
func (b *GetGradeChatGroupReqBuilder) Build() *GetGradeChatGroupReq { return b.req }

// GetGradeChatGroupResp is the response for GetGradeChatGroup.
type GetGradeChatGroupResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.ChatGroup `json:"data"`
}

// GetGradeChatGroup: 查询年级群
func (s *Service) GetGradeChatGroup(ctx context.Context, req *GetGradeChatGroupReq, opts ...core.RequestOption) (*GetGradeChatGroupResp, error) {
	resp := &GetGradeChatGroupResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/groupchat/grade",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// CreateGradeChatGroupReq is the request for CreateGradeChatGroup.
type CreateGradeChatGroupReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// CreateGradeChatGroupReqBuilder builds a CreateGradeChatGroupReq with a fluent setter per field.
type CreateGradeChatGroupReqBuilder struct{ req *CreateGradeChatGroupReq }

// NewCreateGradeChatGroupReqBuilder creates a request builder for CreateGradeChatGroup.
func NewCreateGradeChatGroupReqBuilder() *CreateGradeChatGroupReqBuilder {
	return &CreateGradeChatGroupReqBuilder{req: &CreateGradeChatGroupReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// StaffID sets the "X-Staff-Id" header parameter.
func (b *CreateGradeChatGroupReqBuilder) StaffID(v string) *CreateGradeChatGroupReqBuilder {
	b.req.headers["X-Staff-Id"] = v
	return b
}

// Body sets the request body.
func (b *CreateGradeChatGroupReqBuilder) Body(body *models.CreateGradeChatGroupRequestBody) *CreateGradeChatGroupReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *CreateGradeChatGroupReqBuilder) Build() *CreateGradeChatGroupReq { return b.req }

// CreateGradeChatGroupResp is the response for CreateGradeChatGroup.
type CreateGradeChatGroupResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.ChatGroup `json:"data"`
}

// CreateGradeChatGroup: 创建年级群
func (s *Service) CreateGradeChatGroup(ctx context.Context, req *CreateGradeChatGroupReq, opts ...core.RequestOption) (*CreateGradeChatGroupResp, error) {
	resp := &CreateGradeChatGroupResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/groupchat/grade",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// SyncGradeChatGroupReq is the request for SyncGradeChatGroup.
type SyncGradeChatGroupReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// SyncGradeChatGroupReqBuilder builds a SyncGradeChatGroupReq with a fluent setter per field.
type SyncGradeChatGroupReqBuilder struct{ req *SyncGradeChatGroupReq }

// NewSyncGradeChatGroupReqBuilder creates a request builder for SyncGradeChatGroup.
func NewSyncGradeChatGroupReqBuilder() *SyncGradeChatGroupReqBuilder {
	return &SyncGradeChatGroupReqBuilder{req: &SyncGradeChatGroupReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// StaffID sets the "X-Staff-Id" header parameter.
func (b *SyncGradeChatGroupReqBuilder) StaffID(v string) *SyncGradeChatGroupReqBuilder {
	b.req.headers["X-Staff-Id"] = v
	return b
}

// Body sets the request body.
func (b *SyncGradeChatGroupReqBuilder) Body(body *models.SyncGradeChatGroupRequestBody) *SyncGradeChatGroupReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *SyncGradeChatGroupReqBuilder) Build() *SyncGradeChatGroupReq { return b.req }

// SyncGradeChatGroupResp is the response for SyncGradeChatGroup.
type SyncGradeChatGroupResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// SyncGradeChatGroup: 同步年级群成员
func (s *Service) SyncGradeChatGroup(ctx context.Context, req *SyncGradeChatGroupReq, opts ...core.RequestOption) (*SyncGradeChatGroupResp, error) {
	resp := &SyncGradeChatGroupResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/groupchat/grade/sync",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// MyGroupsReq is the request for MyGroups.
type MyGroupsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// MyGroupsReqBuilder builds a MyGroupsReq with a fluent setter per field.
type MyGroupsReqBuilder struct{ req *MyGroupsReq }

// NewMyGroupsReqBuilder creates a request builder for MyGroups.
func NewMyGroupsReqBuilder() *MyGroupsReqBuilder {
	return &MyGroupsReqBuilder{req: &MyGroupsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *MyGroupsReqBuilder) Build() *MyGroupsReq { return b.req }

// MyGroupsResp is the response for MyGroups.
type MyGroupsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.GroupInfo `json:"data"`
}

// MyGroups: 查询我创建的群聊
func (s *Service) MyGroups(ctx context.Context, req *MyGroupsReq, opts ...core.RequestOption) (*MyGroupsResp, error) {
	resp := &MyGroupsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/groupchat/groups",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// CreateGroupReq is the request for CreateGroup.
type CreateGroupReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// CreateGroupReqBuilder builds a CreateGroupReq with a fluent setter per field.
type CreateGroupReqBuilder struct{ req *CreateGroupReq }

// NewCreateGroupReqBuilder creates a request builder for CreateGroup.
func NewCreateGroupReqBuilder() *CreateGroupReqBuilder {
	return &CreateGroupReqBuilder{req: &CreateGroupReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// StaffID sets the "X-Staff-Id" header parameter.
func (b *CreateGroupReqBuilder) StaffID(v string) *CreateGroupReqBuilder {
	b.req.headers["X-Staff-Id"] = v
	return b
}

// Body sets the request body.
func (b *CreateGroupReqBuilder) Body(body *models.CreateGroupRequestBody) *CreateGroupReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *CreateGroupReqBuilder) Build() *CreateGroupReq { return b.req }

// CreateGroupResp is the response for CreateGroup.
type CreateGroupResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.GroupInfo `json:"data"`
}

// CreateGroup: 创建钉钉群聊
func (s *Service) CreateGroup(ctx context.Context, req *CreateGroupReq, opts ...core.RequestOption) (*CreateGroupResp, error) {
	resp := &CreateGroupResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/groupchat/groups",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// LeaveGroupReq is the request for LeaveGroup.
type LeaveGroupReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// LeaveGroupReqBuilder builds a LeaveGroupReq with a fluent setter per field.
type LeaveGroupReqBuilder struct{ req *LeaveGroupReq }

// NewLeaveGroupReqBuilder creates a request builder for LeaveGroup.
func NewLeaveGroupReqBuilder() *LeaveGroupReqBuilder {
	return &LeaveGroupReqBuilder{req: &LeaveGroupReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// OpenConversationId sets the "openConversationId" query parameter: 必填。要退出的群 openConversationId，必须复用先前群列表或群详情返回的真实 ID。
func (b *LeaveGroupReqBuilder) OpenConversationId(v string) *LeaveGroupReqBuilder {
	b.req.queryParams["openConversationId"] = v
	return b
}

// StaffID sets the "X-Staff-Id" header parameter.
func (b *LeaveGroupReqBuilder) StaffID(v string) *LeaveGroupReqBuilder {
	b.req.headers["X-Staff-Id"] = v
	return b
}

// Build finalizes the request.
func (b *LeaveGroupReqBuilder) Build() *LeaveGroupReq { return b.req }

// LeaveGroupResp is the response for LeaveGroup.
type LeaveGroupResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// LeaveGroup: 退出群聊
func (s *Service) LeaveGroup(ctx context.Context, req *LeaveGroupReq, opts ...core.RequestOption) (*LeaveGroupResp, error) {
	resp := &LeaveGroupResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "DELETE",
		PathTemplate: "/hduhelp-neo/groupchat/groups/member",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// CreateRecruitChatGroupReq is the request for CreateRecruitChatGroup.
type CreateRecruitChatGroupReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// CreateRecruitChatGroupReqBuilder builds a CreateRecruitChatGroupReq with a fluent setter per field.
type CreateRecruitChatGroupReqBuilder struct{ req *CreateRecruitChatGroupReq }

// NewCreateRecruitChatGroupReqBuilder creates a request builder for CreateRecruitChatGroup.
func NewCreateRecruitChatGroupReqBuilder() *CreateRecruitChatGroupReqBuilder {
	return &CreateRecruitChatGroupReqBuilder{req: &CreateRecruitChatGroupReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// StaffID sets the "X-Staff-Id" header parameter.
func (b *CreateRecruitChatGroupReqBuilder) StaffID(v string) *CreateRecruitChatGroupReqBuilder {
	b.req.headers["X-Staff-Id"] = v
	return b
}

// Body sets the request body.
func (b *CreateRecruitChatGroupReqBuilder) Body(body *models.CreateRecruitChatGroupRequestBody) *CreateRecruitChatGroupReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *CreateRecruitChatGroupReqBuilder) Build() *CreateRecruitChatGroupReq { return b.req }

// CreateRecruitChatGroupResp is the response for CreateRecruitChatGroup.
type CreateRecruitChatGroupResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.CreateRecruitChatGroupData `json:"data"`
}

// CreateRecruitChatGroup: 创建招新群
func (s *Service) CreateRecruitChatGroup(ctx context.Context, req *CreateRecruitChatGroupReq, opts ...core.RequestOption) (*CreateRecruitChatGroupResp, error) {
	resp := &CreateRecruitChatGroupResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/groupchat/recruit",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}
