// Code generated by hduhelp-sdk-gen; DO NOT EDIT.

package knowledge

import (
	"context"
	"strconv"

	"github.com/hduhelp/hduhelp-neo-sdk-go/core"
	"github.com/hduhelp/hduhelp-neo-sdk-go/models"
)

// Service groups the Knowledge endpoints.
type Service struct{ config *core.Config }

// NewService binds the Knowledge service to a client config.
func NewService(config *core.Config) *Service { return &Service{config: config} }

// AdminListAuditReq is the request for AdminListAudit.
type AdminListAuditReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminListAuditReqBuilder builds a AdminListAuditReq with a fluent setter per field.
type AdminListAuditReqBuilder struct{ req *AdminListAuditReq }

// NewAdminListAuditReqBuilder creates a request builder for AdminListAudit.
func NewAdminListAuditReqBuilder() *AdminListAuditReqBuilder {
	return &AdminListAuditReqBuilder{req: &AdminListAuditReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// TargetId sets the "target_id" query parameter.
func (b *AdminListAuditReqBuilder) TargetId(v string) *AdminListAuditReqBuilder {
	b.req.queryParams["target_id"] = v
	return b
}

// TargetType sets the "target_type" query parameter.
func (b *AdminListAuditReqBuilder) TargetType(v string) *AdminListAuditReqBuilder {
	b.req.queryParams["target_type"] = v
	return b
}

// Action sets the "action" query parameter.
func (b *AdminListAuditReqBuilder) Action(v string) *AdminListAuditReqBuilder {
	b.req.queryParams["action"] = v
	return b
}

// Page sets the "page" query parameter.
func (b *AdminListAuditReqBuilder) Page(v int32) *AdminListAuditReqBuilder {
	b.req.queryParams["page"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Size sets the "size" query parameter.
func (b *AdminListAuditReqBuilder) Size(v int32) *AdminListAuditReqBuilder {
	b.req.queryParams["size"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Build finalizes the request.
func (b *AdminListAuditReqBuilder) Build() *AdminListAuditReq { return b.req }

// AdminListAuditResp is the response for AdminListAudit.
type AdminListAuditResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.AuditEntry `json:"data"`
}

// AdminListAudit: 操作审计
func (s *Service) AdminListAudit(ctx context.Context, req *AdminListAuditReq, opts ...core.RequestOption) (*AdminListAuditResp, error) {
	resp := &AdminListAuditResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/knowledge/audit",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminListChunksReq is the request for AdminListChunks.
type AdminListChunksReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminListChunksReqBuilder builds a AdminListChunksReq with a fluent setter per field.
type AdminListChunksReqBuilder struct{ req *AdminListChunksReq }

// NewAdminListChunksReqBuilder creates a request builder for AdminListChunks.
func NewAdminListChunksReqBuilder() *AdminListChunksReqBuilder {
	return &AdminListChunksReqBuilder{req: &AdminListChunksReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// CarrierId sets the "carrier_id" query parameter.
func (b *AdminListChunksReqBuilder) CarrierId(v string) *AdminListChunksReqBuilder {
	b.req.queryParams["carrier_id"] = v
	return b
}

// Build finalizes the request.
func (b *AdminListChunksReqBuilder) Build() *AdminListChunksReq { return b.req }

// AdminListChunksResp is the response for AdminListChunks.
type AdminListChunksResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.KnowledgeChunk `json:"data"`
}

// AdminListChunks: 切片列表
func (s *Service) AdminListChunks(ctx context.Context, req *AdminListChunksReq, opts ...core.RequestOption) (*AdminListChunksResp, error) {
	resp := &AdminListChunksResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/knowledge/chunks",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminAddChunkReq is the request for AdminAddChunk.
type AdminAddChunkReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminAddChunkReqBuilder builds a AdminAddChunkReq with a fluent setter per field.
type AdminAddChunkReqBuilder struct{ req *AdminAddChunkReq }

// NewAdminAddChunkReqBuilder creates a request builder for AdminAddChunk.
func NewAdminAddChunkReqBuilder() *AdminAddChunkReqBuilder {
	return &AdminAddChunkReqBuilder{req: &AdminAddChunkReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *AdminAddChunkReqBuilder) Body(body *models.AddChunkRequestBody) *AdminAddChunkReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *AdminAddChunkReqBuilder) Build() *AdminAddChunkReq { return b.req }

// AdminAddChunkResp is the response for AdminAddChunk.
type AdminAddChunkResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.KnowledgeChunk `json:"data"`
}

// AdminAddChunk: 新增补充切片
func (s *Service) AdminAddChunk(ctx context.Context, req *AdminAddChunkReq, opts ...core.RequestOption) (*AdminAddChunkResp, error) {
	resp := &AdminAddChunkResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/knowledge/chunks",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminUpdateChunkReq is the request for AdminUpdateChunk.
type AdminUpdateChunkReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminUpdateChunkReqBuilder builds a AdminUpdateChunkReq with a fluent setter per field.
type AdminUpdateChunkReqBuilder struct{ req *AdminUpdateChunkReq }

// NewAdminUpdateChunkReqBuilder creates a request builder for AdminUpdateChunk.
func NewAdminUpdateChunkReqBuilder() *AdminUpdateChunkReqBuilder {
	return &AdminUpdateChunkReqBuilder{req: &AdminUpdateChunkReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// CarrierId sets the "carrier_id" query parameter.
func (b *AdminUpdateChunkReqBuilder) CarrierId(v string) *AdminUpdateChunkReqBuilder {
	b.req.queryParams["carrier_id"] = v
	return b
}

// Body sets the request body.
func (b *AdminUpdateChunkReqBuilder) Body(body *models.UpdateChunkRequestBody) *AdminUpdateChunkReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *AdminUpdateChunkReqBuilder) Build() *AdminUpdateChunkReq { return b.req }

// AdminUpdateChunkResp is the response for AdminUpdateChunk.
type AdminUpdateChunkResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.KnowledgeChunk `json:"data"`
}

// AdminUpdateChunk: 编辑切片
func (s *Service) AdminUpdateChunk(ctx context.Context, req *AdminUpdateChunkReq, opts ...core.RequestOption) (*AdminUpdateChunkResp, error) {
	resp := &AdminUpdateChunkResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/knowledge/chunks",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminDeleteChunkReq is the request for AdminDeleteChunk.
type AdminDeleteChunkReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminDeleteChunkReqBuilder builds a AdminDeleteChunkReq with a fluent setter per field.
type AdminDeleteChunkReqBuilder struct{ req *AdminDeleteChunkReq }

// NewAdminDeleteChunkReqBuilder creates a request builder for AdminDeleteChunk.
func NewAdminDeleteChunkReqBuilder() *AdminDeleteChunkReqBuilder {
	return &AdminDeleteChunkReqBuilder{req: &AdminDeleteChunkReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// CarrierId sets the "carrier_id" query parameter.
func (b *AdminDeleteChunkReqBuilder) CarrierId(v string) *AdminDeleteChunkReqBuilder {
	b.req.queryParams["carrier_id"] = v
	return b
}

// PointId sets the "point_id" query parameter.
func (b *AdminDeleteChunkReqBuilder) PointId(v string) *AdminDeleteChunkReqBuilder {
	b.req.queryParams["point_id"] = v
	return b
}

// Build finalizes the request.
func (b *AdminDeleteChunkReqBuilder) Build() *AdminDeleteChunkReq { return b.req }

// AdminDeleteChunkResp is the response for AdminDeleteChunk.
type AdminDeleteChunkResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// AdminDeleteChunk: 删除切片
func (s *Service) AdminDeleteChunk(ctx context.Context, req *AdminDeleteChunkReq, opts ...core.RequestOption) (*AdminDeleteChunkResp, error) {
	resp := &AdminDeleteChunkResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "DELETE",
		PathTemplate: "/hduhelp-neo/admin/knowledge/chunks",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminListCollectorsReq is the request for AdminListCollectors.
type AdminListCollectorsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminListCollectorsReqBuilder builds a AdminListCollectorsReq with a fluent setter per field.
type AdminListCollectorsReqBuilder struct{ req *AdminListCollectorsReq }

// NewAdminListCollectorsReqBuilder creates a request builder for AdminListCollectors.
func NewAdminListCollectorsReqBuilder() *AdminListCollectorsReqBuilder {
	return &AdminListCollectorsReqBuilder{req: &AdminListCollectorsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *AdminListCollectorsReqBuilder) Build() *AdminListCollectorsReq { return b.req }

// AdminListCollectorsResp is the response for AdminListCollectors.
type AdminListCollectorsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.CollectorInfo `json:"data"`
}

// AdminListCollectors: 采集器列表
func (s *Service) AdminListCollectors(ctx context.Context, req *AdminListCollectorsReq, opts ...core.RequestOption) (*AdminListCollectorsResp, error) {
	resp := &AdminListCollectorsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/knowledge/collectors",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminUpdateCollectorReq is the request for AdminUpdateCollector.
type AdminUpdateCollectorReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminUpdateCollectorReqBuilder builds a AdminUpdateCollectorReq with a fluent setter per field.
type AdminUpdateCollectorReqBuilder struct{ req *AdminUpdateCollectorReq }

// NewAdminUpdateCollectorReqBuilder creates a request builder for AdminUpdateCollector.
func NewAdminUpdateCollectorReqBuilder() *AdminUpdateCollectorReqBuilder {
	return &AdminUpdateCollectorReqBuilder{req: &AdminUpdateCollectorReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Key sets the "key" query parameter.
func (b *AdminUpdateCollectorReqBuilder) Key(v string) *AdminUpdateCollectorReqBuilder {
	b.req.queryParams["key"] = v
	return b
}

// Body sets the request body.
func (b *AdminUpdateCollectorReqBuilder) Body(body *models.UpdateCollectorRequestBody) *AdminUpdateCollectorReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *AdminUpdateCollectorReqBuilder) Build() *AdminUpdateCollectorReq { return b.req }

// AdminUpdateCollectorResp is the response for AdminUpdateCollector.
type AdminUpdateCollectorResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.CollectorInfo `json:"data"`
}

// AdminUpdateCollector: 配置采集器
func (s *Service) AdminUpdateCollector(ctx context.Context, req *AdminUpdateCollectorReq, opts ...core.RequestOption) (*AdminUpdateCollectorResp, error) {
	resp := &AdminUpdateCollectorResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/knowledge/collectors",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminRunCollectorReq is the request for AdminRunCollector.
type AdminRunCollectorReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminRunCollectorReqBuilder builds a AdminRunCollectorReq with a fluent setter per field.
type AdminRunCollectorReqBuilder struct{ req *AdminRunCollectorReq }

// NewAdminRunCollectorReqBuilder creates a request builder for AdminRunCollector.
func NewAdminRunCollectorReqBuilder() *AdminRunCollectorReqBuilder {
	return &AdminRunCollectorReqBuilder{req: &AdminRunCollectorReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Key sets the "key" query parameter.
func (b *AdminRunCollectorReqBuilder) Key(v string) *AdminRunCollectorReqBuilder {
	b.req.queryParams["key"] = v
	return b
}

// Build finalizes the request.
func (b *AdminRunCollectorReqBuilder) Build() *AdminRunCollectorReq { return b.req }

// AdminRunCollectorResp is the response for AdminRunCollector.
type AdminRunCollectorResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// AdminRunCollector: 立即运行采集器
func (s *Service) AdminRunCollector(ctx context.Context, req *AdminRunCollectorReq, opts ...core.RequestOption) (*AdminRunCollectorResp, error) {
	resp := &AdminRunCollectorResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/knowledge/collectors/run",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminDiscardDraftReq is the request for AdminDiscardDraft.
type AdminDiscardDraftReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminDiscardDraftReqBuilder builds a AdminDiscardDraftReq with a fluent setter per field.
type AdminDiscardDraftReqBuilder struct{ req *AdminDiscardDraftReq }

// NewAdminDiscardDraftReqBuilder creates a request builder for AdminDiscardDraft.
func NewAdminDiscardDraftReqBuilder() *AdminDiscardDraftReqBuilder {
	return &AdminDiscardDraftReqBuilder{req: &AdminDiscardDraftReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// CarrierId sets the "carrier_id" query parameter.
func (b *AdminDiscardDraftReqBuilder) CarrierId(v string) *AdminDiscardDraftReqBuilder {
	b.req.queryParams["carrier_id"] = v
	return b
}

// Build finalizes the request.
func (b *AdminDiscardDraftReqBuilder) Build() *AdminDiscardDraftReq { return b.req }

// AdminDiscardDraftResp is the response for AdminDiscardDraft.
type AdminDiscardDraftResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.KnowledgeCarrier `json:"data"`
}

// AdminDiscardDraft: 撤销草稿
func (s *Service) AdminDiscardDraft(ctx context.Context, req *AdminDiscardDraftReq, opts ...core.RequestOption) (*AdminDiscardDraftResp, error) {
	resp := &AdminDiscardDraftResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/knowledge/content/discard",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminSaveDraftReq is the request for AdminSaveDraft.
type AdminSaveDraftReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminSaveDraftReqBuilder builds a AdminSaveDraftReq with a fluent setter per field.
type AdminSaveDraftReqBuilder struct{ req *AdminSaveDraftReq }

// NewAdminSaveDraftReqBuilder creates a request builder for AdminSaveDraft.
func NewAdminSaveDraftReqBuilder() *AdminSaveDraftReqBuilder {
	return &AdminSaveDraftReqBuilder{req: &AdminSaveDraftReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// CarrierId sets the "carrier_id" query parameter.
func (b *AdminSaveDraftReqBuilder) CarrierId(v string) *AdminSaveDraftReqBuilder {
	b.req.queryParams["carrier_id"] = v
	return b
}

// Body sets the request body.
func (b *AdminSaveDraftReqBuilder) Body(body *models.SaveDraftRequestBody) *AdminSaveDraftReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *AdminSaveDraftReqBuilder) Build() *AdminSaveDraftReq { return b.req }

// AdminSaveDraftResp is the response for AdminSaveDraft.
type AdminSaveDraftResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.KnowledgeCarrier `json:"data"`
}

// AdminSaveDraft: 保存草稿
func (s *Service) AdminSaveDraft(ctx context.Context, req *AdminSaveDraftReq, opts ...core.RequestOption) (*AdminSaveDraftResp, error) {
	resp := &AdminSaveDraftResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/knowledge/content/draft",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminPublishDraftReq is the request for AdminPublishDraft.
type AdminPublishDraftReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminPublishDraftReqBuilder builds a AdminPublishDraftReq with a fluent setter per field.
type AdminPublishDraftReqBuilder struct{ req *AdminPublishDraftReq }

// NewAdminPublishDraftReqBuilder creates a request builder for AdminPublishDraft.
func NewAdminPublishDraftReqBuilder() *AdminPublishDraftReqBuilder {
	return &AdminPublishDraftReqBuilder{req: &AdminPublishDraftReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// CarrierId sets the "carrier_id" query parameter.
func (b *AdminPublishDraftReqBuilder) CarrierId(v string) *AdminPublishDraftReqBuilder {
	b.req.queryParams["carrier_id"] = v
	return b
}

// Build finalizes the request.
func (b *AdminPublishDraftReqBuilder) Build() *AdminPublishDraftReq { return b.req }

// AdminPublishDraftResp is the response for AdminPublishDraft.
type AdminPublishDraftResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.KnowledgeCarrier `json:"data"`
}

// AdminPublishDraft: 发布草稿
func (s *Service) AdminPublishDraft(ctx context.Context, req *AdminPublishDraftReq, opts ...core.RequestOption) (*AdminPublishDraftResp, error) {
	resp := &AdminPublishDraftResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/knowledge/content/publish",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminRestoreVersionReq is the request for AdminRestoreVersion.
type AdminRestoreVersionReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminRestoreVersionReqBuilder builds a AdminRestoreVersionReq with a fluent setter per field.
type AdminRestoreVersionReqBuilder struct{ req *AdminRestoreVersionReq }

// NewAdminRestoreVersionReqBuilder creates a request builder for AdminRestoreVersion.
func NewAdminRestoreVersionReqBuilder() *AdminRestoreVersionReqBuilder {
	return &AdminRestoreVersionReqBuilder{req: &AdminRestoreVersionReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// CarrierId sets the "carrier_id" query parameter.
func (b *AdminRestoreVersionReqBuilder) CarrierId(v string) *AdminRestoreVersionReqBuilder {
	b.req.queryParams["carrier_id"] = v
	return b
}

// Body sets the request body.
func (b *AdminRestoreVersionReqBuilder) Body(body *models.RestoreVersionRequestBody) *AdminRestoreVersionReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *AdminRestoreVersionReqBuilder) Build() *AdminRestoreVersionReq { return b.req }

// AdminRestoreVersionResp is the response for AdminRestoreVersion.
type AdminRestoreVersionResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.KnowledgeCarrier `json:"data"`
}

// AdminRestoreVersion: 恢复历史版本
func (s *Service) AdminRestoreVersion(ctx context.Context, req *AdminRestoreVersionReq, opts ...core.RequestOption) (*AdminRestoreVersionResp, error) {
	resp := &AdminRestoreVersionResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/knowledge/content/restore",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminListCrawlRunsReq is the request for AdminListCrawlRuns.
type AdminListCrawlRunsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminListCrawlRunsReqBuilder builds a AdminListCrawlRunsReq with a fluent setter per field.
type AdminListCrawlRunsReqBuilder struct{ req *AdminListCrawlRunsReq }

// NewAdminListCrawlRunsReqBuilder creates a request builder for AdminListCrawlRuns.
func NewAdminListCrawlRunsReqBuilder() *AdminListCrawlRunsReqBuilder {
	return &AdminListCrawlRunsReqBuilder{req: &AdminListCrawlRunsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// CollectorKey sets the "collector_key" query parameter.
func (b *AdminListCrawlRunsReqBuilder) CollectorKey(v string) *AdminListCrawlRunsReqBuilder {
	b.req.queryParams["collector_key"] = v
	return b
}

// Page sets the "page" query parameter.
func (b *AdminListCrawlRunsReqBuilder) Page(v int32) *AdminListCrawlRunsReqBuilder {
	b.req.queryParams["page"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Size sets the "size" query parameter.
func (b *AdminListCrawlRunsReqBuilder) Size(v int32) *AdminListCrawlRunsReqBuilder {
	b.req.queryParams["size"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Build finalizes the request.
func (b *AdminListCrawlRunsReqBuilder) Build() *AdminListCrawlRunsReq { return b.req }

// AdminListCrawlRunsResp is the response for AdminListCrawlRuns.
type AdminListCrawlRunsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.CrawlRunInfo `json:"data"`
}

// AdminListCrawlRuns: 抓取运行记录
func (s *Service) AdminListCrawlRuns(ctx context.Context, req *AdminListCrawlRunsReq, opts ...core.RequestOption) (*AdminListCrawlRunsResp, error) {
	resp := &AdminListCrawlRunsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/knowledge/crawl-runs",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminListDomainsReq is the request for AdminListDomains.
type AdminListDomainsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminListDomainsReqBuilder builds a AdminListDomainsReq with a fluent setter per field.
type AdminListDomainsReqBuilder struct{ req *AdminListDomainsReq }

// NewAdminListDomainsReqBuilder creates a request builder for AdminListDomains.
func NewAdminListDomainsReqBuilder() *AdminListDomainsReqBuilder {
	return &AdminListDomainsReqBuilder{req: &AdminListDomainsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *AdminListDomainsReqBuilder) Build() *AdminListDomainsReq { return b.req }

// AdminListDomainsResp is the response for AdminListDomains.
type AdminListDomainsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.KnowledgeDomainNode `json:"data"`
}

// AdminListDomains: 知识域列表
func (s *Service) AdminListDomains(ctx context.Context, req *AdminListDomainsReq, opts ...core.RequestOption) (*AdminListDomainsResp, error) {
	resp := &AdminListDomainsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/knowledge/domains",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminCreateDomainReq is the request for AdminCreateDomain.
type AdminCreateDomainReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminCreateDomainReqBuilder builds a AdminCreateDomainReq with a fluent setter per field.
type AdminCreateDomainReqBuilder struct{ req *AdminCreateDomainReq }

// NewAdminCreateDomainReqBuilder creates a request builder for AdminCreateDomain.
func NewAdminCreateDomainReqBuilder() *AdminCreateDomainReqBuilder {
	return &AdminCreateDomainReqBuilder{req: &AdminCreateDomainReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *AdminCreateDomainReqBuilder) Body(body *models.CreateDomainRequestBody) *AdminCreateDomainReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *AdminCreateDomainReqBuilder) Build() *AdminCreateDomainReq { return b.req }

// AdminCreateDomainResp is the response for AdminCreateDomain.
type AdminCreateDomainResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.KnowledgeDomainNode `json:"data"`
}

// AdminCreateDomain: 新建知识域
func (s *Service) AdminCreateDomain(ctx context.Context, req *AdminCreateDomainReq, opts ...core.RequestOption) (*AdminCreateDomainResp, error) {
	resp := &AdminCreateDomainResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/knowledge/domains",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminUpdateDomainReq is the request for AdminUpdateDomain.
type AdminUpdateDomainReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminUpdateDomainReqBuilder builds a AdminUpdateDomainReq with a fluent setter per field.
type AdminUpdateDomainReqBuilder struct{ req *AdminUpdateDomainReq }

// NewAdminUpdateDomainReqBuilder creates a request builder for AdminUpdateDomain.
func NewAdminUpdateDomainReqBuilder() *AdminUpdateDomainReqBuilder {
	return &AdminUpdateDomainReqBuilder{req: &AdminUpdateDomainReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" query parameter.
func (b *AdminUpdateDomainReqBuilder) Id(v string) *AdminUpdateDomainReqBuilder {
	b.req.queryParams["id"] = v
	return b
}

// Body sets the request body.
func (b *AdminUpdateDomainReqBuilder) Body(body *models.UpdateDomainRequestBody) *AdminUpdateDomainReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *AdminUpdateDomainReqBuilder) Build() *AdminUpdateDomainReq { return b.req }

// AdminUpdateDomainResp is the response for AdminUpdateDomain.
type AdminUpdateDomainResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.KnowledgeDomainNode `json:"data"`
}

// AdminUpdateDomain: 编辑知识域
func (s *Service) AdminUpdateDomain(ctx context.Context, req *AdminUpdateDomainReq, opts ...core.RequestOption) (*AdminUpdateDomainResp, error) {
	resp := &AdminUpdateDomainResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/knowledge/domains",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminDeleteDomainReq is the request for AdminDeleteDomain.
type AdminDeleteDomainReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminDeleteDomainReqBuilder builds a AdminDeleteDomainReq with a fluent setter per field.
type AdminDeleteDomainReqBuilder struct{ req *AdminDeleteDomainReq }

// NewAdminDeleteDomainReqBuilder creates a request builder for AdminDeleteDomain.
func NewAdminDeleteDomainReqBuilder() *AdminDeleteDomainReqBuilder {
	return &AdminDeleteDomainReqBuilder{req: &AdminDeleteDomainReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" query parameter.
func (b *AdminDeleteDomainReqBuilder) Id(v string) *AdminDeleteDomainReqBuilder {
	b.req.queryParams["id"] = v
	return b
}

// MergeIntoId sets the "merge_into_id" query parameter: 把条目并入目标域后删除
func (b *AdminDeleteDomainReqBuilder) MergeIntoId(v string) *AdminDeleteDomainReqBuilder {
	b.req.queryParams["merge_into_id"] = v
	return b
}

// Build finalizes the request.
func (b *AdminDeleteDomainReqBuilder) Build() *AdminDeleteDomainReq { return b.req }

// AdminDeleteDomainResp is the response for AdminDeleteDomain.
type AdminDeleteDomainResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// AdminDeleteDomain: 删除知识域
func (s *Service) AdminDeleteDomain(ctx context.Context, req *AdminDeleteDomainReq, opts ...core.RequestOption) (*AdminDeleteDomainResp, error) {
	resp := &AdminDeleteDomainResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "DELETE",
		PathTemplate: "/hduhelp-neo/admin/knowledge/domains",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminImportFaqReq is the request for AdminImportFaq.
type AdminImportFaqReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminImportFaqReqBuilder builds a AdminImportFaqReq with a fluent setter per field.
type AdminImportFaqReqBuilder struct{ req *AdminImportFaqReq }

// NewAdminImportFaqReqBuilder creates a request builder for AdminImportFaq.
func NewAdminImportFaqReqBuilder() *AdminImportFaqReqBuilder {
	return &AdminImportFaqReqBuilder{req: &AdminImportFaqReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *AdminImportFaqReqBuilder) Body(body *models.FaqImportRequestBody) *AdminImportFaqReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *AdminImportFaqReqBuilder) Build() *AdminImportFaqReq { return b.req }

// AdminImportFaqResp is the response for AdminImportFaq.
type AdminImportFaqResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// AdminImportFaq: 批量导入 FAQ
func (s *Service) AdminImportFaq(ctx context.Context, req *AdminImportFaqReq, opts ...core.RequestOption) (*AdminImportFaqResp, error) {
	resp := &AdminImportFaqResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/knowledge/faq/import",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminListGapsReq is the request for AdminListGaps.
type AdminListGapsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminListGapsReqBuilder builds a AdminListGapsReq with a fluent setter per field.
type AdminListGapsReqBuilder struct{ req *AdminListGapsReq }

// NewAdminListGapsReqBuilder creates a request builder for AdminListGaps.
func NewAdminListGapsReqBuilder() *AdminListGapsReqBuilder {
	return &AdminListGapsReqBuilder{req: &AdminListGapsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Status sets the "status" query parameter.
func (b *AdminListGapsReqBuilder) Status(v string) *AdminListGapsReqBuilder {
	b.req.queryParams["status"] = v
	return b
}

// Page sets the "page" query parameter.
func (b *AdminListGapsReqBuilder) Page(v int32) *AdminListGapsReqBuilder {
	b.req.queryParams["page"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Size sets the "size" query parameter.
func (b *AdminListGapsReqBuilder) Size(v int32) *AdminListGapsReqBuilder {
	b.req.queryParams["size"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Build finalizes the request.
func (b *AdminListGapsReqBuilder) Build() *AdminListGapsReq { return b.req }

// AdminListGapsResp is the response for AdminListGaps.
type AdminListGapsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.KnowledgeGapInfo `json:"data"`
}

// AdminListGaps: 知识盲区列表
func (s *Service) AdminListGaps(ctx context.Context, req *AdminListGapsReq, opts ...core.RequestOption) (*AdminListGapsResp, error) {
	resp := &AdminListGapsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/knowledge/gaps",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminGapActionReq is the request for AdminGapAction.
type AdminGapActionReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminGapActionReqBuilder builds a AdminGapActionReq with a fluent setter per field.
type AdminGapActionReqBuilder struct{ req *AdminGapActionReq }

// NewAdminGapActionReqBuilder creates a request builder for AdminGapAction.
func NewAdminGapActionReqBuilder() *AdminGapActionReqBuilder {
	return &AdminGapActionReqBuilder{req: &AdminGapActionReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" query parameter.
func (b *AdminGapActionReqBuilder) Id(v string) *AdminGapActionReqBuilder {
	b.req.queryParams["id"] = v
	return b
}

// Body sets the request body.
func (b *AdminGapActionReqBuilder) Body(body *models.GapActionRequestBody) *AdminGapActionReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *AdminGapActionReqBuilder) Build() *AdminGapActionReq { return b.req }

// AdminGapActionResp is the response for AdminGapAction.
type AdminGapActionResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.KnowledgeGapInfo `json:"data"`
}

// AdminGapAction: 处理盲区
func (s *Service) AdminGapAction(ctx context.Context, req *AdminGapActionReq, opts ...core.RequestOption) (*AdminGapActionResp, error) {
	resp := &AdminGapActionResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/knowledge/gaps/action",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminListItemsReq is the request for AdminListItems.
type AdminListItemsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminListItemsReqBuilder builds a AdminListItemsReq with a fluent setter per field.
type AdminListItemsReqBuilder struct{ req *AdminListItemsReq }

// NewAdminListItemsReqBuilder creates a request builder for AdminListItems.
func NewAdminListItemsReqBuilder() *AdminListItemsReqBuilder {
	return &AdminListItemsReqBuilder{req: &AdminListItemsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// DomainId sets the "domain_id" query parameter.
func (b *AdminListItemsReqBuilder) DomainId(v string) *AdminListItemsReqBuilder {
	b.req.queryParams["domain_id"] = v
	return b
}

// Status sets the "status" query parameter.
func (b *AdminListItemsReqBuilder) Status(v string) *AdminListItemsReqBuilder {
	b.req.queryParams["status"] = v
	return b
}

// SourceId sets the "source_id" query parameter.
func (b *AdminListItemsReqBuilder) SourceId(v string) *AdminListItemsReqBuilder {
	b.req.queryParams["source_id"] = v
	return b
}

// Authority sets the "authority" query parameter: human | official_school | official_hduhelp
func (b *AdminListItemsReqBuilder) Authority(v string) *AdminListItemsReqBuilder {
	b.req.queryParams["authority"] = v
	return b
}

// Kind sets the "kind" query parameter: faq | article | file
func (b *AdminListItemsReqBuilder) Kind(v string) *AdminListItemsReqBuilder {
	b.req.queryParams["kind"] = v
	return b
}

// Keyword sets the "keyword" query parameter.
func (b *AdminListItemsReqBuilder) Keyword(v string) *AdminListItemsReqBuilder {
	b.req.queryParams["keyword"] = v
	return b
}

// TakeoverOnly sets the "takeover_only" query parameter.
func (b *AdminListItemsReqBuilder) TakeoverOnly(v bool) *AdminListItemsReqBuilder {
	b.req.queryParams["takeover_only"] = strconv.FormatBool(v)
	return b
}

// Page sets the "page" query parameter.
func (b *AdminListItemsReqBuilder) Page(v int32) *AdminListItemsReqBuilder {
	b.req.queryParams["page"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Size sets the "size" query parameter.
func (b *AdminListItemsReqBuilder) Size(v int32) *AdminListItemsReqBuilder {
	b.req.queryParams["size"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Deleted sets the "deleted" query parameter: 回收站：仅软删条目
func (b *AdminListItemsReqBuilder) Deleted(v bool) *AdminListItemsReqBuilder {
	b.req.queryParams["deleted"] = strconv.FormatBool(v)
	return b
}

// SyncStatus sets the "sync_status" query parameter: 收录态过滤: synced | pending | failed
func (b *AdminListItemsReqBuilder) SyncStatus(v string) *AdminListItemsReqBuilder {
	b.req.queryParams["sync_status"] = v
	return b
}

// Build finalizes the request.
func (b *AdminListItemsReqBuilder) Build() *AdminListItemsReq { return b.req }

// AdminListItemsResp is the response for AdminListItems.
type AdminListItemsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.KnowledgeItemSummary `json:"data"`
}

// AdminListItems: 知识条目列表
func (s *Service) AdminListItems(ctx context.Context, req *AdminListItemsReq, opts ...core.RequestOption) (*AdminListItemsResp, error) {
	resp := &AdminListItemsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/knowledge/items",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminCreateItemReq is the request for AdminCreateItem.
type AdminCreateItemReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminCreateItemReqBuilder builds a AdminCreateItemReq with a fluent setter per field.
type AdminCreateItemReqBuilder struct{ req *AdminCreateItemReq }

// NewAdminCreateItemReqBuilder creates a request builder for AdminCreateItem.
func NewAdminCreateItemReqBuilder() *AdminCreateItemReqBuilder {
	return &AdminCreateItemReqBuilder{req: &AdminCreateItemReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *AdminCreateItemReqBuilder) Body(body *models.CreateItemRequestBody) *AdminCreateItemReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *AdminCreateItemReqBuilder) Build() *AdminCreateItemReq { return b.req }

// AdminCreateItemResp is the response for AdminCreateItem.
type AdminCreateItemResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.KnowledgeItemDetail `json:"data"`
}

// AdminCreateItem: 新建知识条目
func (s *Service) AdminCreateItem(ctx context.Context, req *AdminCreateItemReq, opts ...core.RequestOption) (*AdminCreateItemResp, error) {
	resp := &AdminCreateItemResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/knowledge/items",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminUpdateItemReq is the request for AdminUpdateItem.
type AdminUpdateItemReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminUpdateItemReqBuilder builds a AdminUpdateItemReq with a fluent setter per field.
type AdminUpdateItemReqBuilder struct{ req *AdminUpdateItemReq }

// NewAdminUpdateItemReqBuilder creates a request builder for AdminUpdateItem.
func NewAdminUpdateItemReqBuilder() *AdminUpdateItemReqBuilder {
	return &AdminUpdateItemReqBuilder{req: &AdminUpdateItemReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" query parameter.
func (b *AdminUpdateItemReqBuilder) Id(v string) *AdminUpdateItemReqBuilder {
	b.req.queryParams["id"] = v
	return b
}

// Body sets the request body.
func (b *AdminUpdateItemReqBuilder) Body(body *models.UpdateItemRequestBody) *AdminUpdateItemReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *AdminUpdateItemReqBuilder) Build() *AdminUpdateItemReq { return b.req }

// AdminUpdateItemResp is the response for AdminUpdateItem.
type AdminUpdateItemResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.KnowledgeItemDetail `json:"data"`
}

// AdminUpdateItem: 编辑条目元信息
func (s *Service) AdminUpdateItem(ctx context.Context, req *AdminUpdateItemReq, opts ...core.RequestOption) (*AdminUpdateItemResp, error) {
	resp := &AdminUpdateItemResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/knowledge/items",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminAttachFileReq is the request for AdminAttachFile.
type AdminAttachFileReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminAttachFileReqBuilder builds a AdminAttachFileReq with a fluent setter per field.
type AdminAttachFileReqBuilder struct{ req *AdminAttachFileReq }

// NewAdminAttachFileReqBuilder creates a request builder for AdminAttachFile.
func NewAdminAttachFileReqBuilder() *AdminAttachFileReqBuilder {
	return &AdminAttachFileReqBuilder{req: &AdminAttachFileReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" query parameter.
func (b *AdminAttachFileReqBuilder) Id(v string) *AdminAttachFileReqBuilder {
	b.req.queryParams["id"] = v
	return b
}

// Body sets the request body.
func (b *AdminAttachFileReqBuilder) Body(body *models.AttachFileRequestBody) *AdminAttachFileReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *AdminAttachFileReqBuilder) Build() *AdminAttachFileReq { return b.req }

// AdminAttachFileResp is the response for AdminAttachFile.
type AdminAttachFileResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.KnowledgeItemDetail `json:"data"`
}

// AdminAttachFile: 给条目挂附件
func (s *Service) AdminAttachFile(ctx context.Context, req *AdminAttachFileReq, opts ...core.RequestOption) (*AdminAttachFileResp, error) {
	resp := &AdminAttachFileResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/knowledge/items/attach",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminCheckUpdateReq is the request for AdminCheckUpdate.
type AdminCheckUpdateReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminCheckUpdateReqBuilder builds a AdminCheckUpdateReq with a fluent setter per field.
type AdminCheckUpdateReqBuilder struct{ req *AdminCheckUpdateReq }

// NewAdminCheckUpdateReqBuilder creates a request builder for AdminCheckUpdate.
func NewAdminCheckUpdateReqBuilder() *AdminCheckUpdateReqBuilder {
	return &AdminCheckUpdateReqBuilder{req: &AdminCheckUpdateReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" query parameter.
func (b *AdminCheckUpdateReqBuilder) Id(v string) *AdminCheckUpdateReqBuilder {
	b.req.queryParams["id"] = v
	return b
}

// Build finalizes the request.
func (b *AdminCheckUpdateReqBuilder) Build() *AdminCheckUpdateReq { return b.req }

// AdminCheckUpdateResp is the response for AdminCheckUpdate.
type AdminCheckUpdateResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.CheckUpdateData `json:"data"`
}

// AdminCheckUpdate: 检查更新
func (s *Service) AdminCheckUpdate(ctx context.Context, req *AdminCheckUpdateReq, opts ...core.RequestOption) (*AdminCheckUpdateResp, error) {
	resp := &AdminCheckUpdateResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/knowledge/items/check-update",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminItemDetailReq is the request for AdminItemDetail.
type AdminItemDetailReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminItemDetailReqBuilder builds a AdminItemDetailReq with a fluent setter per field.
type AdminItemDetailReqBuilder struct{ req *AdminItemDetailReq }

// NewAdminItemDetailReqBuilder creates a request builder for AdminItemDetail.
func NewAdminItemDetailReqBuilder() *AdminItemDetailReqBuilder {
	return &AdminItemDetailReqBuilder{req: &AdminItemDetailReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" query parameter.
func (b *AdminItemDetailReqBuilder) Id(v string) *AdminItemDetailReqBuilder {
	b.req.queryParams["id"] = v
	return b
}

// Build finalizes the request.
func (b *AdminItemDetailReqBuilder) Build() *AdminItemDetailReq { return b.req }

// AdminItemDetailResp is the response for AdminItemDetail.
type AdminItemDetailResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.KnowledgeItemDetail `json:"data"`
}

// AdminItemDetail: 知识条目详情
func (s *Service) AdminItemDetail(ctx context.Context, req *AdminItemDetailReq, opts ...core.RequestOption) (*AdminItemDetailResp, error) {
	resp := &AdminItemDetailResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/knowledge/items/detail",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminRetagReq is the request for AdminRetag.
type AdminRetagReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminRetagReqBuilder builds a AdminRetagReq with a fluent setter per field.
type AdminRetagReqBuilder struct{ req *AdminRetagReq }

// NewAdminRetagReqBuilder creates a request builder for AdminRetag.
func NewAdminRetagReqBuilder() *AdminRetagReqBuilder {
	return &AdminRetagReqBuilder{req: &AdminRetagReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" query parameter.
func (b *AdminRetagReqBuilder) Id(v string) *AdminRetagReqBuilder {
	b.req.queryParams["id"] = v
	return b
}

// Build finalizes the request.
func (b *AdminRetagReqBuilder) Build() *AdminRetagReq { return b.req }

// AdminRetagResp is the response for AdminRetag.
type AdminRetagResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.KnowledgeItemSummary `json:"data"`
}

// AdminRetag: 重新自动打标
func (s *Service) AdminRetag(ctx context.Context, req *AdminRetagReq, opts ...core.RequestOption) (*AdminRetagResp, error) {
	resp := &AdminRetagResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/knowledge/items/retag",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminItemStateReq is the request for AdminItemState.
type AdminItemStateReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminItemStateReqBuilder builds a AdminItemStateReq with a fluent setter per field.
type AdminItemStateReqBuilder struct{ req *AdminItemStateReq }

// NewAdminItemStateReqBuilder creates a request builder for AdminItemState.
func NewAdminItemStateReqBuilder() *AdminItemStateReqBuilder {
	return &AdminItemStateReqBuilder{req: &AdminItemStateReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" query parameter.
func (b *AdminItemStateReqBuilder) Id(v string) *AdminItemStateReqBuilder {
	b.req.queryParams["id"] = v
	return b
}

// Body sets the request body.
func (b *AdminItemStateReqBuilder) Body(body *models.ItemStateRequestBody) *AdminItemStateReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *AdminItemStateReqBuilder) Build() *AdminItemStateReq { return b.req }

// AdminItemStateResp is the response for AdminItemState.
type AdminItemStateResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.KnowledgeItemSummary `json:"data"`
}

// AdminItemState: 条目状态流转
func (s *Service) AdminItemState(ctx context.Context, req *AdminItemStateReq, opts ...core.RequestOption) (*AdminItemStateResp, error) {
	resp := &AdminItemStateResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/knowledge/items/state",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminOverviewReq is the request for AdminOverview.
type AdminOverviewReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminOverviewReqBuilder builds a AdminOverviewReq with a fluent setter per field.
type AdminOverviewReqBuilder struct{ req *AdminOverviewReq }

// NewAdminOverviewReqBuilder creates a request builder for AdminOverview.
func NewAdminOverviewReqBuilder() *AdminOverviewReqBuilder {
	return &AdminOverviewReqBuilder{req: &AdminOverviewReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *AdminOverviewReqBuilder) Build() *AdminOverviewReq { return b.req }

// AdminOverviewResp is the response for AdminOverview.
type AdminOverviewResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// AdminOverview: 知识库总览
func (s *Service) AdminOverview(ctx context.Context, req *AdminOverviewReq, opts ...core.RequestOption) (*AdminOverviewResp, error) {
	resp := &AdminOverviewResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/knowledge/overview",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminListSourcesReq is the request for AdminListSources.
type AdminListSourcesReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminListSourcesReqBuilder builds a AdminListSourcesReq with a fluent setter per field.
type AdminListSourcesReqBuilder struct{ req *AdminListSourcesReq }

// NewAdminListSourcesReqBuilder creates a request builder for AdminListSources.
func NewAdminListSourcesReqBuilder() *AdminListSourcesReqBuilder {
	return &AdminListSourcesReqBuilder{req: &AdminListSourcesReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *AdminListSourcesReqBuilder) Build() *AdminListSourcesReq { return b.req }

// AdminListSourcesResp is the response for AdminListSources.
type AdminListSourcesResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.KnowledgeSourceNode `json:"data"`
}

// AdminListSources: 来源列表
func (s *Service) AdminListSources(ctx context.Context, req *AdminListSourcesReq, opts ...core.RequestOption) (*AdminListSourcesResp, error) {
	resp := &AdminListSourcesResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/knowledge/sources",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminCreateSourceReq is the request for AdminCreateSource.
type AdminCreateSourceReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminCreateSourceReqBuilder builds a AdminCreateSourceReq with a fluent setter per field.
type AdminCreateSourceReqBuilder struct{ req *AdminCreateSourceReq }

// NewAdminCreateSourceReqBuilder creates a request builder for AdminCreateSource.
func NewAdminCreateSourceReqBuilder() *AdminCreateSourceReqBuilder {
	return &AdminCreateSourceReqBuilder{req: &AdminCreateSourceReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *AdminCreateSourceReqBuilder) Body(body *models.CreateSourceRequestBody) *AdminCreateSourceReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *AdminCreateSourceReqBuilder) Build() *AdminCreateSourceReq { return b.req }

// AdminCreateSourceResp is the response for AdminCreateSource.
type AdminCreateSourceResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.KnowledgeSourceNode `json:"data"`
}

// AdminCreateSource: 新建来源
func (s *Service) AdminCreateSource(ctx context.Context, req *AdminCreateSourceReq, opts ...core.RequestOption) (*AdminCreateSourceResp, error) {
	resp := &AdminCreateSourceResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/knowledge/sources",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminUpdateSourceReq is the request for AdminUpdateSource.
type AdminUpdateSourceReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminUpdateSourceReqBuilder builds a AdminUpdateSourceReq with a fluent setter per field.
type AdminUpdateSourceReqBuilder struct{ req *AdminUpdateSourceReq }

// NewAdminUpdateSourceReqBuilder creates a request builder for AdminUpdateSource.
func NewAdminUpdateSourceReqBuilder() *AdminUpdateSourceReqBuilder {
	return &AdminUpdateSourceReqBuilder{req: &AdminUpdateSourceReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" query parameter.
func (b *AdminUpdateSourceReqBuilder) Id(v string) *AdminUpdateSourceReqBuilder {
	b.req.queryParams["id"] = v
	return b
}

// Body sets the request body.
func (b *AdminUpdateSourceReqBuilder) Body(body *models.UpdateSourceRequestBody) *AdminUpdateSourceReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *AdminUpdateSourceReqBuilder) Build() *AdminUpdateSourceReq { return b.req }

// AdminUpdateSourceResp is the response for AdminUpdateSource.
type AdminUpdateSourceResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.KnowledgeSourceNode `json:"data"`
}

// AdminUpdateSource: 编辑来源
func (s *Service) AdminUpdateSource(ctx context.Context, req *AdminUpdateSourceReq, opts ...core.RequestOption) (*AdminUpdateSourceResp, error) {
	resp := &AdminUpdateSourceResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/knowledge/sources",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminDeleteSourceReq is the request for AdminDeleteSource.
type AdminDeleteSourceReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminDeleteSourceReqBuilder builds a AdminDeleteSourceReq with a fluent setter per field.
type AdminDeleteSourceReqBuilder struct{ req *AdminDeleteSourceReq }

// NewAdminDeleteSourceReqBuilder creates a request builder for AdminDeleteSource.
func NewAdminDeleteSourceReqBuilder() *AdminDeleteSourceReqBuilder {
	return &AdminDeleteSourceReqBuilder{req: &AdminDeleteSourceReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" query parameter.
func (b *AdminDeleteSourceReqBuilder) Id(v string) *AdminDeleteSourceReqBuilder {
	b.req.queryParams["id"] = v
	return b
}

// MergeIntoId sets the "merge_into_id" query parameter: 把条目并入目标来源后删除
func (b *AdminDeleteSourceReqBuilder) MergeIntoId(v string) *AdminDeleteSourceReqBuilder {
	b.req.queryParams["merge_into_id"] = v
	return b
}

// Build finalizes the request.
func (b *AdminDeleteSourceReqBuilder) Build() *AdminDeleteSourceReq { return b.req }

// AdminDeleteSourceResp is the response for AdminDeleteSource.
type AdminDeleteSourceResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// AdminDeleteSource: 删除来源
func (s *Service) AdminDeleteSource(ctx context.Context, req *AdminDeleteSourceReq, opts ...core.RequestOption) (*AdminDeleteSourceResp, error) {
	resp := &AdminDeleteSourceResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "DELETE",
		PathTemplate: "/hduhelp-neo/admin/knowledge/sources",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminGetTaggingPromptReq is the request for AdminGetTaggingPrompt.
type AdminGetTaggingPromptReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminGetTaggingPromptReqBuilder builds a AdminGetTaggingPromptReq with a fluent setter per field.
type AdminGetTaggingPromptReqBuilder struct{ req *AdminGetTaggingPromptReq }

// NewAdminGetTaggingPromptReqBuilder creates a request builder for AdminGetTaggingPrompt.
func NewAdminGetTaggingPromptReqBuilder() *AdminGetTaggingPromptReqBuilder {
	return &AdminGetTaggingPromptReqBuilder{req: &AdminGetTaggingPromptReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *AdminGetTaggingPromptReqBuilder) Build() *AdminGetTaggingPromptReq { return b.req }

// AdminGetTaggingPromptResp is the response for AdminGetTaggingPrompt.
type AdminGetTaggingPromptResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.TaggingPromptData `json:"data"`
}

// AdminGetTaggingPrompt: 获取AI打标提示词
func (s *Service) AdminGetTaggingPrompt(ctx context.Context, req *AdminGetTaggingPromptReq, opts ...core.RequestOption) (*AdminGetTaggingPromptResp, error) {
	resp := &AdminGetTaggingPromptResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/knowledge/tagging-prompt",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminSetTaggingPromptReq is the request for AdminSetTaggingPrompt.
type AdminSetTaggingPromptReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminSetTaggingPromptReqBuilder builds a AdminSetTaggingPromptReq with a fluent setter per field.
type AdminSetTaggingPromptReqBuilder struct{ req *AdminSetTaggingPromptReq }

// NewAdminSetTaggingPromptReqBuilder creates a request builder for AdminSetTaggingPrompt.
func NewAdminSetTaggingPromptReqBuilder() *AdminSetTaggingPromptReqBuilder {
	return &AdminSetTaggingPromptReqBuilder{req: &AdminSetTaggingPromptReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *AdminSetTaggingPromptReqBuilder) Body(body *models.SetTaggingPromptRequestBody) *AdminSetTaggingPromptReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *AdminSetTaggingPromptReqBuilder) Build() *AdminSetTaggingPromptReq { return b.req }

// AdminSetTaggingPromptResp is the response for AdminSetTaggingPrompt.
type AdminSetTaggingPromptResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.TaggingPromptData `json:"data"`
}

// AdminSetTaggingPrompt: 保存AI打标提示词
func (s *Service) AdminSetTaggingPrompt(ctx context.Context, req *AdminSetTaggingPromptReq, opts ...core.RequestOption) (*AdminSetTaggingPromptResp, error) {
	resp := &AdminSetTaggingPromptResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/knowledge/tagging-prompt",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminPreviewTaggingPromptReq is the request for AdminPreviewTaggingPrompt.
type AdminPreviewTaggingPromptReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminPreviewTaggingPromptReqBuilder builds a AdminPreviewTaggingPromptReq with a fluent setter per field.
type AdminPreviewTaggingPromptReqBuilder struct{ req *AdminPreviewTaggingPromptReq }

// NewAdminPreviewTaggingPromptReqBuilder creates a request builder for AdminPreviewTaggingPrompt.
func NewAdminPreviewTaggingPromptReqBuilder() *AdminPreviewTaggingPromptReqBuilder {
	return &AdminPreviewTaggingPromptReqBuilder{req: &AdminPreviewTaggingPromptReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *AdminPreviewTaggingPromptReqBuilder) Body(body *models.SetTaggingPromptRequestBody) *AdminPreviewTaggingPromptReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *AdminPreviewTaggingPromptReqBuilder) Build() *AdminPreviewTaggingPromptReq { return b.req }

// AdminPreviewTaggingPromptResp is the response for AdminPreviewTaggingPrompt.
type AdminPreviewTaggingPromptResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.PreviewData `json:"data"`
}

// AdminPreviewTaggingPrompt: 预览AI打标提示词
func (s *Service) AdminPreviewTaggingPrompt(ctx context.Context, req *AdminPreviewTaggingPromptReq, opts ...core.RequestOption) (*AdminPreviewTaggingPromptResp, error) {
	resp := &AdminPreviewTaggingPromptResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/knowledge/tagging-prompt/preview",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminUploadFileReq is the request for AdminUploadFile.
type AdminUploadFileReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminUploadFileReqBuilder builds a AdminUploadFileReq with a fluent setter per field.
type AdminUploadFileReqBuilder struct{ req *AdminUploadFileReq }

// NewAdminUploadFileReqBuilder creates a request builder for AdminUploadFile.
func NewAdminUploadFileReqBuilder() *AdminUploadFileReqBuilder {
	return &AdminUploadFileReqBuilder{req: &AdminUploadFileReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *AdminUploadFileReqBuilder) Build() *AdminUploadFileReq { return b.req }

// AdminUploadFileResp is the response for AdminUploadFile.
type AdminUploadFileResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.UploadFileData `json:"data"`
}

// AdminUploadFile: 上传文件
func (s *Service) AdminUploadFile(ctx context.Context, req *AdminUploadFileReq, opts ...core.RequestOption) (*AdminUploadFileResp, error) {
	resp := &AdminUploadFileResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/knowledge/upload",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// KnowledgeDomainsReq is the request for KnowledgeDomains.
type KnowledgeDomainsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// KnowledgeDomainsReqBuilder builds a KnowledgeDomainsReq with a fluent setter per field.
type KnowledgeDomainsReqBuilder struct{ req *KnowledgeDomainsReq }

// NewKnowledgeDomainsReqBuilder creates a request builder for KnowledgeDomains.
func NewKnowledgeDomainsReqBuilder() *KnowledgeDomainsReqBuilder {
	return &KnowledgeDomainsReqBuilder{req: &KnowledgeDomainsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *KnowledgeDomainsReqBuilder) Build() *KnowledgeDomainsReq { return b.req }

// KnowledgeDomainsResp is the response for KnowledgeDomains.
type KnowledgeDomainsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.KnowledgeDomainNode `json:"data"`
}

// KnowledgeDomains: 知识域树
func (s *Service) KnowledgeDomains(ctx context.Context, req *KnowledgeDomainsReq, opts ...core.RequestOption) (*KnowledgeDomainsResp, error) {
	resp := &KnowledgeDomainsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/knowledge/domains",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// KnowledgeReportGapReq is the request for KnowledgeReportGap.
type KnowledgeReportGapReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// KnowledgeReportGapReqBuilder builds a KnowledgeReportGapReq with a fluent setter per field.
type KnowledgeReportGapReqBuilder struct{ req *KnowledgeReportGapReq }

// NewKnowledgeReportGapReqBuilder creates a request builder for KnowledgeReportGap.
func NewKnowledgeReportGapReqBuilder() *KnowledgeReportGapReqBuilder {
	return &KnowledgeReportGapReqBuilder{req: &KnowledgeReportGapReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *KnowledgeReportGapReqBuilder) Body(body *models.ReportGapRequestBody) *KnowledgeReportGapReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *KnowledgeReportGapReqBuilder) Build() *KnowledgeReportGapReq { return b.req }

// KnowledgeReportGapResp is the response for KnowledgeReportGap.
type KnowledgeReportGapResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// KnowledgeReportGap: 上报知识盲区
func (s *Service) KnowledgeReportGap(ctx context.Context, req *KnowledgeReportGapReq, opts ...core.RequestOption) (*KnowledgeReportGapResp, error) {
	resp := &KnowledgeReportGapResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/knowledge/gaps",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// KnowledgeSearchReq is the request for KnowledgeSearch.
type KnowledgeSearchReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// KnowledgeSearchReqBuilder builds a KnowledgeSearchReq with a fluent setter per field.
type KnowledgeSearchReqBuilder struct{ req *KnowledgeSearchReq }

// NewKnowledgeSearchReqBuilder creates a request builder for KnowledgeSearch.
func NewKnowledgeSearchReqBuilder() *KnowledgeSearchReqBuilder {
	return &KnowledgeSearchReqBuilder{req: &KnowledgeSearchReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *KnowledgeSearchReqBuilder) Body(body *models.SearchRequestBody) *KnowledgeSearchReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *KnowledgeSearchReqBuilder) Build() *KnowledgeSearchReq { return b.req }

// KnowledgeSearchResp is the response for KnowledgeSearch.
type KnowledgeSearchResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.SearchHit `json:"data"`
}

// KnowledgeSearch: 知识检索
func (s *Service) KnowledgeSearch(ctx context.Context, req *KnowledgeSearchReq, opts ...core.RequestOption) (*KnowledgeSearchResp, error) {
	resp := &KnowledgeSearchResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/knowledge/search",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}
