// Code generated by hduhelp-sdk-gen; DO NOT EDIT.

package librarybooking

import (
	"context"
	"strconv"

	"github.com/hduhelp/hduhelp-neo-sdk-go/core"
	"github.com/hduhelp/hduhelp-neo-sdk-go/models"
)

// Service groups the LibraryBooking endpoints.
type Service struct{ config *core.Config }

// NewService binds the LibraryBooking service to a client config.
func NewService(config *core.Config) *Service { return &Service{config: config} }

// ListMyBookingsReq is the request for ListMyBookings.
type ListMyBookingsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListMyBookingsReqBuilder builds a ListMyBookingsReq with a fluent setter per field.
type ListMyBookingsReqBuilder struct{ req *ListMyBookingsReq }

// NewListMyBookingsReqBuilder creates a request builder for ListMyBookings.
func NewListMyBookingsReqBuilder() *ListMyBookingsReqBuilder {
	return &ListMyBookingsReqBuilder{req: &ListMyBookingsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *ListMyBookingsReqBuilder) Build() *ListMyBookingsReq { return b.req }

// ListMyBookingsResp is the response for ListMyBookings.
type ListMyBookingsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.BookingListData `json:"data"`
}

// ListMyBookings: 查询我的图书馆座位预约
func (s *Service) ListMyBookings(ctx context.Context, req *ListMyBookingsReq, opts ...core.RequestOption) (*ListMyBookingsResp, error) {
	resp := &ListMyBookingsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/library-booking/bookings",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// CreateBookingReq is the request for CreateBooking.
type CreateBookingReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// CreateBookingReqBuilder builds a CreateBookingReq with a fluent setter per field.
type CreateBookingReqBuilder struct{ req *CreateBookingReq }

// NewCreateBookingReqBuilder creates a request builder for CreateBooking.
func NewCreateBookingReqBuilder() *CreateBookingReqBuilder {
	return &CreateBookingReqBuilder{req: &CreateBookingReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *CreateBookingReqBuilder) Body(body *models.CreateBookingRequestBody) *CreateBookingReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *CreateBookingReqBuilder) Build() *CreateBookingReq { return b.req }

// CreateBookingResp is the response for CreateBooking.
type CreateBookingResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.BookingResultData `json:"data"`
}

// CreateBooking: 预约选定图书馆座位
func (s *Service) CreateBooking(ctx context.Context, req *CreateBookingReq, opts ...core.RequestOption) (*CreateBookingResp, error) {
	resp := &CreateBookingResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/library-booking/bookings",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// CancelBookingReq is the request for CancelBooking.
type CancelBookingReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// CancelBookingReqBuilder builds a CancelBookingReq with a fluent setter per field.
type CancelBookingReqBuilder struct{ req *CancelBookingReq }

// NewCancelBookingReqBuilder creates a request builder for CancelBooking.
func NewCancelBookingReqBuilder() *CancelBookingReqBuilder {
	return &CancelBookingReqBuilder{req: &CancelBookingReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// BookingId sets the "bookingId" path parameter.
func (b *CancelBookingReqBuilder) BookingId(v string) *CancelBookingReqBuilder {
	b.req.pathParams["bookingId"] = v
	return b
}

// Build finalizes the request.
func (b *CancelBookingReqBuilder) Build() *CancelBookingReq { return b.req }

// CancelBookingResp is the response for CancelBooking.
type CancelBookingResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.CancelBookingData `json:"data"`
}

// CancelBooking: 取消选定图书馆座位预约
func (s *Service) CancelBooking(ctx context.Context, req *CancelBookingReq, opts ...core.RequestOption) (*CancelBookingResp, error) {
	resp := &CancelBookingResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "DELETE",
		PathTemplate: "/hduhelp-neo/library-booking/bookings/{bookingId}",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListSpaceCategoriesReq is the request for ListSpaceCategories.
type ListSpaceCategoriesReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListSpaceCategoriesReqBuilder builds a ListSpaceCategoriesReq with a fluent setter per field.
type ListSpaceCategoriesReqBuilder struct{ req *ListSpaceCategoriesReq }

// NewListSpaceCategoriesReqBuilder creates a request builder for ListSpaceCategories.
func NewListSpaceCategoriesReqBuilder() *ListSpaceCategoriesReqBuilder {
	return &ListSpaceCategoriesReqBuilder{req: &ListSpaceCategoriesReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *ListSpaceCategoriesReqBuilder) Build() *ListSpaceCategoriesReq { return b.req }

// ListSpaceCategoriesResp is the response for ListSpaceCategories.
type ListSpaceCategoriesResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.Category `json:"data"`
}

// ListSpaceCategories: 查询图书馆座位空间分类
func (s *Service) ListSpaceCategories(ctx context.Context, req *ListSpaceCategoriesReq, opts ...core.RequestOption) (*ListSpaceCategoriesResp, error) {
	resp := &ListSpaceCategoriesResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/library-booking/categories",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// GetBookingOptionsReq is the request for GetBookingOptions.
type GetBookingOptionsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// GetBookingOptionsReqBuilder builds a GetBookingOptionsReq with a fluent setter per field.
type GetBookingOptionsReqBuilder struct{ req *GetBookingOptionsReq }

// NewGetBookingOptionsReqBuilder creates a request builder for GetBookingOptions.
func NewGetBookingOptionsReqBuilder() *GetBookingOptionsReqBuilder {
	return &GetBookingOptionsReqBuilder{req: &GetBookingOptionsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// CategoryId sets the "categoryId" query parameter: 空间分类接口返回的 categoryId。
func (b *GetBookingOptionsReqBuilder) CategoryId(v string) *GetBookingOptionsReqBuilder {
	b.req.queryParams["categoryId"] = v
	return b
}

// ContentId sets the "contentId" query parameter: 空间分类接口返回的 contentId。
func (b *GetBookingOptionsReqBuilder) ContentId(v string) *GetBookingOptionsReqBuilder {
	b.req.queryParams["contentId"] = v
	return b
}

// Build finalizes the request.
func (b *GetBookingOptionsReqBuilder) Build() *GetBookingOptionsReq { return b.req }

// GetBookingOptionsResp is the response for GetBookingOptions.
type GetBookingOptionsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.BookingOptionsData `json:"data"`
}

// GetBookingOptions: 查询空间可预约日期和时间
func (s *Service) GetBookingOptions(ctx context.Context, req *GetBookingOptionsReq, opts ...core.RequestOption) (*GetBookingOptionsResp, error) {
	resp := &GetBookingOptionsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/library-booking/options",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// SearchAvailableSeatsReq is the request for SearchAvailableSeats.
type SearchAvailableSeatsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// SearchAvailableSeatsReqBuilder builds a SearchAvailableSeatsReq with a fluent setter per field.
type SearchAvailableSeatsReqBuilder struct{ req *SearchAvailableSeatsReq }

// NewSearchAvailableSeatsReqBuilder creates a request builder for SearchAvailableSeats.
func NewSearchAvailableSeatsReqBuilder() *SearchAvailableSeatsReqBuilder {
	return &SearchAvailableSeatsReqBuilder{req: &SearchAvailableSeatsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// CategoryId sets the "categoryId" query parameter: 空间分类接口返回的 categoryId。
func (b *SearchAvailableSeatsReqBuilder) CategoryId(v string) *SearchAvailableSeatsReqBuilder {
	b.req.queryParams["categoryId"] = v
	return b
}

// ContentId sets the "contentId" query parameter: 空间分类接口返回的 contentId。
func (b *SearchAvailableSeatsReqBuilder) ContentId(v string) *SearchAvailableSeatsReqBuilder {
	b.req.queryParams["contentId"] = v
	return b
}

// Date sets the "date" query parameter: options 返回的日期，格式 YYYY-MM-DD。
func (b *SearchAvailableSeatsReqBuilder) Date(v string) *SearchAvailableSeatsReqBuilder {
	b.req.queryParams["date"] = v
	return b
}

// BeginTime sets the "beginTime" query parameter: options 返回的开始时间，格式 HH:mm。
func (b *SearchAvailableSeatsReqBuilder) BeginTime(v string) *SearchAvailableSeatsReqBuilder {
	b.req.queryParams["beginTime"] = v
	return b
}

// DurationHours sets the "durationHours" query parameter: 所选开始时间的 durationHours 列表中的一个值。
func (b *SearchAvailableSeatsReqBuilder) DurationHours(v int32) *SearchAvailableSeatsReqBuilder {
	b.req.queryParams["durationHours"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Build finalizes the request.
func (b *SearchAvailableSeatsReqBuilder) Build() *SearchAvailableSeatsReq { return b.req }

// SearchAvailableSeatsResp is the response for SearchAvailableSeats.
type SearchAvailableSeatsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.SeatSearchData `json:"data"`
}

// SearchAvailableSeats: 实时查询图书馆座位
func (s *Service) SearchAvailableSeats(ctx context.Context, req *SearchAvailableSeatsReq, opts ...core.RequestOption) (*SearchAvailableSeatsResp, error) {
	resp := &SearchAvailableSeatsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/library-booking/seats/search",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}
