// Code generated by hduhelp-sdk-gen; DO NOT EDIT.

package siteannouncement

import (
	"context"
	"strconv"

	"github.com/hduhelp/hduhelp-neo-sdk-go/core"
	"github.com/hduhelp/hduhelp-neo-sdk-go/models"
)

// Service groups the SiteAnnouncement endpoints.
type Service struct{ config *core.Config }

// NewService binds the SiteAnnouncement service to a client config.
func NewService(config *core.Config) *Service { return &Service{config: config} }

// ListSiteAnnouncementsReq is the request for ListSiteAnnouncements.
type ListSiteAnnouncementsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListSiteAnnouncementsReqBuilder builds a ListSiteAnnouncementsReq with a fluent setter per field.
type ListSiteAnnouncementsReqBuilder struct{ req *ListSiteAnnouncementsReq }

// NewListSiteAnnouncementsReqBuilder creates a request builder for ListSiteAnnouncements.
func NewListSiteAnnouncementsReqBuilder() *ListSiteAnnouncementsReqBuilder {
	return &ListSiteAnnouncementsReqBuilder{req: &ListSiteAnnouncementsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Page sets the "page" query parameter.
func (b *ListSiteAnnouncementsReqBuilder) Page(v int32) *ListSiteAnnouncementsReqBuilder {
	b.req.queryParams["page"] = strconv.FormatInt(int64(v), 10)
	return b
}

// PageSize sets the "page_size" query parameter.
func (b *ListSiteAnnouncementsReqBuilder) PageSize(v int32) *ListSiteAnnouncementsReqBuilder {
	b.req.queryParams["page_size"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Status sets the "status" query parameter.
func (b *ListSiteAnnouncementsReqBuilder) Status(v string) *ListSiteAnnouncementsReqBuilder {
	b.req.queryParams["status"] = v
	return b
}

// Build finalizes the request.
func (b *ListSiteAnnouncementsReqBuilder) Build() *ListSiteAnnouncementsReq { return b.req }

// ListSiteAnnouncementsResp is the response for ListSiteAnnouncements.
type ListSiteAnnouncementsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.SiteAnnouncementPage `json:"data"`
}

// ListSiteAnnouncements calls GET /hduhelp-neo/admin/site-announcements.
func (s *Service) ListSiteAnnouncements(ctx context.Context, req *ListSiteAnnouncementsReq, opts ...core.RequestOption) (*ListSiteAnnouncementsResp, error) {
	resp := &ListSiteAnnouncementsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/site-announcements",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// CreateSiteAnnouncementReq is the request for CreateSiteAnnouncement.
type CreateSiteAnnouncementReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// CreateSiteAnnouncementReqBuilder builds a CreateSiteAnnouncementReq with a fluent setter per field.
type CreateSiteAnnouncementReqBuilder struct{ req *CreateSiteAnnouncementReq }

// NewCreateSiteAnnouncementReqBuilder creates a request builder for CreateSiteAnnouncement.
func NewCreateSiteAnnouncementReqBuilder() *CreateSiteAnnouncementReqBuilder {
	return &CreateSiteAnnouncementReqBuilder{req: &CreateSiteAnnouncementReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *CreateSiteAnnouncementReqBuilder) Body(body *models.CreateSiteAnnouncementRequestBody) *CreateSiteAnnouncementReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *CreateSiteAnnouncementReqBuilder) Build() *CreateSiteAnnouncementReq { return b.req }

// CreateSiteAnnouncementResp is the response for CreateSiteAnnouncement.
type CreateSiteAnnouncementResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.SiteAnnouncement `json:"data"`
}

// CreateSiteAnnouncement calls POST /hduhelp-neo/admin/site-announcements.
func (s *Service) CreateSiteAnnouncement(ctx context.Context, req *CreateSiteAnnouncementReq, opts ...core.RequestOption) (*CreateSiteAnnouncementResp, error) {
	resp := &CreateSiteAnnouncementResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/site-announcements",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// GetSiteAnnouncementReq is the request for GetSiteAnnouncement.
type GetSiteAnnouncementReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// GetSiteAnnouncementReqBuilder builds a GetSiteAnnouncementReq with a fluent setter per field.
type GetSiteAnnouncementReqBuilder struct{ req *GetSiteAnnouncementReq }

// NewGetSiteAnnouncementReqBuilder creates a request builder for GetSiteAnnouncement.
func NewGetSiteAnnouncementReqBuilder() *GetSiteAnnouncementReqBuilder {
	return &GetSiteAnnouncementReqBuilder{req: &GetSiteAnnouncementReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *GetSiteAnnouncementReqBuilder) Id(v string) *GetSiteAnnouncementReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Build finalizes the request.
func (b *GetSiteAnnouncementReqBuilder) Build() *GetSiteAnnouncementReq { return b.req }

// GetSiteAnnouncementResp is the response for GetSiteAnnouncement.
type GetSiteAnnouncementResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.SiteAnnouncement `json:"data"`
}

// GetSiteAnnouncement calls GET /hduhelp-neo/admin/site-announcements/{id}.
func (s *Service) GetSiteAnnouncement(ctx context.Context, req *GetSiteAnnouncementReq, opts ...core.RequestOption) (*GetSiteAnnouncementResp, error) {
	resp := &GetSiteAnnouncementResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/site-announcements/{id}",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// UpdateSiteAnnouncementReq is the request for UpdateSiteAnnouncement.
type UpdateSiteAnnouncementReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// UpdateSiteAnnouncementReqBuilder builds a UpdateSiteAnnouncementReq with a fluent setter per field.
type UpdateSiteAnnouncementReqBuilder struct{ req *UpdateSiteAnnouncementReq }

// NewUpdateSiteAnnouncementReqBuilder creates a request builder for UpdateSiteAnnouncement.
func NewUpdateSiteAnnouncementReqBuilder() *UpdateSiteAnnouncementReqBuilder {
	return &UpdateSiteAnnouncementReqBuilder{req: &UpdateSiteAnnouncementReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *UpdateSiteAnnouncementReqBuilder) Id(v string) *UpdateSiteAnnouncementReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Body sets the request body.
func (b *UpdateSiteAnnouncementReqBuilder) Body(body *models.UpdateSiteAnnouncementRequestBody) *UpdateSiteAnnouncementReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *UpdateSiteAnnouncementReqBuilder) Build() *UpdateSiteAnnouncementReq { return b.req }

// UpdateSiteAnnouncementResp is the response for UpdateSiteAnnouncement.
type UpdateSiteAnnouncementResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.SiteAnnouncement `json:"data"`
}

// UpdateSiteAnnouncement calls PUT /hduhelp-neo/admin/site-announcements/{id}.
func (s *Service) UpdateSiteAnnouncement(ctx context.Context, req *UpdateSiteAnnouncementReq, opts ...core.RequestOption) (*UpdateSiteAnnouncementResp, error) {
	resp := &UpdateSiteAnnouncementResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/site-announcements/{id}",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// DeleteSiteAnnouncementReq is the request for DeleteSiteAnnouncement.
type DeleteSiteAnnouncementReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// DeleteSiteAnnouncementReqBuilder builds a DeleteSiteAnnouncementReq with a fluent setter per field.
type DeleteSiteAnnouncementReqBuilder struct{ req *DeleteSiteAnnouncementReq }

// NewDeleteSiteAnnouncementReqBuilder creates a request builder for DeleteSiteAnnouncement.
func NewDeleteSiteAnnouncementReqBuilder() *DeleteSiteAnnouncementReqBuilder {
	return &DeleteSiteAnnouncementReqBuilder{req: &DeleteSiteAnnouncementReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *DeleteSiteAnnouncementReqBuilder) Id(v string) *DeleteSiteAnnouncementReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Build finalizes the request.
func (b *DeleteSiteAnnouncementReqBuilder) Build() *DeleteSiteAnnouncementReq { return b.req }

// DeleteSiteAnnouncementResp is the response for DeleteSiteAnnouncement.
type DeleteSiteAnnouncementResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// DeleteSiteAnnouncement calls DELETE /hduhelp-neo/admin/site-announcements/{id}.
func (s *Service) DeleteSiteAnnouncement(ctx context.Context, req *DeleteSiteAnnouncementReq, opts ...core.RequestOption) (*DeleteSiteAnnouncementResp, error) {
	resp := &DeleteSiteAnnouncementResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "DELETE",
		PathTemplate: "/hduhelp-neo/admin/site-announcements/{id}",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ArchiveSiteAnnouncementReq is the request for ArchiveSiteAnnouncement.
type ArchiveSiteAnnouncementReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ArchiveSiteAnnouncementReqBuilder builds a ArchiveSiteAnnouncementReq with a fluent setter per field.
type ArchiveSiteAnnouncementReqBuilder struct{ req *ArchiveSiteAnnouncementReq }

// NewArchiveSiteAnnouncementReqBuilder creates a request builder for ArchiveSiteAnnouncement.
func NewArchiveSiteAnnouncementReqBuilder() *ArchiveSiteAnnouncementReqBuilder {
	return &ArchiveSiteAnnouncementReqBuilder{req: &ArchiveSiteAnnouncementReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *ArchiveSiteAnnouncementReqBuilder) Id(v string) *ArchiveSiteAnnouncementReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Build finalizes the request.
func (b *ArchiveSiteAnnouncementReqBuilder) Build() *ArchiveSiteAnnouncementReq { return b.req }

// ArchiveSiteAnnouncementResp is the response for ArchiveSiteAnnouncement.
type ArchiveSiteAnnouncementResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.SiteAnnouncement `json:"data"`
}

// ArchiveSiteAnnouncement calls POST /hduhelp-neo/admin/site-announcements/{id}/archive.
func (s *Service) ArchiveSiteAnnouncement(ctx context.Context, req *ArchiveSiteAnnouncementReq, opts ...core.RequestOption) (*ArchiveSiteAnnouncementResp, error) {
	resp := &ArchiveSiteAnnouncementResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/site-announcements/{id}/archive",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// PublishSiteAnnouncementReq is the request for PublishSiteAnnouncement.
type PublishSiteAnnouncementReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// PublishSiteAnnouncementReqBuilder builds a PublishSiteAnnouncementReq with a fluent setter per field.
type PublishSiteAnnouncementReqBuilder struct{ req *PublishSiteAnnouncementReq }

// NewPublishSiteAnnouncementReqBuilder creates a request builder for PublishSiteAnnouncement.
func NewPublishSiteAnnouncementReqBuilder() *PublishSiteAnnouncementReqBuilder {
	return &PublishSiteAnnouncementReqBuilder{req: &PublishSiteAnnouncementReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *PublishSiteAnnouncementReqBuilder) Id(v string) *PublishSiteAnnouncementReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Build finalizes the request.
func (b *PublishSiteAnnouncementReqBuilder) Build() *PublishSiteAnnouncementReq { return b.req }

// PublishSiteAnnouncementResp is the response for PublishSiteAnnouncement.
type PublishSiteAnnouncementResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.SiteAnnouncement `json:"data"`
}

// PublishSiteAnnouncement calls POST /hduhelp-neo/admin/site-announcements/{id}/publish.
func (s *Service) PublishSiteAnnouncement(ctx context.Context, req *PublishSiteAnnouncementReq, opts ...core.RequestOption) (*PublishSiteAnnouncementResp, error) {
	resp := &PublishSiteAnnouncementResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/site-announcements/{id}/publish",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// GetActiveSiteAnnouncementReq is the request for GetActiveSiteAnnouncement.
type GetActiveSiteAnnouncementReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// GetActiveSiteAnnouncementReqBuilder builds a GetActiveSiteAnnouncementReq with a fluent setter per field.
type GetActiveSiteAnnouncementReqBuilder struct{ req *GetActiveSiteAnnouncementReq }

// NewGetActiveSiteAnnouncementReqBuilder creates a request builder for GetActiveSiteAnnouncement.
func NewGetActiveSiteAnnouncementReqBuilder() *GetActiveSiteAnnouncementReqBuilder {
	return &GetActiveSiteAnnouncementReqBuilder{req: &GetActiveSiteAnnouncementReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *GetActiveSiteAnnouncementReqBuilder) Build() *GetActiveSiteAnnouncementReq { return b.req }

// GetActiveSiteAnnouncementResp is the response for GetActiveSiteAnnouncement.
type GetActiveSiteAnnouncementResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.SiteAnnouncement `json:"data"`
}

// GetActiveSiteAnnouncement: 当前全站公告
func (s *Service) GetActiveSiteAnnouncement(ctx context.Context, req *GetActiveSiteAnnouncementReq, opts ...core.RequestOption) (*GetActiveSiteAnnouncementResp, error) {
	resp := &GetActiveSiteAnnouncementResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/site-announcements/active",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}
