// Code generated by hduhelp-sdk-gen; DO NOT EDIT.

package emptyschedule

import (
	"context"
	"strconv"

	"github.com/hduhelp/hduhelp-neo-sdk-go/core"
	"github.com/hduhelp/hduhelp-neo-sdk-go/models"
)

// Service groups the EmptySchedule endpoints.
type Service struct{ config *core.Config }

// NewService binds the EmptySchedule service to a client config.
func NewService(config *core.Config) *Service { return &Service{config: config} }

// EnrollReq is the request for Enroll.
type EnrollReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// EnrollReqBuilder builds a EnrollReq with a fluent setter per field.
type EnrollReqBuilder struct{ req *EnrollReq }

// NewEnrollReqBuilder creates a request builder for Enroll.
func NewEnrollReqBuilder() *EnrollReqBuilder {
	return &EnrollReqBuilder{req: &EnrollReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *EnrollReqBuilder) Body(body *models.EnrollRequestBody) *EnrollReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *EnrollReqBuilder) Build() *EnrollReq { return b.req }

// EnrollResp is the response for Enroll.
type EnrollResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.EnrollData `json:"data"`
}

// Enroll: 口令组队报名
func (s *Service) Enroll(ctx context.Context, req *EnrollReq, opts ...core.RequestOption) (*EnrollResp, error) {
	resp := &EnrollResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/emptyschedule/enroll",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// EventResultReq is the request for EventResult.
type EventResultReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// EventResultReqBuilder builds a EventResultReq with a fluent setter per field.
type EventResultReqBuilder struct{ req *EventResultReq }

// NewEventResultReqBuilder creates a request builder for EventResult.
func NewEventResultReqBuilder() *EventResultReqBuilder {
	return &EventResultReqBuilder{req: &EventResultReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// RoomId sets the "room_id" query parameter.
func (b *EventResultReqBuilder) RoomId(v string) *EventResultReqBuilder {
	b.req.queryParams["room_id"] = v
	return b
}

// EventId sets the "event_id" query parameter.
func (b *EventResultReqBuilder) EventId(v string) *EventResultReqBuilder {
	b.req.queryParams["event_id"] = v
	return b
}

// Build finalizes the request.
func (b *EventResultReqBuilder) Build() *EventResultReq { return b.req }

// EventResultResp is the response for EventResult.
type EventResultResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.EventResultData `json:"data"`
}

// EventResult: 获取排班结果详情
func (s *Service) EventResult(ctx context.Context, req *EventResultReq, opts ...core.RequestOption) (*EventResultResp, error) {
	resp := &EventResultResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/emptyschedule/events",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// DeleteEventReq is the request for DeleteEvent.
type DeleteEventReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// DeleteEventReqBuilder builds a DeleteEventReq with a fluent setter per field.
type DeleteEventReqBuilder struct{ req *DeleteEventReq }

// NewDeleteEventReqBuilder creates a request builder for DeleteEvent.
func NewDeleteEventReqBuilder() *DeleteEventReqBuilder {
	return &DeleteEventReqBuilder{req: &DeleteEventReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// RoomId sets the "room_id" query parameter.
func (b *DeleteEventReqBuilder) RoomId(v string) *DeleteEventReqBuilder {
	b.req.queryParams["room_id"] = v
	return b
}

// EventId sets the "event_id" query parameter.
func (b *DeleteEventReqBuilder) EventId(v string) *DeleteEventReqBuilder {
	b.req.queryParams["event_id"] = v
	return b
}

// Build finalizes the request.
func (b *DeleteEventReqBuilder) Build() *DeleteEventReq { return b.req }

// DeleteEventResp is the response for DeleteEvent.
type DeleteEventResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// DeleteEvent: 删除排班结果
func (s *Service) DeleteEvent(ctx context.Context, req *DeleteEventReq, opts ...core.RequestOption) (*DeleteEventResp, error) {
	resp := &DeleteEventResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "DELETE",
		PathTemplate: "/hduhelp-neo/emptyschedule/events",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ShareReq is the request for Share.
type ShareReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ShareReqBuilder builds a ShareReq with a fluent setter per field.
type ShareReqBuilder struct{ req *ShareReq }

// NewShareReqBuilder creates a request builder for Share.
func NewShareReqBuilder() *ShareReqBuilder {
	return &ShareReqBuilder{req: &ShareReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *ShareReqBuilder) Body(body *models.ShareRequestBody) *ShareReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *ShareReqBuilder) Build() *ShareReq { return b.req }

// ShareResp is the response for Share.
type ShareResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.ShareData `json:"data"`
}

// Share: 分享排班结果生成分享码
func (s *Service) Share(ctx context.Context, req *ShareReq, opts ...core.RequestOption) (*ShareResp, error) {
	resp := &ShareResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/emptyschedule/events/share",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// FavoritesReq is the request for Favorites.
type FavoritesReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// FavoritesReqBuilder builds a FavoritesReq with a fluent setter per field.
type FavoritesReqBuilder struct{ req *FavoritesReq }

// NewFavoritesReqBuilder creates a request builder for Favorites.
func NewFavoritesReqBuilder() *FavoritesReqBuilder {
	return &FavoritesReqBuilder{req: &FavoritesReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Page sets the "page" query parameter.
func (b *FavoritesReqBuilder) Page(v int32) *FavoritesReqBuilder {
	b.req.queryParams["page"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Size sets the "size" query parameter.
func (b *FavoritesReqBuilder) Size(v int32) *FavoritesReqBuilder {
	b.req.queryParams["size"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Build finalizes the request.
func (b *FavoritesReqBuilder) Build() *FavoritesReq { return b.req }

// FavoritesResp is the response for Favorites.
type FavoritesResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.FavoritesData `json:"data"`
}

// Favorites: 收藏列表
func (s *Service) Favorites(ctx context.Context, req *FavoritesReq, opts ...core.RequestOption) (*FavoritesResp, error) {
	resp := &FavoritesResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/emptyschedule/favorites",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// FavoriteReq is the request for Favorite.
type FavoriteReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// FavoriteReqBuilder builds a FavoriteReq with a fluent setter per field.
type FavoriteReqBuilder struct{ req *FavoriteReq }

// NewFavoriteReqBuilder creates a request builder for Favorite.
func NewFavoriteReqBuilder() *FavoriteReqBuilder {
	return &FavoriteReqBuilder{req: &FavoriteReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *FavoriteReqBuilder) Body(body *models.FavoriteRequestBody) *FavoriteReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *FavoriteReqBuilder) Build() *FavoriteReq { return b.req }

// FavoriteResp is the response for Favorite.
type FavoriteResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.FavoriteData `json:"data"`
}

// Favorite: 收藏排班结果
func (s *Service) Favorite(ctx context.Context, req *FavoriteReq, opts ...core.RequestOption) (*FavoriteResp, error) {
	resp := &FavoriteResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/emptyschedule/favorites",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// UpdateFavoriteReq is the request for UpdateFavorite.
type UpdateFavoriteReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// UpdateFavoriteReqBuilder builds a UpdateFavoriteReq with a fluent setter per field.
type UpdateFavoriteReqBuilder struct{ req *UpdateFavoriteReq }

// NewUpdateFavoriteReqBuilder creates a request builder for UpdateFavorite.
func NewUpdateFavoriteReqBuilder() *UpdateFavoriteReqBuilder {
	return &UpdateFavoriteReqBuilder{req: &UpdateFavoriteReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *UpdateFavoriteReqBuilder) Body(body *models.UpdateFavoriteRequestBody) *UpdateFavoriteReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *UpdateFavoriteReqBuilder) Build() *UpdateFavoriteReq { return b.req }

// UpdateFavoriteResp is the response for UpdateFavorite.
type UpdateFavoriteResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.FavoriteItem `json:"data"`
}

// UpdateFavorite: 修改收藏备注
func (s *Service) UpdateFavorite(ctx context.Context, req *UpdateFavoriteReq, opts ...core.RequestOption) (*UpdateFavoriteResp, error) {
	resp := &UpdateFavoriteResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/emptyschedule/favorites",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// DeleteFavoriteReq is the request for DeleteFavorite.
type DeleteFavoriteReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// DeleteFavoriteReqBuilder builds a DeleteFavoriteReq with a fluent setter per field.
type DeleteFavoriteReqBuilder struct{ req *DeleteFavoriteReq }

// NewDeleteFavoriteReqBuilder creates a request builder for DeleteFavorite.
func NewDeleteFavoriteReqBuilder() *DeleteFavoriteReqBuilder {
	return &DeleteFavoriteReqBuilder{req: &DeleteFavoriteReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// FId sets the "f_id" query parameter.
func (b *DeleteFavoriteReqBuilder) FId(v string) *DeleteFavoriteReqBuilder {
	b.req.queryParams["f_id"] = v
	return b
}

// Build finalizes the request.
func (b *DeleteFavoriteReqBuilder) Build() *DeleteFavoriteReq { return b.req }

// DeleteFavoriteResp is the response for DeleteFavorite.
type DeleteFavoriteResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// DeleteFavorite: 删除收藏
func (s *Service) DeleteFavorite(ctx context.Context, req *DeleteFavoriteReq, opts ...core.RequestOption) (*DeleteFavoriteResp, error) {
	resp := &DeleteFavoriteResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "DELETE",
		PathTemplate: "/hduhelp-neo/emptyschedule/favorites",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// GenReq is the request for Gen.
type GenReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// GenReqBuilder builds a GenReq with a fluent setter per field.
type GenReqBuilder struct{ req *GenReq }

// NewGenReqBuilder creates a request builder for Gen.
func NewGenReqBuilder() *GenReqBuilder {
	return &GenReqBuilder{req: &GenReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *GenReqBuilder) Build() *GenReq { return b.req }

// GenResp is the response for Gen.
type GenResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.GenData `json:"data"`
}

// Gen: 口令组队生成结果
func (s *Service) Gen(ctx context.Context, req *GenReq, opts ...core.RequestOption) (*GenResp, error) {
	resp := &GenResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/emptyschedule/gen",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// MyRoomsReq is the request for MyRooms.
type MyRoomsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// MyRoomsReqBuilder builds a MyRoomsReq with a fluent setter per field.
type MyRoomsReqBuilder struct{ req *MyRoomsReq }

// NewMyRoomsReqBuilder creates a request builder for MyRooms.
func NewMyRoomsReqBuilder() *MyRoomsReqBuilder {
	return &MyRoomsReqBuilder{req: &MyRoomsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *MyRoomsReqBuilder) Build() *MyRoomsReq { return b.req }

// MyRoomsResp is the response for MyRooms.
type MyRoomsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.RoomInfo `json:"data"`
}

// MyRooms: 我加入的房间列表
func (s *Service) MyRooms(ctx context.Context, req *MyRoomsReq, opts ...core.RequestOption) (*MyRoomsResp, error) {
	resp := &MyRoomsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/emptyschedule/rooms",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// CreateRoomReq is the request for CreateRoom.
type CreateRoomReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// CreateRoomReqBuilder builds a CreateRoomReq with a fluent setter per field.
type CreateRoomReqBuilder struct{ req *CreateRoomReq }

// NewCreateRoomReqBuilder creates a request builder for CreateRoom.
func NewCreateRoomReqBuilder() *CreateRoomReqBuilder {
	return &CreateRoomReqBuilder{req: &CreateRoomReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *CreateRoomReqBuilder) Body(body *models.CreateRoomRequestBody) *CreateRoomReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *CreateRoomReqBuilder) Build() *CreateRoomReq { return b.req }

// CreateRoomResp is the response for CreateRoom.
type CreateRoomResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.RoomInfo `json:"data"`
}

// CreateRoom: 创建空课表房间
func (s *Service) CreateRoom(ctx context.Context, req *CreateRoomReq, opts ...core.RequestOption) (*CreateRoomResp, error) {
	resp := &CreateRoomResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/emptyschedule/rooms",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// DeleteRoomReq is the request for DeleteRoom.
type DeleteRoomReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// DeleteRoomReqBuilder builds a DeleteRoomReq with a fluent setter per field.
type DeleteRoomReqBuilder struct{ req *DeleteRoomReq }

// NewDeleteRoomReqBuilder creates a request builder for DeleteRoom.
func NewDeleteRoomReqBuilder() *DeleteRoomReqBuilder {
	return &DeleteRoomReqBuilder{req: &DeleteRoomReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// RoomId sets the "room_id" query parameter.
func (b *DeleteRoomReqBuilder) RoomId(v string) *DeleteRoomReqBuilder {
	b.req.queryParams["room_id"] = v
	return b
}

// Build finalizes the request.
func (b *DeleteRoomReqBuilder) Build() *DeleteRoomReq { return b.req }

// DeleteRoomResp is the response for DeleteRoom.
type DeleteRoomResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// DeleteRoom: 删除房间
func (s *Service) DeleteRoom(ctx context.Context, req *DeleteRoomReq, opts ...core.RequestOption) (*DeleteRoomResp, error) {
	resp := &DeleteRoomResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "DELETE",
		PathTemplate: "/hduhelp-neo/emptyschedule/rooms",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// RoomDetailReq is the request for RoomDetail.
type RoomDetailReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// RoomDetailReqBuilder builds a RoomDetailReq with a fluent setter per field.
type RoomDetailReqBuilder struct{ req *RoomDetailReq }

// NewRoomDetailReqBuilder creates a request builder for RoomDetail.
func NewRoomDetailReqBuilder() *RoomDetailReqBuilder {
	return &RoomDetailReqBuilder{req: &RoomDetailReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// RoomId sets the "room_id" query parameter.
func (b *RoomDetailReqBuilder) RoomId(v string) *RoomDetailReqBuilder {
	b.req.queryParams["room_id"] = v
	return b
}

// Build finalizes the request.
func (b *RoomDetailReqBuilder) Build() *RoomDetailReq { return b.req }

// RoomDetailResp is the response for RoomDetail.
type RoomDetailResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.RoomDetailData `json:"data"`
}

// RoomDetail: 房间详情
func (s *Service) RoomDetail(ctx context.Context, req *RoomDetailReq, opts ...core.RequestOption) (*RoomDetailResp, error) {
	resp := &RoomDetailResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/emptyschedule/rooms/detail",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// GenerateReq is the request for Generate.
type GenerateReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// GenerateReqBuilder builds a GenerateReq with a fluent setter per field.
type GenerateReqBuilder struct{ req *GenerateReq }

// NewGenerateReqBuilder creates a request builder for Generate.
func NewGenerateReqBuilder() *GenerateReqBuilder {
	return &GenerateReqBuilder{req: &GenerateReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *GenerateReqBuilder) Body(body *models.GenerateRequestBody) *GenerateReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *GenerateReqBuilder) Build() *GenerateReq { return b.req }

// GenerateResp is the response for Generate.
type GenerateResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.GenerateData `json:"data"`
}

// Generate: 计算房间共同空闲并存档
func (s *Service) Generate(ctx context.Context, req *GenerateReq, opts ...core.RequestOption) (*GenerateResp, error) {
	resp := &GenerateResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/emptyschedule/rooms/generate",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// InviteReq is the request for Invite.
type InviteReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// InviteReqBuilder builds a InviteReq with a fluent setter per field.
type InviteReqBuilder struct{ req *InviteReq }

// NewInviteReqBuilder creates a request builder for Invite.
func NewInviteReqBuilder() *InviteReqBuilder {
	return &InviteReqBuilder{req: &InviteReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *InviteReqBuilder) Body(body *models.InviteRequestBody) *InviteReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *InviteReqBuilder) Build() *InviteReq { return b.req }

// InviteResp is the response for Invite.
type InviteResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.InviteData `json:"data"`
}

// Invite: 生成房间邀请码
func (s *Service) Invite(ctx context.Context, req *InviteReq, opts ...core.RequestOption) (*InviteResp, error) {
	resp := &InviteResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/emptyschedule/rooms/invite",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// JoinReq is the request for Join.
type JoinReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// JoinReqBuilder builds a JoinReq with a fluent setter per field.
type JoinReqBuilder struct{ req *JoinReq }

// NewJoinReqBuilder creates a request builder for Join.
func NewJoinReqBuilder() *JoinReqBuilder {
	return &JoinReqBuilder{req: &JoinReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *JoinReqBuilder) Body(body *models.JoinRequestBody) *JoinReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *JoinReqBuilder) Build() *JoinReq { return b.req }

// JoinResp is the response for Join.
type JoinResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.RoomInfo `json:"data"`
}

// Join: 通过邀请码加入房间
func (s *Service) Join(ctx context.Context, req *JoinReq, opts ...core.RequestOption) (*JoinResp, error) {
	resp := &JoinResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/emptyschedule/rooms/join",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// LeaveRoomReq is the request for LeaveRoom.
type LeaveRoomReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// LeaveRoomReqBuilder builds a LeaveRoomReq with a fluent setter per field.
type LeaveRoomReqBuilder struct{ req *LeaveRoomReq }

// NewLeaveRoomReqBuilder creates a request builder for LeaveRoom.
func NewLeaveRoomReqBuilder() *LeaveRoomReqBuilder {
	return &LeaveRoomReqBuilder{req: &LeaveRoomReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *LeaveRoomReqBuilder) Body(body *models.LeaveRoomRequestBody) *LeaveRoomReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *LeaveRoomReqBuilder) Build() *LeaveRoomReq { return b.req }

// LeaveRoomResp is the response for LeaveRoom.
type LeaveRoomResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// LeaveRoom: 离开房间
func (s *Service) LeaveRoom(ctx context.Context, req *LeaveRoomReq, opts ...core.RequestOption) (*LeaveRoomResp, error) {
	resp := &LeaveRoomResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/emptyschedule/rooms/leave",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// LookUpShareReq is the request for LookUpShare.
type LookUpShareReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// LookUpShareReqBuilder builds a LookUpShareReq with a fluent setter per field.
type LookUpShareReqBuilder struct{ req *LookUpShareReq }

// NewLookUpShareReqBuilder creates a request builder for LookUpShare.
func NewLookUpShareReqBuilder() *LookUpShareReqBuilder {
	return &LookUpShareReqBuilder{req: &LookUpShareReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Code sets the "code" query parameter.
func (b *LookUpShareReqBuilder) Code(v string) *LookUpShareReqBuilder {
	b.req.queryParams["code"] = v
	return b
}

// Build finalizes the request.
func (b *LookUpShareReqBuilder) Build() *LookUpShareReq { return b.req }

// LookUpShareResp is the response for LookUpShare.
type LookUpShareResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.LookUpShareData `json:"data"`
}

// LookUpShare: 通过分享码查看排班结果
func (s *Service) LookUpShare(ctx context.Context, req *LookUpShareReq, opts ...core.RequestOption) (*LookUpShareResp, error) {
	resp := &LookUpShareResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/emptyschedule/share",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// StatusReq is the request for Status.
type StatusReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// StatusReqBuilder builds a StatusReq with a fluent setter per field.
type StatusReqBuilder struct{ req *StatusReq }

// NewStatusReqBuilder creates a request builder for Status.
func NewStatusReqBuilder() *StatusReqBuilder {
	return &StatusReqBuilder{req: &StatusReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *StatusReqBuilder) Build() *StatusReq { return b.req }

// StatusResp is the response for Status.
type StatusResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.StatusData `json:"data"`
}

// Status: 口令组队状态查询
func (s *Service) Status(ctx context.Context, req *StatusReq, opts ...core.RequestOption) (*StatusResp, error) {
	resp := &StatusResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/emptyschedule/status",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}
