// Code generated by hduhelp-sdk-gen; DO NOT EDIT.

package campuslife

import (
	"context"
	"strconv"
	"strings"

	"github.com/hduhelp/hduhelp-neo-sdk-go/core"
	"github.com/hduhelp/hduhelp-neo-sdk-go/models"
)

// Service groups the CampusLife endpoints.
type Service struct{ config *core.Config }

// NewService binds the CampusLife service to a client config.
func NewService(config *core.Config) *Service { return &Service{config: config} }

// ListActivitiesReq is the request for ListActivities.
type ListActivitiesReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListActivitiesReqBuilder builds a ListActivitiesReq with a fluent setter per field.
type ListActivitiesReqBuilder struct{ req *ListActivitiesReq }

// NewListActivitiesReqBuilder creates a request builder for ListActivities.
func NewListActivitiesReqBuilder() *ListActivitiesReqBuilder {
	return &ListActivitiesReqBuilder{req: &ListActivitiesReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Status sets the "status" query parameter.
func (b *ListActivitiesReqBuilder) Status(v int32) *ListActivitiesReqBuilder {
	b.req.queryParams["status"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Content sets the "content" query parameter.
func (b *ListActivitiesReqBuilder) Content(v []string) *ListActivitiesReqBuilder {
	b.req.queryParams["content"] = strings.Join(v, ",")
	return b
}

// HostName sets the "hostName" query parameter.
func (b *ListActivitiesReqBuilder) HostName(v string) *ListActivitiesReqBuilder {
	b.req.queryParams["hostName"] = v
	return b
}

// Page sets the "page" query parameter.
func (b *ListActivitiesReqBuilder) Page(v int32) *ListActivitiesReqBuilder {
	b.req.queryParams["page"] = strconv.FormatInt(int64(v), 10)
	return b
}

// PageSize sets the "pageSize" query parameter.
func (b *ListActivitiesReqBuilder) PageSize(v int32) *ListActivitiesReqBuilder {
	b.req.queryParams["pageSize"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Build finalizes the request.
func (b *ListActivitiesReqBuilder) Build() *ListActivitiesReq { return b.req }

// ListActivitiesResp is the response for ListActivities.
type ListActivitiesResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.ActivityPage `json:"data"`
}

// ListActivities: 查询校园活动
func (s *Service) ListActivities(ctx context.Context, req *ListActivitiesReq, opts ...core.RequestOption) (*ListActivitiesResp, error) {
	resp := &ListActivitiesResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/activities",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListActivityNoticesReq is the request for ListActivityNotices.
type ListActivityNoticesReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListActivityNoticesReqBuilder builds a ListActivityNoticesReq with a fluent setter per field.
type ListActivityNoticesReqBuilder struct{ req *ListActivityNoticesReq }

// NewListActivityNoticesReqBuilder creates a request builder for ListActivityNotices.
func NewListActivityNoticesReqBuilder() *ListActivityNoticesReqBuilder {
	return &ListActivityNoticesReqBuilder{req: &ListActivityNoticesReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *ListActivityNoticesReqBuilder) Build() *ListActivityNoticesReq { return b.req }

// ListActivityNoticesResp is the response for ListActivityNotices.
type ListActivityNoticesResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.News `json:"data"`
}

// ListActivityNotices: 查询校园活动通知
func (s *Service) ListActivityNotices(ctx context.Context, req *ListActivityNoticesReq, opts ...core.RequestOption) (*ListActivityNoticesResp, error) {
	resp := &ListActivityNoticesResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/activities/notices",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListActivityOrganizersReq is the request for ListActivityOrganizers.
type ListActivityOrganizersReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListActivityOrganizersReqBuilder builds a ListActivityOrganizersReq with a fluent setter per field.
type ListActivityOrganizersReqBuilder struct{ req *ListActivityOrganizersReq }

// NewListActivityOrganizersReqBuilder creates a request builder for ListActivityOrganizers.
func NewListActivityOrganizersReqBuilder() *ListActivityOrganizersReqBuilder {
	return &ListActivityOrganizersReqBuilder{req: &ListActivityOrganizersReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *ListActivityOrganizersReqBuilder) Build() *ListActivityOrganizersReq { return b.req }

// ListActivityOrganizersResp is the response for ListActivityOrganizers.
type ListActivityOrganizersResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.Sponsor `json:"data"`
}

// ListActivityOrganizers: 查询校园活动主办方目录
func (s *Service) ListActivityOrganizers(ctx context.Context, req *ListActivityOrganizersReq, opts ...core.RequestOption) (*ListActivityOrganizersResp, error) {
	resp := &ListActivityOrganizersResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/activities/organizers",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListPopularActivitiesReq is the request for ListPopularActivities.
type ListPopularActivitiesReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListPopularActivitiesReqBuilder builds a ListPopularActivitiesReq with a fluent setter per field.
type ListPopularActivitiesReqBuilder struct{ req *ListPopularActivitiesReq }

// NewListPopularActivitiesReqBuilder creates a request builder for ListPopularActivities.
func NewListPopularActivitiesReqBuilder() *ListPopularActivitiesReqBuilder {
	return &ListPopularActivitiesReqBuilder{req: &ListPopularActivitiesReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *ListPopularActivitiesReqBuilder) Build() *ListPopularActivitiesReq { return b.req }

// ListPopularActivitiesResp is the response for ListPopularActivities.
type ListPopularActivitiesResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.Activity `json:"data"`
}

// ListPopularActivities: 查询热门校园活动
func (s *Service) ListPopularActivities(ctx context.Context, req *ListPopularActivitiesReq, opts ...core.RequestOption) (*ListPopularActivitiesResp, error) {
	resp := &ListPopularActivitiesResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/activities/popular",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListActivityRankingsReq is the request for ListActivityRankings.
type ListActivityRankingsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListActivityRankingsReqBuilder builds a ListActivityRankingsReq with a fluent setter per field.
type ListActivityRankingsReqBuilder struct{ req *ListActivityRankingsReq }

// NewListActivityRankingsReqBuilder creates a request builder for ListActivityRankings.
func NewListActivityRankingsReqBuilder() *ListActivityRankingsReqBuilder {
	return &ListActivityRankingsReqBuilder{req: &ListActivityRankingsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *ListActivityRankingsReqBuilder) Build() *ListActivityRankingsReq { return b.req }

// ListActivityRankingsResp is the response for ListActivityRankings.
type ListActivityRankingsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.Ranking `json:"data"`
}

// ListActivityRankings: 查询校园活动排行榜
func (s *Service) ListActivityRankings(ctx context.Context, req *ListActivityRankingsReq, opts ...core.RequestOption) (*ListActivityRankingsResp, error) {
	resp := &ListActivityRankingsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/activities/rankings",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// GetActivityReq is the request for GetActivity.
type GetActivityReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// GetActivityReqBuilder builds a GetActivityReq with a fluent setter per field.
type GetActivityReqBuilder struct{ req *GetActivityReq }

// NewGetActivityReqBuilder creates a request builder for GetActivity.
func NewGetActivityReqBuilder() *GetActivityReqBuilder {
	return &GetActivityReqBuilder{req: &GetActivityReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// ActivityId sets the "activityId" path parameter.
func (b *GetActivityReqBuilder) ActivityId(v string) *GetActivityReqBuilder {
	b.req.pathParams["activityId"] = v
	return b
}

// Build finalizes the request.
func (b *GetActivityReqBuilder) Build() *GetActivityReq { return b.req }

// GetActivityResp is the response for GetActivity.
type GetActivityResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.ActivityDetail `json:"data"`
}

// GetActivity: 查询校园活动详情
func (s *Service) GetActivity(ctx context.Context, req *GetActivityReq, opts ...core.RequestOption) (*GetActivityResp, error) {
	resp := &GetActivityResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/activities/{activityId}",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// GetActivityApplicationRequirementsReq is the request for GetActivityApplicationRequirements.
type GetActivityApplicationRequirementsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// GetActivityApplicationRequirementsReqBuilder builds a GetActivityApplicationRequirementsReq with a fluent setter per field.
type GetActivityApplicationRequirementsReqBuilder struct {
	req *GetActivityApplicationRequirementsReq
}

// NewGetActivityApplicationRequirementsReqBuilder creates a request builder for GetActivityApplicationRequirements.
func NewGetActivityApplicationRequirementsReqBuilder() *GetActivityApplicationRequirementsReqBuilder {
	return &GetActivityApplicationRequirementsReqBuilder{req: &GetActivityApplicationRequirementsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// ActivityId sets the "activityId" path parameter.
func (b *GetActivityApplicationRequirementsReqBuilder) ActivityId(v string) *GetActivityApplicationRequirementsReqBuilder {
	b.req.pathParams["activityId"] = v
	return b
}

// Build finalizes the request.
func (b *GetActivityApplicationRequirementsReqBuilder) Build() *GetActivityApplicationRequirementsReq {
	return b.req
}

// GetActivityApplicationRequirementsResp is the response for GetActivityApplicationRequirements.
type GetActivityApplicationRequirementsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.AuditData `json:"data"`
}

// GetActivityApplicationRequirements: 查询校园活动报名要求
func (s *Service) GetActivityApplicationRequirements(ctx context.Context, req *GetActivityApplicationRequirementsReq, opts ...core.RequestOption) (*GetActivityApplicationRequirementsResp, error) {
	resp := &GetActivityApplicationRequirementsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/activities/{activityId}/application-requirements",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListPublicCampusesReq is the request for ListPublicCampuses.
type ListPublicCampusesReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListPublicCampusesReqBuilder builds a ListPublicCampusesReq with a fluent setter per field.
type ListPublicCampusesReqBuilder struct{ req *ListPublicCampusesReq }

// NewListPublicCampusesReqBuilder creates a request builder for ListPublicCampuses.
func NewListPublicCampusesReqBuilder() *ListPublicCampusesReqBuilder {
	return &ListPublicCampusesReqBuilder{req: &ListPublicCampusesReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *ListPublicCampusesReqBuilder) Build() *ListPublicCampusesReq { return b.req }

// ListPublicCampusesResp is the response for ListPublicCampuses.
type ListPublicCampusesResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.PublicCampusItem `json:"data"`
}

// ListPublicCampuses: 校区列表(公开：id/名称/坐标)
func (s *Service) ListPublicCampuses(ctx context.Context, req *ListPublicCampusesReq, opts ...core.RequestOption) (*ListPublicCampusesResp, error) {
	resp := &ListPublicCampusesResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/campuses",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// CardBalanceReq is the request for CardBalance.
type CardBalanceReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// CardBalanceReqBuilder builds a CardBalanceReq with a fluent setter per field.
type CardBalanceReqBuilder struct{ req *CardBalanceReq }

// NewCardBalanceReqBuilder creates a request builder for CardBalance.
func NewCardBalanceReqBuilder() *CardBalanceReqBuilder {
	return &CardBalanceReqBuilder{req: &CardBalanceReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// StaffID sets the "X-Staff-Id" header parameter.
func (b *CardBalanceReqBuilder) StaffID(v string) *CardBalanceReqBuilder {
	b.req.headers["X-Staff-Id"] = v
	return b
}

// Build finalizes the request.
func (b *CardBalanceReqBuilder) Build() *CardBalanceReq { return b.req }

// CardBalanceResp is the response for CardBalance.
type CardBalanceResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.CardBalanceData `json:"data"`
}

// CardBalance: 查询校园卡余额
func (s *Service) CardBalance(ctx context.Context, req *CardBalanceReq, opts ...core.RequestOption) (*CardBalanceResp, error) {
	resp := &CardBalanceResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/card/balance",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// CardConsumeReq is the request for CardConsume.
type CardConsumeReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// CardConsumeReqBuilder builds a CardConsumeReq with a fluent setter per field.
type CardConsumeReqBuilder struct{ req *CardConsumeReq }

// NewCardConsumeReqBuilder creates a request builder for CardConsume.
func NewCardConsumeReqBuilder() *CardConsumeReqBuilder {
	return &CardConsumeReqBuilder{req: &CardConsumeReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// StaffID sets the "X-Staff-Id" header parameter.
func (b *CardConsumeReqBuilder) StaffID(v string) *CardConsumeReqBuilder {
	b.req.headers["X-Staff-Id"] = v
	return b
}

// Build finalizes the request.
func (b *CardConsumeReqBuilder) Build() *CardConsumeReq { return b.req }

// CardConsumeResp is the response for CardConsume.
type CardConsumeResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.CardConsumeData `json:"data"`
}

// CardConsume: 查询校园卡消费流水
func (s *Service) CardConsume(ctx context.Context, req *CardConsumeReq, opts ...core.RequestOption) (*CardConsumeResp, error) {
	resp := &CardConsumeResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/card/consume",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// CardInfoReq is the request for CardInfo.
type CardInfoReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// CardInfoReqBuilder builds a CardInfoReq with a fluent setter per field.
type CardInfoReqBuilder struct{ req *CardInfoReq }

// NewCardInfoReqBuilder creates a request builder for CardInfo.
func NewCardInfoReqBuilder() *CardInfoReqBuilder {
	return &CardInfoReqBuilder{req: &CardInfoReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// StaffID sets the "X-Staff-Id" header parameter.
func (b *CardInfoReqBuilder) StaffID(v string) *CardInfoReqBuilder {
	b.req.headers["X-Staff-Id"] = v
	return b
}

// Build finalizes the request.
func (b *CardInfoReqBuilder) Build() *CardInfoReq { return b.req }

// CardInfoResp is the response for CardInfo.
type CardInfoResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.CardInfoData `json:"data"`
}

// CardInfo: 查询校园卡信息
func (s *Service) CardInfo(ctx context.Context, req *CardInfoReq, opts ...core.RequestOption) (*CardInfoResp, error) {
	resp := &CardInfoResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/card/info",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListCareerRecruitmentReq is the request for ListCareerRecruitment.
type ListCareerRecruitmentReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListCareerRecruitmentReqBuilder builds a ListCareerRecruitmentReq with a fluent setter per field.
type ListCareerRecruitmentReqBuilder struct{ req *ListCareerRecruitmentReq }

// NewListCareerRecruitmentReqBuilder creates a request builder for ListCareerRecruitment.
func NewListCareerRecruitmentReqBuilder() *ListCareerRecruitmentReqBuilder {
	return &ListCareerRecruitmentReqBuilder{req: &ListCareerRecruitmentReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Section sets the "section" query parameter.
func (b *ListCareerRecruitmentReqBuilder) Section(v string) *ListCareerRecruitmentReqBuilder {
	b.req.queryParams["section"] = v
	return b
}

// Page sets the "page" query parameter.
func (b *ListCareerRecruitmentReqBuilder) Page(v int32) *ListCareerRecruitmentReqBuilder {
	b.req.queryParams["page"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Build finalizes the request.
func (b *ListCareerRecruitmentReqBuilder) Build() *ListCareerRecruitmentReq { return b.req }

// ListCareerRecruitmentResp is the response for ListCareerRecruitment.
type ListCareerRecruitmentResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.RecruitmentPage `json:"data"`
}

// ListCareerRecruitment: 查询最近三个月就业信息
func (s *Service) ListCareerRecruitment(ctx context.Context, req *ListCareerRecruitmentReq, opts ...core.RequestOption) (*ListCareerRecruitmentResp, error) {
	resp := &ListCareerRecruitmentResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/career-guide/recruitment",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ElectricBalanceReq is the request for ElectricBalance.
type ElectricBalanceReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ElectricBalanceReqBuilder builds a ElectricBalanceReq with a fluent setter per field.
type ElectricBalanceReqBuilder struct{ req *ElectricBalanceReq }

// NewElectricBalanceReqBuilder creates a request builder for ElectricBalance.
func NewElectricBalanceReqBuilder() *ElectricBalanceReqBuilder {
	return &ElectricBalanceReqBuilder{req: &ElectricBalanceReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *ElectricBalanceReqBuilder) Build() *ElectricBalanceReq { return b.req }

// ElectricBalanceResp is the response for ElectricBalance.
type ElectricBalanceResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.ElectricBalanceData `json:"data"`
}

// ElectricBalance: 查询宿舍电费余额(绑定电表)
func (s *Service) ElectricBalance(ctx context.Context, req *ElectricBalanceReq, opts ...core.RequestOption) (*ElectricBalanceResp, error) {
	resp := &ElectricBalanceResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/electric/balance",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ElectricBindingReq is the request for ElectricBinding.
type ElectricBindingReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ElectricBindingReqBuilder builds a ElectricBindingReq with a fluent setter per field.
type ElectricBindingReqBuilder struct{ req *ElectricBindingReq }

// NewElectricBindingReqBuilder creates a request builder for ElectricBinding.
func NewElectricBindingReqBuilder() *ElectricBindingReqBuilder {
	return &ElectricBindingReqBuilder{req: &ElectricBindingReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *ElectricBindingReqBuilder) Build() *ElectricBindingReq { return b.req }

// ElectricBindingResp is the response for ElectricBinding.
type ElectricBindingResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.ElectricBindingData `json:"data"`
}

// ElectricBinding: 查询当前电表绑定信息
func (s *Service) ElectricBinding(ctx context.Context, req *ElectricBindingReq, opts ...core.RequestOption) (*ElectricBindingResp, error) {
	resp := &ElectricBindingResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/electric/binding",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// BindRoomReq is the request for BindRoom.
type BindRoomReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// BindRoomReqBuilder builds a BindRoomReq with a fluent setter per field.
type BindRoomReqBuilder struct{ req *BindRoomReq }

// NewBindRoomReqBuilder creates a request builder for BindRoom.
func NewBindRoomReqBuilder() *BindRoomReqBuilder {
	return &BindRoomReqBuilder{req: &BindRoomReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *BindRoomReqBuilder) Body(body *models.BindRoomRequestBody) *BindRoomReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *BindRoomReqBuilder) Build() *BindRoomReq { return b.req }

// BindRoomResp is the response for BindRoom.
type BindRoomResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.ElectricBindingData `json:"data"`
}

// BindRoom: 按真实寝室绑定宿舍电表
func (s *Service) BindRoom(ctx context.Context, req *BindRoomReq, opts ...core.RequestOption) (*BindRoomResp, error) {
	resp := &BindRoomResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/campuslife/electric/binding",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// UnbindMeterReq is the request for UnbindMeter.
type UnbindMeterReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// UnbindMeterReqBuilder builds a UnbindMeterReq with a fluent setter per field.
type UnbindMeterReqBuilder struct{ req *UnbindMeterReq }

// NewUnbindMeterReqBuilder creates a request builder for UnbindMeter.
func NewUnbindMeterReqBuilder() *UnbindMeterReqBuilder {
	return &UnbindMeterReqBuilder{req: &UnbindMeterReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *UnbindMeterReqBuilder) Build() *UnbindMeterReq { return b.req }

// UnbindMeterResp is the response for UnbindMeter.
type UnbindMeterResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// UnbindMeter: 解绑当前宿舍电表
func (s *Service) UnbindMeter(ctx context.Context, req *UnbindMeterReq, opts ...core.RequestOption) (*UnbindMeterResp, error) {
	resp := &UnbindMeterResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "DELETE",
		PathTemplate: "/hduhelp-neo/campuslife/electric/binding",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListBuildingsReq is the request for ListBuildings.
type ListBuildingsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListBuildingsReqBuilder builds a ListBuildingsReq with a fluent setter per field.
type ListBuildingsReqBuilder struct{ req *ListBuildingsReq }

// NewListBuildingsReqBuilder creates a request builder for ListBuildings.
func NewListBuildingsReqBuilder() *ListBuildingsReqBuilder {
	return &ListBuildingsReqBuilder{req: &ListBuildingsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *ListBuildingsReqBuilder) Build() *ListBuildingsReq { return b.req }

// ListBuildingsResp is the response for ListBuildings.
type ListBuildingsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.ElectricBuildingItem `json:"data"`
}

// ListBuildings: 查询真实楼栋列表
func (s *Service) ListBuildings(ctx context.Context, req *ListBuildingsReq, opts ...core.RequestOption) (*ListBuildingsResp, error) {
	resp := &ListBuildingsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/electric/buildings",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListFloorsReq is the request for ListFloors.
type ListFloorsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListFloorsReqBuilder builds a ListFloorsReq with a fluent setter per field.
type ListFloorsReqBuilder struct{ req *ListFloorsReq }

// NewListFloorsReqBuilder creates a request builder for ListFloors.
func NewListFloorsReqBuilder() *ListFloorsReqBuilder {
	return &ListFloorsReqBuilder{req: &ListFloorsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// BuildingId sets the "building_id" query parameter.
func (b *ListFloorsReqBuilder) BuildingId(v int64) *ListFloorsReqBuilder {
	b.req.queryParams["building_id"] = strconv.FormatInt(v, 10)
	return b
}

// Build finalizes the request.
func (b *ListFloorsReqBuilder) Build() *ListFloorsReq { return b.req }

// ListFloorsResp is the response for ListFloors.
type ListFloorsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.ElectricFloorItem `json:"data"`
}

// ListFloors: 按楼栋查询真实楼层列表
func (s *Service) ListFloors(ctx context.Context, req *ListFloorsReq, opts ...core.RequestOption) (*ListFloorsResp, error) {
	resp := &ListFloorsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/electric/floors",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ElectricHistoryReq is the request for ElectricHistory.
type ElectricHistoryReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ElectricHistoryReqBuilder builds a ElectricHistoryReq with a fluent setter per field.
type ElectricHistoryReqBuilder struct{ req *ElectricHistoryReq }

// NewElectricHistoryReqBuilder creates a request builder for ElectricHistory.
func NewElectricHistoryReqBuilder() *ElectricHistoryReqBuilder {
	return &ElectricHistoryReqBuilder{req: &ElectricHistoryReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *ElectricHistoryReqBuilder) Build() *ElectricHistoryReq { return b.req }

// ElectricHistoryResp is the response for ElectricHistory.
type ElectricHistoryResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.ElectricHistoryData `json:"data"`
}

// ElectricHistory: 查询近14天电费历史
func (s *Service) ElectricHistory(ctx context.Context, req *ElectricHistoryReq, opts ...core.RequestOption) (*ElectricHistoryResp, error) {
	resp := &ElectricHistoryResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/electric/history",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListRoomsReq is the request for ListRooms.
type ListRoomsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListRoomsReqBuilder builds a ListRoomsReq with a fluent setter per field.
type ListRoomsReqBuilder struct{ req *ListRoomsReq }

// NewListRoomsReqBuilder creates a request builder for ListRooms.
func NewListRoomsReqBuilder() *ListRoomsReqBuilder {
	return &ListRoomsReqBuilder{req: &ListRoomsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// FloorId sets the "floor_id" query parameter.
func (b *ListRoomsReqBuilder) FloorId(v int64) *ListRoomsReqBuilder {
	b.req.queryParams["floor_id"] = strconv.FormatInt(v, 10)
	return b
}

// Build finalizes the request.
func (b *ListRoomsReqBuilder) Build() *ListRoomsReq { return b.req }

// ListRoomsResp is the response for ListRooms.
type ListRoomsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.ElectricRoomItem `json:"data"`
}

// ListRooms: 按楼层查询真实寝室与电表列表
func (s *Service) ListRooms(ctx context.Context, req *ListRoomsReq, opts ...core.RequestOption) (*ListRoomsResp, error) {
	resp := &ListRoomsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/electric/rooms",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListLostFoundCategoriesReq is the request for ListLostFoundCategories.
type ListLostFoundCategoriesReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListLostFoundCategoriesReqBuilder builds a ListLostFoundCategoriesReq with a fluent setter per field.
type ListLostFoundCategoriesReqBuilder struct{ req *ListLostFoundCategoriesReq }

// NewListLostFoundCategoriesReqBuilder creates a request builder for ListLostFoundCategories.
func NewListLostFoundCategoriesReqBuilder() *ListLostFoundCategoriesReqBuilder {
	return &ListLostFoundCategoriesReqBuilder{req: &ListLostFoundCategoriesReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// StaffID sets the "X-Staff-Id" header parameter.
func (b *ListLostFoundCategoriesReqBuilder) StaffID(v string) *ListLostFoundCategoriesReqBuilder {
	b.req.headers["X-Staff-Id"] = v
	return b
}

// Build finalizes the request.
func (b *ListLostFoundCategoriesReqBuilder) Build() *ListLostFoundCategoriesReq { return b.req }

// ListLostFoundCategoriesResp is the response for ListLostFoundCategories.
type ListLostFoundCategoriesResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.Category `json:"data"`
}

// ListLostFoundCategories: 失物类型目录
func (s *Service) ListLostFoundCategories(ctx context.Context, req *ListLostFoundCategoriesReq, opts ...core.RequestOption) (*ListLostFoundCategoriesResp, error) {
	resp := &ListLostFoundCategoriesResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/lost-found/categories",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// SearchLostItemsReq is the request for SearchLostItems.
type SearchLostItemsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// SearchLostItemsReqBuilder builds a SearchLostItemsReq with a fluent setter per field.
type SearchLostItemsReqBuilder struct{ req *SearchLostItemsReq }

// NewSearchLostItemsReqBuilder creates a request builder for SearchLostItems.
func NewSearchLostItemsReqBuilder() *SearchLostItemsReqBuilder {
	return &SearchLostItemsReqBuilder{req: &SearchLostItemsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Page sets the "page" query parameter.
func (b *SearchLostItemsReqBuilder) Page(v int32) *SearchLostItemsReqBuilder {
	b.req.queryParams["page"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Keyword sets the "keyword" query parameter.
func (b *SearchLostItemsReqBuilder) Keyword(v string) *SearchLostItemsReqBuilder {
	b.req.queryParams["keyword"] = v
	return b
}

// Category sets the "category" query parameter.
func (b *SearchLostItemsReqBuilder) Category(v string) *SearchLostItemsReqBuilder {
	b.req.queryParams["category"] = v
	return b
}

// Scene sets the "scene" query parameter.
func (b *SearchLostItemsReqBuilder) Scene(v string) *SearchLostItemsReqBuilder {
	b.req.queryParams["scene"] = v
	return b
}

// StaffID sets the "X-Staff-Id" header parameter.
func (b *SearchLostItemsReqBuilder) StaffID(v string) *SearchLostItemsReqBuilder {
	b.req.headers["X-Staff-Id"] = v
	return b
}

// Build finalizes the request.
func (b *SearchLostItemsReqBuilder) Build() *SearchLostItemsReq { return b.req }

// SearchLostItemsResp is the response for SearchLostItems.
type SearchLostItemsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.SearchPage `json:"data"`
}

// SearchLostItems: 查询校园失物
func (s *Service) SearchLostItems(ctx context.Context, req *SearchLostItemsReq, opts ...core.RequestOption) (*SearchLostItemsResp, error) {
	resp := &SearchLostItemsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/lost-found/items",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListLostFoundScenesReq is the request for ListLostFoundScenes.
type ListLostFoundScenesReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListLostFoundScenesReqBuilder builds a ListLostFoundScenesReq with a fluent setter per field.
type ListLostFoundScenesReqBuilder struct{ req *ListLostFoundScenesReq }

// NewListLostFoundScenesReqBuilder creates a request builder for ListLostFoundScenes.
func NewListLostFoundScenesReqBuilder() *ListLostFoundScenesReqBuilder {
	return &ListLostFoundScenesReqBuilder{req: &ListLostFoundScenesReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// StaffID sets the "X-Staff-Id" header parameter.
func (b *ListLostFoundScenesReqBuilder) StaffID(v string) *ListLostFoundScenesReqBuilder {
	b.req.headers["X-Staff-Id"] = v
	return b
}

// Build finalizes the request.
func (b *ListLostFoundScenesReqBuilder) Build() *ListLostFoundScenesReq { return b.req }

// ListLostFoundScenesResp is the response for ListLostFoundScenes.
type ListLostFoundScenesResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.Scene `json:"data"`
}

// ListLostFoundScenes: 失物场所目录
func (s *Service) ListLostFoundScenes(ctx context.Context, req *ListLostFoundScenesReq, opts ...core.RequestOption) (*ListLostFoundScenesResp, error) {
	resp := &ListLostFoundScenesResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/lost-found/scenes",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// GetVenueAvailabilityReq is the request for GetVenueAvailability.
type GetVenueAvailabilityReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// GetVenueAvailabilityReqBuilder builds a GetVenueAvailabilityReq with a fluent setter per field.
type GetVenueAvailabilityReqBuilder struct{ req *GetVenueAvailabilityReq }

// NewGetVenueAvailabilityReqBuilder creates a request builder for GetVenueAvailability.
func NewGetVenueAvailabilityReqBuilder() *GetVenueAvailabilityReqBuilder {
	return &GetVenueAvailabilityReqBuilder{req: &GetVenueAvailabilityReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Venue sets the "venue" query parameter: 必填。要查询的球馆，可输入羽毛球、羽毛球馆、综合馆羽毛球、网球、网球馆或穹顶网球场；当前官网个人预约只开放羽毛球和网球。
func (b *GetVenueAvailabilityReqBuilder) Venue(v string) *GetVenueAvailabilityReqBuilder {
	b.req.queryParams["venue"] = v
	return b
}

// Date sets the "date" query parameter: 必填。用户从 campuslife venues bookable-dates 返回的 dates 中选择的日期，格式为 YYYY-MM-DD。
func (b *GetVenueAvailabilityReqBuilder) Date(v string) *GetVenueAvailabilityReqBuilder {
	b.req.queryParams["date"] = v
	return b
}

// Build finalizes the request.
func (b *GetVenueAvailabilityReqBuilder) Build() *GetVenueAvailabilityReq { return b.req }

// GetVenueAvailabilityResp is the response for GetVenueAvailability.
type GetVenueAvailabilityResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.VenueAvailabilityData `json:"data"`
}

// GetVenueAvailability: 查询选定日期的可预约时段
func (s *Service) GetVenueAvailability(ctx context.Context, req *GetVenueAvailabilityReq, opts ...core.RequestOption) (*GetVenueAvailabilityResp, error) {
	resp := &GetVenueAvailabilityResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/venues/availability",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListVenueBookableDatesReq is the request for ListVenueBookableDates.
type ListVenueBookableDatesReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListVenueBookableDatesReqBuilder builds a ListVenueBookableDatesReq with a fluent setter per field.
type ListVenueBookableDatesReqBuilder struct{ req *ListVenueBookableDatesReq }

// NewListVenueBookableDatesReqBuilder creates a request builder for ListVenueBookableDates.
func NewListVenueBookableDatesReqBuilder() *ListVenueBookableDatesReqBuilder {
	return &ListVenueBookableDatesReqBuilder{req: &ListVenueBookableDatesReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Venue sets the "venue" query parameter: 必填。用户想预约的场馆或运动项目，可输入羽毛球、网球、乒乓球、篮球、足球、排球、击剑或形体。
func (b *ListVenueBookableDatesReqBuilder) Venue(v string) *ListVenueBookableDatesReqBuilder {
	b.req.queryParams["venue"] = v
	return b
}

// Build finalizes the request.
func (b *ListVenueBookableDatesReqBuilder) Build() *ListVenueBookableDatesReq { return b.req }

// ListVenueBookableDatesResp is the response for ListVenueBookableDates.
type ListVenueBookableDatesResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.VenueDatesData `json:"data"`
}

// ListVenueBookableDates: 查询场馆可预约日期
func (s *Service) ListVenueBookableDates(ctx context.Context, req *ListVenueBookableDatesReq, opts ...core.RequestOption) (*ListVenueBookableDatesResp, error) {
	resp := &ListVenueBookableDatesResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/venues/bookable-dates",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// PredictReq is the request for Predict.
type PredictReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// PredictReqBuilder builds a PredictReq with a fluent setter per field.
type PredictReqBuilder struct{ req *PredictReq }

// NewPredictReqBuilder creates a request builder for Predict.
func NewPredictReqBuilder() *PredictReqBuilder {
	return &PredictReqBuilder{req: &PredictReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Days sets the "days" query parameter.
func (b *PredictReqBuilder) Days(v int32) *PredictReqBuilder {
	b.req.queryParams["days"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Lat sets the "lat" query parameter.
func (b *PredictReqBuilder) Lat(v float64) *PredictReqBuilder {
	b.req.queryParams["lat"] = strconv.FormatFloat(v, 'g', -1, 64)
	return b
}

// Lng sets the "lng" query parameter.
func (b *PredictReqBuilder) Lng(v float64) *PredictReqBuilder {
	b.req.queryParams["lng"] = strconv.FormatFloat(v, 'g', -1, 64)
	return b
}

// Build finalizes the request.
func (b *PredictReqBuilder) Build() *PredictReq { return b.req }

// PredictResp is the response for Predict.
type PredictResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.PredictData `json:"data"`
}

// Predict: 获取天气预报(逐小时/逐天)
func (s *Service) Predict(ctx context.Context, req *PredictReq, opts ...core.RequestOption) (*PredictResp, error) {
	resp := &PredictResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/weather/forecast",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// InfoStreamReq is the request for InfoStream.
type InfoStreamReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// InfoStreamReqBuilder builds a InfoStreamReq with a fluent setter per field.
type InfoStreamReqBuilder struct{ req *InfoStreamReq }

// NewInfoStreamReqBuilder creates a request builder for InfoStream.
func NewInfoStreamReqBuilder() *InfoStreamReqBuilder {
	return &InfoStreamReqBuilder{req: &InfoStreamReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Lat sets the "lat" query parameter.
func (b *InfoStreamReqBuilder) Lat(v float64) *InfoStreamReqBuilder {
	b.req.queryParams["lat"] = strconv.FormatFloat(v, 'g', -1, 64)
	return b
}

// Lng sets the "lng" query parameter.
func (b *InfoStreamReqBuilder) Lng(v float64) *InfoStreamReqBuilder {
	b.req.queryParams["lng"] = strconv.FormatFloat(v, 'g', -1, 64)
	return b
}

// Build finalizes the request.
func (b *InfoStreamReqBuilder) Build() *InfoStreamReq { return b.req }

// InfoStreamResp is the response for InfoStream.
type InfoStreamResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.InfoStreamData `json:"data"`
}

// InfoStream: 获取天气信息流卡片(AQI/温度/停雨)
func (s *Service) InfoStream(ctx context.Context, req *InfoStreamReq, opts ...core.RequestOption) (*InfoStreamResp, error) {
	resp := &InfoStreamResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/weather/info-stream",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// RealTimeReq is the request for RealTime.
type RealTimeReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// RealTimeReqBuilder builds a RealTimeReq with a fluent setter per field.
type RealTimeReqBuilder struct{ req *RealTimeReq }

// NewRealTimeReqBuilder creates a request builder for RealTime.
func NewRealTimeReqBuilder() *RealTimeReqBuilder {
	return &RealTimeReqBuilder{req: &RealTimeReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Lat sets the "lat" query parameter.
func (b *RealTimeReqBuilder) Lat(v float64) *RealTimeReqBuilder {
	b.req.queryParams["lat"] = strconv.FormatFloat(v, 'g', -1, 64)
	return b
}

// Lng sets the "lng" query parameter.
func (b *RealTimeReqBuilder) Lng(v float64) *RealTimeReqBuilder {
	b.req.queryParams["lng"] = strconv.FormatFloat(v, 'g', -1, 64)
	return b
}

// Build finalizes the request.
func (b *RealTimeReqBuilder) Build() *RealTimeReq { return b.req }

// RealTimeResp is the response for RealTime.
type RealTimeResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.RealTimeData `json:"data"`
}

// RealTime: 获取实时天气(按当前校区坐标)
func (s *Service) RealTime(ctx context.Context, req *RealTimeReq, opts ...core.RequestOption) (*RealTimeResp, error) {
	resp := &RealTimeResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/campuslife/weather/real-time",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}
