// Code generated by hduhelp-sdk-gen; DO NOT EDIT.

package volunteer

import (
	"context"
	"strconv"

	"github.com/hduhelp/hduhelp-neo-sdk-go/core"
	"github.com/hduhelp/hduhelp-neo-sdk-go/models"
)

// Service groups the Volunteer endpoints.
type Service struct{ config *core.Config }

// NewService binds the Volunteer service to a client config.
func NewService(config *core.Config) *Service { return &Service{config: config} }

// AdminListVolunteerActivitiesReq is the request for AdminListVolunteerActivities.
type AdminListVolunteerActivitiesReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminListVolunteerActivitiesReqBuilder builds a AdminListVolunteerActivitiesReq with a fluent setter per field.
type AdminListVolunteerActivitiesReqBuilder struct {
	req *AdminListVolunteerActivitiesReq
}

// NewAdminListVolunteerActivitiesReqBuilder creates a request builder for AdminListVolunteerActivities.
func NewAdminListVolunteerActivitiesReqBuilder() *AdminListVolunteerActivitiesReqBuilder {
	return &AdminListVolunteerActivitiesReqBuilder{req: &AdminListVolunteerActivitiesReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Page sets the "page" query parameter.
func (b *AdminListVolunteerActivitiesReqBuilder) Page(v int32) *AdminListVolunteerActivitiesReqBuilder {
	b.req.queryParams["page"] = strconv.FormatInt(int64(v), 10)
	return b
}

// PageSize sets the "page_size" query parameter.
func (b *AdminListVolunteerActivitiesReqBuilder) PageSize(v int32) *AdminListVolunteerActivitiesReqBuilder {
	b.req.queryParams["page_size"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Category sets the "category" query parameter.
func (b *AdminListVolunteerActivitiesReqBuilder) Category(v string) *AdminListVolunteerActivitiesReqBuilder {
	b.req.queryParams["category"] = v
	return b
}

// Organization sets the "organization" query parameter.
func (b *AdminListVolunteerActivitiesReqBuilder) Organization(v string) *AdminListVolunteerActivitiesReqBuilder {
	b.req.queryParams["organization"] = v
	return b
}

// StartAtFrom sets the "start_at_from" query parameter.
func (b *AdminListVolunteerActivitiesReqBuilder) StartAtFrom(v int64) *AdminListVolunteerActivitiesReqBuilder {
	b.req.queryParams["start_at_from"] = strconv.FormatInt(v, 10)
	return b
}

// StartAtTo sets the "start_at_to" query parameter.
func (b *AdminListVolunteerActivitiesReqBuilder) StartAtTo(v int64) *AdminListVolunteerActivitiesReqBuilder {
	b.req.queryParams["start_at_to"] = strconv.FormatInt(v, 10)
	return b
}

// DeadlineAtFrom sets the "deadline_at_from" query parameter.
func (b *AdminListVolunteerActivitiesReqBuilder) DeadlineAtFrom(v int64) *AdminListVolunteerActivitiesReqBuilder {
	b.req.queryParams["deadline_at_from"] = strconv.FormatInt(v, 10)
	return b
}

// DeadlineAtTo sets the "deadline_at_to" query parameter.
func (b *AdminListVolunteerActivitiesReqBuilder) DeadlineAtTo(v int64) *AdminListVolunteerActivitiesReqBuilder {
	b.req.queryParams["deadline_at_to"] = strconv.FormatInt(v, 10)
	return b
}

// IsUrgent sets the "is_urgent" query parameter.
func (b *AdminListVolunteerActivitiesReqBuilder) IsUrgent(v bool) *AdminListVolunteerActivitiesReqBuilder {
	b.req.queryParams["is_urgent"] = strconv.FormatBool(v)
	return b
}

// Keyword sets the "keyword" query parameter.
func (b *AdminListVolunteerActivitiesReqBuilder) Keyword(v string) *AdminListVolunteerActivitiesReqBuilder {
	b.req.queryParams["keyword"] = v
	return b
}

// Status sets the "status" query parameter.
func (b *AdminListVolunteerActivitiesReqBuilder) Status(v string) *AdminListVolunteerActivitiesReqBuilder {
	b.req.queryParams["status"] = v
	return b
}

// CreatedByUserId sets the "created_by_user_id" query parameter.
func (b *AdminListVolunteerActivitiesReqBuilder) CreatedByUserId(v string) *AdminListVolunteerActivitiesReqBuilder {
	b.req.queryParams["created_by_user_id"] = v
	return b
}

// Build finalizes the request.
func (b *AdminListVolunteerActivitiesReqBuilder) Build() *AdminListVolunteerActivitiesReq {
	return b.req
}

// AdminListVolunteerActivitiesResp is the response for AdminListVolunteerActivities.
type AdminListVolunteerActivitiesResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.ActivityListData `json:"data"`
}

// AdminListVolunteerActivities: 志愿活动管理列表
func (s *Service) AdminListVolunteerActivities(ctx context.Context, req *AdminListVolunteerActivitiesReq, opts ...core.RequestOption) (*AdminListVolunteerActivitiesResp, error) {
	resp := &AdminListVolunteerActivitiesResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/volunteer-admin/activities",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminGetVolunteerActivityReq is the request for AdminGetVolunteerActivity.
type AdminGetVolunteerActivityReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminGetVolunteerActivityReqBuilder builds a AdminGetVolunteerActivityReq with a fluent setter per field.
type AdminGetVolunteerActivityReqBuilder struct{ req *AdminGetVolunteerActivityReq }

// NewAdminGetVolunteerActivityReqBuilder creates a request builder for AdminGetVolunteerActivity.
func NewAdminGetVolunteerActivityReqBuilder() *AdminGetVolunteerActivityReqBuilder {
	return &AdminGetVolunteerActivityReqBuilder{req: &AdminGetVolunteerActivityReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *AdminGetVolunteerActivityReqBuilder) Id(v string) *AdminGetVolunteerActivityReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Build finalizes the request.
func (b *AdminGetVolunteerActivityReqBuilder) Build() *AdminGetVolunteerActivityReq { return b.req }

// AdminGetVolunteerActivityResp is the response for AdminGetVolunteerActivity.
type AdminGetVolunteerActivityResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.ActivityDetail `json:"data"`
}

// AdminGetVolunteerActivity: 志愿活动管理详情
func (s *Service) AdminGetVolunteerActivity(ctx context.Context, req *AdminGetVolunteerActivityReq, opts ...core.RequestOption) (*AdminGetVolunteerActivityResp, error) {
	resp := &AdminGetVolunteerActivityResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/volunteer-admin/activities/{id}",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminUpdateVolunteerActivityReq is the request for AdminUpdateVolunteerActivity.
type AdminUpdateVolunteerActivityReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminUpdateVolunteerActivityReqBuilder builds a AdminUpdateVolunteerActivityReq with a fluent setter per field.
type AdminUpdateVolunteerActivityReqBuilder struct {
	req *AdminUpdateVolunteerActivityReq
}

// NewAdminUpdateVolunteerActivityReqBuilder creates a request builder for AdminUpdateVolunteerActivity.
func NewAdminUpdateVolunteerActivityReqBuilder() *AdminUpdateVolunteerActivityReqBuilder {
	return &AdminUpdateVolunteerActivityReqBuilder{req: &AdminUpdateVolunteerActivityReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *AdminUpdateVolunteerActivityReqBuilder) Id(v string) *AdminUpdateVolunteerActivityReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Body sets the request body.
func (b *AdminUpdateVolunteerActivityReqBuilder) Body(body *models.UpdateActivityRequestBody) *AdminUpdateVolunteerActivityReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *AdminUpdateVolunteerActivityReqBuilder) Build() *AdminUpdateVolunteerActivityReq {
	return b.req
}

// AdminUpdateVolunteerActivityResp is the response for AdminUpdateVolunteerActivity.
type AdminUpdateVolunteerActivityResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.ActivityDetail `json:"data"`
}

// AdminUpdateVolunteerActivity: 管理员编辑志愿活动
func (s *Service) AdminUpdateVolunteerActivity(ctx context.Context, req *AdminUpdateVolunteerActivityReq, opts ...core.RequestOption) (*AdminUpdateVolunteerActivityResp, error) {
	resp := &AdminUpdateVolunteerActivityResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/volunteer-admin/activities/{id}",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminOfflineVolunteerActivityReq is the request for AdminOfflineVolunteerActivity.
type AdminOfflineVolunteerActivityReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminOfflineVolunteerActivityReqBuilder builds a AdminOfflineVolunteerActivityReq with a fluent setter per field.
type AdminOfflineVolunteerActivityReqBuilder struct {
	req *AdminOfflineVolunteerActivityReq
}

// NewAdminOfflineVolunteerActivityReqBuilder creates a request builder for AdminOfflineVolunteerActivity.
func NewAdminOfflineVolunteerActivityReqBuilder() *AdminOfflineVolunteerActivityReqBuilder {
	return &AdminOfflineVolunteerActivityReqBuilder{req: &AdminOfflineVolunteerActivityReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *AdminOfflineVolunteerActivityReqBuilder) Id(v string) *AdminOfflineVolunteerActivityReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Build finalizes the request.
func (b *AdminOfflineVolunteerActivityReqBuilder) Build() *AdminOfflineVolunteerActivityReq {
	return b.req
}

// AdminOfflineVolunteerActivityResp is the response for AdminOfflineVolunteerActivity.
type AdminOfflineVolunteerActivityResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// AdminOfflineVolunteerActivity: 管理员下架志愿活动
func (s *Service) AdminOfflineVolunteerActivity(ctx context.Context, req *AdminOfflineVolunteerActivityReq, opts ...core.RequestOption) (*AdminOfflineVolunteerActivityResp, error) {
	resp := &AdminOfflineVolunteerActivityResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "DELETE",
		PathTemplate: "/hduhelp-neo/admin/volunteer-admin/activities/{id}",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminCancelVolunteerUrgentReq is the request for AdminCancelVolunteerUrgent.
type AdminCancelVolunteerUrgentReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminCancelVolunteerUrgentReqBuilder builds a AdminCancelVolunteerUrgentReq with a fluent setter per field.
type AdminCancelVolunteerUrgentReqBuilder struct {
	req *AdminCancelVolunteerUrgentReq
}

// NewAdminCancelVolunteerUrgentReqBuilder creates a request builder for AdminCancelVolunteerUrgent.
func NewAdminCancelVolunteerUrgentReqBuilder() *AdminCancelVolunteerUrgentReqBuilder {
	return &AdminCancelVolunteerUrgentReqBuilder{req: &AdminCancelVolunteerUrgentReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *AdminCancelVolunteerUrgentReqBuilder) Id(v string) *AdminCancelVolunteerUrgentReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Build finalizes the request.
func (b *AdminCancelVolunteerUrgentReqBuilder) Build() *AdminCancelVolunteerUrgentReq { return b.req }

// AdminCancelVolunteerUrgentResp is the response for AdminCancelVolunteerUrgent.
type AdminCancelVolunteerUrgentResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.ActivityDetail `json:"data"`
}

// AdminCancelVolunteerUrgent: 取消活动加急
func (s *Service) AdminCancelVolunteerUrgent(ctx context.Context, req *AdminCancelVolunteerUrgentReq, opts ...core.RequestOption) (*AdminCancelVolunteerUrgentResp, error) {
	resp := &AdminCancelVolunteerUrgentResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "DELETE",
		PathTemplate: "/hduhelp-neo/admin/volunteer-admin/activities/{id}/urgent",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminListVolunteerUrgentApplicationsReq is the request for AdminListVolunteerUrgentApplications.
type AdminListVolunteerUrgentApplicationsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminListVolunteerUrgentApplicationsReqBuilder builds a AdminListVolunteerUrgentApplicationsReq with a fluent setter per field.
type AdminListVolunteerUrgentApplicationsReqBuilder struct {
	req *AdminListVolunteerUrgentApplicationsReq
}

// NewAdminListVolunteerUrgentApplicationsReqBuilder creates a request builder for AdminListVolunteerUrgentApplications.
func NewAdminListVolunteerUrgentApplicationsReqBuilder() *AdminListVolunteerUrgentApplicationsReqBuilder {
	return &AdminListVolunteerUrgentApplicationsReqBuilder{req: &AdminListVolunteerUrgentApplicationsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Page sets the "page" query parameter.
func (b *AdminListVolunteerUrgentApplicationsReqBuilder) Page(v int32) *AdminListVolunteerUrgentApplicationsReqBuilder {
	b.req.queryParams["page"] = strconv.FormatInt(int64(v), 10)
	return b
}

// PageSize sets the "page_size" query parameter.
func (b *AdminListVolunteerUrgentApplicationsReqBuilder) PageSize(v int32) *AdminListVolunteerUrgentApplicationsReqBuilder {
	b.req.queryParams["page_size"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Status sets the "status" query parameter.
func (b *AdminListVolunteerUrgentApplicationsReqBuilder) Status(v string) *AdminListVolunteerUrgentApplicationsReqBuilder {
	b.req.queryParams["status"] = v
	return b
}

// Organization sets the "organization" query parameter.
func (b *AdminListVolunteerUrgentApplicationsReqBuilder) Organization(v string) *AdminListVolunteerUrgentApplicationsReqBuilder {
	b.req.queryParams["organization"] = v
	return b
}

// Category sets the "category" query parameter.
func (b *AdminListVolunteerUrgentApplicationsReqBuilder) Category(v string) *AdminListVolunteerUrgentApplicationsReqBuilder {
	b.req.queryParams["category"] = v
	return b
}

// Build finalizes the request.
func (b *AdminListVolunteerUrgentApplicationsReqBuilder) Build() *AdminListVolunteerUrgentApplicationsReq {
	return b.req
}

// AdminListVolunteerUrgentApplicationsResp is the response for AdminListVolunteerUrgentApplications.
type AdminListVolunteerUrgentApplicationsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.UrgentApplicationListData `json:"data"`
}

// AdminListVolunteerUrgentApplications: 加急申请管理列表
func (s *Service) AdminListVolunteerUrgentApplications(ctx context.Context, req *AdminListVolunteerUrgentApplicationsReq, opts ...core.RequestOption) (*AdminListVolunteerUrgentApplicationsResp, error) {
	resp := &AdminListVolunteerUrgentApplicationsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/volunteer-admin/urgent-applications",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminReviewVolunteerUrgentApplicationReq is the request for AdminReviewVolunteerUrgentApplication.
type AdminReviewVolunteerUrgentApplicationReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminReviewVolunteerUrgentApplicationReqBuilder builds a AdminReviewVolunteerUrgentApplicationReq with a fluent setter per field.
type AdminReviewVolunteerUrgentApplicationReqBuilder struct {
	req *AdminReviewVolunteerUrgentApplicationReq
}

// NewAdminReviewVolunteerUrgentApplicationReqBuilder creates a request builder for AdminReviewVolunteerUrgentApplication.
func NewAdminReviewVolunteerUrgentApplicationReqBuilder() *AdminReviewVolunteerUrgentApplicationReqBuilder {
	return &AdminReviewVolunteerUrgentApplicationReqBuilder{req: &AdminReviewVolunteerUrgentApplicationReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *AdminReviewVolunteerUrgentApplicationReqBuilder) Id(v string) *AdminReviewVolunteerUrgentApplicationReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Body sets the request body.
func (b *AdminReviewVolunteerUrgentApplicationReqBuilder) Body(body *models.ReviewUrgentApplicationRequestBody) *AdminReviewVolunteerUrgentApplicationReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *AdminReviewVolunteerUrgentApplicationReqBuilder) Build() *AdminReviewVolunteerUrgentApplicationReq {
	return b.req
}

// AdminReviewVolunteerUrgentApplicationResp is the response for AdminReviewVolunteerUrgentApplication.
type AdminReviewVolunteerUrgentApplicationResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.UrgentApplication `json:"data"`
}

// AdminReviewVolunteerUrgentApplication: 审批加急申请
func (s *Service) AdminReviewVolunteerUrgentApplication(ctx context.Context, req *AdminReviewVolunteerUrgentApplicationReq, opts ...core.RequestOption) (*AdminReviewVolunteerUrgentApplicationResp, error) {
	resp := &AdminReviewVolunteerUrgentApplicationResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/volunteer-admin/urgent-applications/{id}/review",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListMyVolunteerActivitiesReq is the request for ListMyVolunteerActivities.
type ListMyVolunteerActivitiesReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListMyVolunteerActivitiesReqBuilder builds a ListMyVolunteerActivitiesReq with a fluent setter per field.
type ListMyVolunteerActivitiesReqBuilder struct{ req *ListMyVolunteerActivitiesReq }

// NewListMyVolunteerActivitiesReqBuilder creates a request builder for ListMyVolunteerActivities.
func NewListMyVolunteerActivitiesReqBuilder() *ListMyVolunteerActivitiesReqBuilder {
	return &ListMyVolunteerActivitiesReqBuilder{req: &ListMyVolunteerActivitiesReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Page sets the "page" query parameter.
func (b *ListMyVolunteerActivitiesReqBuilder) Page(v int32) *ListMyVolunteerActivitiesReqBuilder {
	b.req.queryParams["page"] = strconv.FormatInt(int64(v), 10)
	return b
}

// PageSize sets the "page_size" query parameter.
func (b *ListMyVolunteerActivitiesReqBuilder) PageSize(v int32) *ListMyVolunteerActivitiesReqBuilder {
	b.req.queryParams["page_size"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Category sets the "category" query parameter.
func (b *ListMyVolunteerActivitiesReqBuilder) Category(v string) *ListMyVolunteerActivitiesReqBuilder {
	b.req.queryParams["category"] = v
	return b
}

// Organization sets the "organization" query parameter.
func (b *ListMyVolunteerActivitiesReqBuilder) Organization(v string) *ListMyVolunteerActivitiesReqBuilder {
	b.req.queryParams["organization"] = v
	return b
}

// StartAtFrom sets the "start_at_from" query parameter.
func (b *ListMyVolunteerActivitiesReqBuilder) StartAtFrom(v int64) *ListMyVolunteerActivitiesReqBuilder {
	b.req.queryParams["start_at_from"] = strconv.FormatInt(v, 10)
	return b
}

// StartAtTo sets the "start_at_to" query parameter.
func (b *ListMyVolunteerActivitiesReqBuilder) StartAtTo(v int64) *ListMyVolunteerActivitiesReqBuilder {
	b.req.queryParams["start_at_to"] = strconv.FormatInt(v, 10)
	return b
}

// DeadlineAtFrom sets the "deadline_at_from" query parameter.
func (b *ListMyVolunteerActivitiesReqBuilder) DeadlineAtFrom(v int64) *ListMyVolunteerActivitiesReqBuilder {
	b.req.queryParams["deadline_at_from"] = strconv.FormatInt(v, 10)
	return b
}

// DeadlineAtTo sets the "deadline_at_to" query parameter.
func (b *ListMyVolunteerActivitiesReqBuilder) DeadlineAtTo(v int64) *ListMyVolunteerActivitiesReqBuilder {
	b.req.queryParams["deadline_at_to"] = strconv.FormatInt(v, 10)
	return b
}

// IsUrgent sets the "is_urgent" query parameter.
func (b *ListMyVolunteerActivitiesReqBuilder) IsUrgent(v bool) *ListMyVolunteerActivitiesReqBuilder {
	b.req.queryParams["is_urgent"] = strconv.FormatBool(v)
	return b
}

// Keyword sets the "keyword" query parameter.
func (b *ListMyVolunteerActivitiesReqBuilder) Keyword(v string) *ListMyVolunteerActivitiesReqBuilder {
	b.req.queryParams["keyword"] = v
	return b
}

// Status sets the "status" query parameter.
func (b *ListMyVolunteerActivitiesReqBuilder) Status(v string) *ListMyVolunteerActivitiesReqBuilder {
	b.req.queryParams["status"] = v
	return b
}

// CreatedByUserId sets the "created_by_user_id" query parameter.
func (b *ListMyVolunteerActivitiesReqBuilder) CreatedByUserId(v string) *ListMyVolunteerActivitiesReqBuilder {
	b.req.queryParams["created_by_user_id"] = v
	return b
}

// Build finalizes the request.
func (b *ListMyVolunteerActivitiesReqBuilder) Build() *ListMyVolunteerActivitiesReq { return b.req }

// ListMyVolunteerActivitiesResp is the response for ListMyVolunteerActivities.
type ListMyVolunteerActivitiesResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.ActivityListData `json:"data"`
}

// ListMyVolunteerActivities: 我的志愿活动
func (s *Service) ListMyVolunteerActivities(ctx context.Context, req *ListMyVolunteerActivitiesReq, opts ...core.RequestOption) (*ListMyVolunteerActivitiesResp, error) {
	resp := &ListMyVolunteerActivitiesResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/volunteer/creator-activities",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// GetVolunteerMeReq is the request for GetVolunteerMe.
type GetVolunteerMeReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// GetVolunteerMeReqBuilder builds a GetVolunteerMeReq with a fluent setter per field.
type GetVolunteerMeReqBuilder struct{ req *GetVolunteerMeReq }

// NewGetVolunteerMeReqBuilder creates a request builder for GetVolunteerMe.
func NewGetVolunteerMeReqBuilder() *GetVolunteerMeReqBuilder {
	return &GetVolunteerMeReqBuilder{req: &GetVolunteerMeReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *GetVolunteerMeReqBuilder) Build() *GetVolunteerMeReq { return b.req }

// GetVolunteerMeResp is the response for GetVolunteerMe.
type GetVolunteerMeResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.VolunteerMe `json:"data"`
}

// GetVolunteerMe: 当前用户 volunteer 权限
func (s *Service) GetVolunteerMe(ctx context.Context, req *GetVolunteerMeReq, opts ...core.RequestOption) (*GetVolunteerMeResp, error) {
	resp := &GetVolunteerMeResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/volunteer/creator-profile",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListMyVolunteerUrgentApplicationsReq is the request for ListMyVolunteerUrgentApplications.
type ListMyVolunteerUrgentApplicationsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListMyVolunteerUrgentApplicationsReqBuilder builds a ListMyVolunteerUrgentApplicationsReq with a fluent setter per field.
type ListMyVolunteerUrgentApplicationsReqBuilder struct {
	req *ListMyVolunteerUrgentApplicationsReq
}

// NewListMyVolunteerUrgentApplicationsReqBuilder creates a request builder for ListMyVolunteerUrgentApplications.
func NewListMyVolunteerUrgentApplicationsReqBuilder() *ListMyVolunteerUrgentApplicationsReqBuilder {
	return &ListMyVolunteerUrgentApplicationsReqBuilder{req: &ListMyVolunteerUrgentApplicationsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Page sets the "page" query parameter.
func (b *ListMyVolunteerUrgentApplicationsReqBuilder) Page(v int32) *ListMyVolunteerUrgentApplicationsReqBuilder {
	b.req.queryParams["page"] = strconv.FormatInt(int64(v), 10)
	return b
}

// PageSize sets the "page_size" query parameter.
func (b *ListMyVolunteerUrgentApplicationsReqBuilder) PageSize(v int32) *ListMyVolunteerUrgentApplicationsReqBuilder {
	b.req.queryParams["page_size"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Status sets the "status" query parameter.
func (b *ListMyVolunteerUrgentApplicationsReqBuilder) Status(v string) *ListMyVolunteerUrgentApplicationsReqBuilder {
	b.req.queryParams["status"] = v
	return b
}

// Organization sets the "organization" query parameter.
func (b *ListMyVolunteerUrgentApplicationsReqBuilder) Organization(v string) *ListMyVolunteerUrgentApplicationsReqBuilder {
	b.req.queryParams["organization"] = v
	return b
}

// Category sets the "category" query parameter.
func (b *ListMyVolunteerUrgentApplicationsReqBuilder) Category(v string) *ListMyVolunteerUrgentApplicationsReqBuilder {
	b.req.queryParams["category"] = v
	return b
}

// Build finalizes the request.
func (b *ListMyVolunteerUrgentApplicationsReqBuilder) Build() *ListMyVolunteerUrgentApplicationsReq {
	return b.req
}

// ListMyVolunteerUrgentApplicationsResp is the response for ListMyVolunteerUrgentApplications.
type ListMyVolunteerUrgentApplicationsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.UrgentApplicationListData `json:"data"`
}

// ListMyVolunteerUrgentApplications: 我的加急申请
func (s *Service) ListMyVolunteerUrgentApplications(ctx context.Context, req *ListMyVolunteerUrgentApplicationsReq, opts ...core.RequestOption) (*ListMyVolunteerUrgentApplicationsResp, error) {
	resp := &ListMyVolunteerUrgentApplicationsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/volunteer/creator-urgent-applications",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListVolunteerActivitiesReq is the request for ListVolunteerActivities.
type ListVolunteerActivitiesReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListVolunteerActivitiesReqBuilder builds a ListVolunteerActivitiesReq with a fluent setter per field.
type ListVolunteerActivitiesReqBuilder struct{ req *ListVolunteerActivitiesReq }

// NewListVolunteerActivitiesReqBuilder creates a request builder for ListVolunteerActivities.
func NewListVolunteerActivitiesReqBuilder() *ListVolunteerActivitiesReqBuilder {
	return &ListVolunteerActivitiesReqBuilder{req: &ListVolunteerActivitiesReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Page sets the "page" query parameter.
func (b *ListVolunteerActivitiesReqBuilder) Page(v int32) *ListVolunteerActivitiesReqBuilder {
	b.req.queryParams["page"] = strconv.FormatInt(int64(v), 10)
	return b
}

// PageSize sets the "page_size" query parameter.
func (b *ListVolunteerActivitiesReqBuilder) PageSize(v int32) *ListVolunteerActivitiesReqBuilder {
	b.req.queryParams["page_size"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Category sets the "category" query parameter.
func (b *ListVolunteerActivitiesReqBuilder) Category(v string) *ListVolunteerActivitiesReqBuilder {
	b.req.queryParams["category"] = v
	return b
}

// Organization sets the "organization" query parameter.
func (b *ListVolunteerActivitiesReqBuilder) Organization(v string) *ListVolunteerActivitiesReqBuilder {
	b.req.queryParams["organization"] = v
	return b
}

// StartAtFrom sets the "start_at_from" query parameter.
func (b *ListVolunteerActivitiesReqBuilder) StartAtFrom(v int64) *ListVolunteerActivitiesReqBuilder {
	b.req.queryParams["start_at_from"] = strconv.FormatInt(v, 10)
	return b
}

// StartAtTo sets the "start_at_to" query parameter.
func (b *ListVolunteerActivitiesReqBuilder) StartAtTo(v int64) *ListVolunteerActivitiesReqBuilder {
	b.req.queryParams["start_at_to"] = strconv.FormatInt(v, 10)
	return b
}

// DeadlineAtFrom sets the "deadline_at_from" query parameter.
func (b *ListVolunteerActivitiesReqBuilder) DeadlineAtFrom(v int64) *ListVolunteerActivitiesReqBuilder {
	b.req.queryParams["deadline_at_from"] = strconv.FormatInt(v, 10)
	return b
}

// DeadlineAtTo sets the "deadline_at_to" query parameter.
func (b *ListVolunteerActivitiesReqBuilder) DeadlineAtTo(v int64) *ListVolunteerActivitiesReqBuilder {
	b.req.queryParams["deadline_at_to"] = strconv.FormatInt(v, 10)
	return b
}

// IsUrgent sets the "is_urgent" query parameter.
func (b *ListVolunteerActivitiesReqBuilder) IsUrgent(v bool) *ListVolunteerActivitiesReqBuilder {
	b.req.queryParams["is_urgent"] = strconv.FormatBool(v)
	return b
}

// Keyword sets the "keyword" query parameter.
func (b *ListVolunteerActivitiesReqBuilder) Keyword(v string) *ListVolunteerActivitiesReqBuilder {
	b.req.queryParams["keyword"] = v
	return b
}

// Status sets the "status" query parameter.
func (b *ListVolunteerActivitiesReqBuilder) Status(v string) *ListVolunteerActivitiesReqBuilder {
	b.req.queryParams["status"] = v
	return b
}

// CreatedByUserId sets the "created_by_user_id" query parameter.
func (b *ListVolunteerActivitiesReqBuilder) CreatedByUserId(v string) *ListVolunteerActivitiesReqBuilder {
	b.req.queryParams["created_by_user_id"] = v
	return b
}

// Build finalizes the request.
func (b *ListVolunteerActivitiesReqBuilder) Build() *ListVolunteerActivitiesReq { return b.req }

// ListVolunteerActivitiesResp is the response for ListVolunteerActivities.
type ListVolunteerActivitiesResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.ActivityListData `json:"data"`
}

// ListVolunteerActivities: 志愿活动列表
func (s *Service) ListVolunteerActivities(ctx context.Context, req *ListVolunteerActivitiesReq, opts ...core.RequestOption) (*ListVolunteerActivitiesResp, error) {
	resp := &ListVolunteerActivitiesResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/volunteer/volunteer-activities",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// CreateVolunteerActivityReq is the request for CreateVolunteerActivity.
type CreateVolunteerActivityReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// CreateVolunteerActivityReqBuilder builds a CreateVolunteerActivityReq with a fluent setter per field.
type CreateVolunteerActivityReqBuilder struct{ req *CreateVolunteerActivityReq }

// NewCreateVolunteerActivityReqBuilder creates a request builder for CreateVolunteerActivity.
func NewCreateVolunteerActivityReqBuilder() *CreateVolunteerActivityReqBuilder {
	return &CreateVolunteerActivityReqBuilder{req: &CreateVolunteerActivityReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *CreateVolunteerActivityReqBuilder) Body(body *models.CreateActivityRequestBody) *CreateVolunteerActivityReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *CreateVolunteerActivityReqBuilder) Build() *CreateVolunteerActivityReq { return b.req }

// CreateVolunteerActivityResp is the response for CreateVolunteerActivity.
type CreateVolunteerActivityResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.ActivityDetail `json:"data"`
}

// CreateVolunteerActivity: 创建志愿活动
func (s *Service) CreateVolunteerActivity(ctx context.Context, req *CreateVolunteerActivityReq, opts ...core.RequestOption) (*CreateVolunteerActivityResp, error) {
	resp := &CreateVolunteerActivityResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/volunteer/volunteer-activities",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// GetVolunteerActivityReq is the request for GetVolunteerActivity.
type GetVolunteerActivityReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// GetVolunteerActivityReqBuilder builds a GetVolunteerActivityReq with a fluent setter per field.
type GetVolunteerActivityReqBuilder struct{ req *GetVolunteerActivityReq }

// NewGetVolunteerActivityReqBuilder creates a request builder for GetVolunteerActivity.
func NewGetVolunteerActivityReqBuilder() *GetVolunteerActivityReqBuilder {
	return &GetVolunteerActivityReqBuilder{req: &GetVolunteerActivityReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *GetVolunteerActivityReqBuilder) Id(v string) *GetVolunteerActivityReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Build finalizes the request.
func (b *GetVolunteerActivityReqBuilder) Build() *GetVolunteerActivityReq { return b.req }

// GetVolunteerActivityResp is the response for GetVolunteerActivity.
type GetVolunteerActivityResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.ActivityDetail `json:"data"`
}

// GetVolunteerActivity: 志愿活动详情
func (s *Service) GetVolunteerActivity(ctx context.Context, req *GetVolunteerActivityReq, opts ...core.RequestOption) (*GetVolunteerActivityResp, error) {
	resp := &GetVolunteerActivityResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/volunteer/volunteer-activities/{id}",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// UpdateVolunteerActivityReq is the request for UpdateVolunteerActivity.
type UpdateVolunteerActivityReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// UpdateVolunteerActivityReqBuilder builds a UpdateVolunteerActivityReq with a fluent setter per field.
type UpdateVolunteerActivityReqBuilder struct{ req *UpdateVolunteerActivityReq }

// NewUpdateVolunteerActivityReqBuilder creates a request builder for UpdateVolunteerActivity.
func NewUpdateVolunteerActivityReqBuilder() *UpdateVolunteerActivityReqBuilder {
	return &UpdateVolunteerActivityReqBuilder{req: &UpdateVolunteerActivityReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *UpdateVolunteerActivityReqBuilder) Id(v string) *UpdateVolunteerActivityReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Body sets the request body.
func (b *UpdateVolunteerActivityReqBuilder) Body(body *models.UpdateActivityRequestBody) *UpdateVolunteerActivityReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *UpdateVolunteerActivityReqBuilder) Build() *UpdateVolunteerActivityReq { return b.req }

// UpdateVolunteerActivityResp is the response for UpdateVolunteerActivity.
type UpdateVolunteerActivityResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.ActivityDetail `json:"data"`
}

// UpdateVolunteerActivity: 编辑本人志愿活动
func (s *Service) UpdateVolunteerActivity(ctx context.Context, req *UpdateVolunteerActivityReq, opts ...core.RequestOption) (*UpdateVolunteerActivityResp, error) {
	resp := &UpdateVolunteerActivityResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/volunteer/volunteer-activities/{id}",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// OfflineVolunteerActivityReq is the request for OfflineVolunteerActivity.
type OfflineVolunteerActivityReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// OfflineVolunteerActivityReqBuilder builds a OfflineVolunteerActivityReq with a fluent setter per field.
type OfflineVolunteerActivityReqBuilder struct{ req *OfflineVolunteerActivityReq }

// NewOfflineVolunteerActivityReqBuilder creates a request builder for OfflineVolunteerActivity.
func NewOfflineVolunteerActivityReqBuilder() *OfflineVolunteerActivityReqBuilder {
	return &OfflineVolunteerActivityReqBuilder{req: &OfflineVolunteerActivityReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *OfflineVolunteerActivityReqBuilder) Id(v string) *OfflineVolunteerActivityReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Build finalizes the request.
func (b *OfflineVolunteerActivityReqBuilder) Build() *OfflineVolunteerActivityReq { return b.req }

// OfflineVolunteerActivityResp is the response for OfflineVolunteerActivity.
type OfflineVolunteerActivityResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// OfflineVolunteerActivity: 下架本人志愿活动
func (s *Service) OfflineVolunteerActivity(ctx context.Context, req *OfflineVolunteerActivityReq, opts ...core.RequestOption) (*OfflineVolunteerActivityResp, error) {
	resp := &OfflineVolunteerActivityResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "DELETE",
		PathTemplate: "/hduhelp-neo/volunteer/volunteer-activities/{id}",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// SubmitVolunteerUrgentApplicationReq is the request for SubmitVolunteerUrgentApplication.
type SubmitVolunteerUrgentApplicationReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// SubmitVolunteerUrgentApplicationReqBuilder builds a SubmitVolunteerUrgentApplicationReq with a fluent setter per field.
type SubmitVolunteerUrgentApplicationReqBuilder struct {
	req *SubmitVolunteerUrgentApplicationReq
}

// NewSubmitVolunteerUrgentApplicationReqBuilder creates a request builder for SubmitVolunteerUrgentApplication.
func NewSubmitVolunteerUrgentApplicationReqBuilder() *SubmitVolunteerUrgentApplicationReqBuilder {
	return &SubmitVolunteerUrgentApplicationReqBuilder{req: &SubmitVolunteerUrgentApplicationReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *SubmitVolunteerUrgentApplicationReqBuilder) Id(v string) *SubmitVolunteerUrgentApplicationReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Body sets the request body.
func (b *SubmitVolunteerUrgentApplicationReqBuilder) Body(body *models.SubmitUrgentApplicationRequestBody) *SubmitVolunteerUrgentApplicationReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *SubmitVolunteerUrgentApplicationReqBuilder) Build() *SubmitVolunteerUrgentApplicationReq {
	return b.req
}

// SubmitVolunteerUrgentApplicationResp is the response for SubmitVolunteerUrgentApplication.
type SubmitVolunteerUrgentApplicationResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.UrgentApplication `json:"data"`
}

// SubmitVolunteerUrgentApplication: 提交活动加急申请
func (s *Service) SubmitVolunteerUrgentApplication(ctx context.Context, req *SubmitVolunteerUrgentApplicationReq, opts ...core.RequestOption) (*SubmitVolunteerUrgentApplicationResp, error) {
	resp := &SubmitVolunteerUrgentApplicationResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/volunteer/volunteer-activities/{id}/urgent-applications",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}
