// Code generated by hduhelp-sdk-gen; DO NOT EDIT.

package adminnotice

import (
	"context"
	"strconv"

	"github.com/hduhelp/hduhelp-neo-sdk-go/core"
	"github.com/hduhelp/hduhelp-neo-sdk-go/models"
)

// Service groups the AdminNotice endpoints.
type Service struct{ config *core.Config }

// NewService binds the AdminNotice service to a client config.
func NewService(config *core.Config) *Service { return &Service{config: config} }

// ListAdminNoticesReq is the request for ListAdminNotices.
type ListAdminNoticesReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListAdminNoticesReqBuilder builds a ListAdminNoticesReq with a fluent setter per field.
type ListAdminNoticesReqBuilder struct{ req *ListAdminNoticesReq }

// NewListAdminNoticesReqBuilder creates a request builder for ListAdminNotices.
func NewListAdminNoticesReqBuilder() *ListAdminNoticesReqBuilder {
	return &ListAdminNoticesReqBuilder{req: &ListAdminNoticesReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Status sets the "status" query parameter.
func (b *ListAdminNoticesReqBuilder) Status(v string) *ListAdminNoticesReqBuilder {
	b.req.queryParams["status"] = v
	return b
}

// Page sets the "page" query parameter.
func (b *ListAdminNoticesReqBuilder) Page(v int32) *ListAdminNoticesReqBuilder {
	b.req.queryParams["page"] = strconv.FormatInt(int64(v), 10)
	return b
}

// PageSize sets the "page_size" query parameter.
func (b *ListAdminNoticesReqBuilder) PageSize(v int32) *ListAdminNoticesReqBuilder {
	b.req.queryParams["page_size"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Build finalizes the request.
func (b *ListAdminNoticesReqBuilder) Build() *ListAdminNoticesReq { return b.req }

// ListAdminNoticesResp is the response for ListAdminNotices.
type ListAdminNoticesResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.AdminNoticePage `json:"data"`
}

// ListAdminNotices calls GET /hduhelp-neo/admin/notices.
func (s *Service) ListAdminNotices(ctx context.Context, req *ListAdminNoticesReq, opts ...core.RequestOption) (*ListAdminNoticesResp, error) {
	resp := &ListAdminNoticesResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/notices",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// CreateAdminNoticeReq is the request for CreateAdminNotice.
type CreateAdminNoticeReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// CreateAdminNoticeReqBuilder builds a CreateAdminNoticeReq with a fluent setter per field.
type CreateAdminNoticeReqBuilder struct{ req *CreateAdminNoticeReq }

// NewCreateAdminNoticeReqBuilder creates a request builder for CreateAdminNotice.
func NewCreateAdminNoticeReqBuilder() *CreateAdminNoticeReqBuilder {
	return &CreateAdminNoticeReqBuilder{req: &CreateAdminNoticeReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *CreateAdminNoticeReqBuilder) Body(body *models.CreateAdminNoticeRequestBody) *CreateAdminNoticeReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *CreateAdminNoticeReqBuilder) Build() *CreateAdminNoticeReq { return b.req }

// CreateAdminNoticeResp is the response for CreateAdminNotice.
type CreateAdminNoticeResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.AdminNotice `json:"data"`
}

// CreateAdminNotice calls POST /hduhelp-neo/admin/notices.
func (s *Service) CreateAdminNotice(ctx context.Context, req *CreateAdminNoticeReq, opts ...core.RequestOption) (*CreateAdminNoticeResp, error) {
	resp := &CreateAdminNoticeResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/notices",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// GetAdminNoticeReq is the request for GetAdminNotice.
type GetAdminNoticeReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// GetAdminNoticeReqBuilder builds a GetAdminNoticeReq with a fluent setter per field.
type GetAdminNoticeReqBuilder struct{ req *GetAdminNoticeReq }

// NewGetAdminNoticeReqBuilder creates a request builder for GetAdminNotice.
func NewGetAdminNoticeReqBuilder() *GetAdminNoticeReqBuilder {
	return &GetAdminNoticeReqBuilder{req: &GetAdminNoticeReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *GetAdminNoticeReqBuilder) Id(v string) *GetAdminNoticeReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Build finalizes the request.
func (b *GetAdminNoticeReqBuilder) Build() *GetAdminNoticeReq { return b.req }

// GetAdminNoticeResp is the response for GetAdminNotice.
type GetAdminNoticeResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.AdminNotice `json:"data"`
}

// GetAdminNotice calls GET /hduhelp-neo/admin/notices/{id}.
func (s *Service) GetAdminNotice(ctx context.Context, req *GetAdminNoticeReq, opts ...core.RequestOption) (*GetAdminNoticeResp, error) {
	resp := &GetAdminNoticeResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/notices/{id}",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// UpdateAdminNoticeReq is the request for UpdateAdminNotice.
type UpdateAdminNoticeReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// UpdateAdminNoticeReqBuilder builds a UpdateAdminNoticeReq with a fluent setter per field.
type UpdateAdminNoticeReqBuilder struct{ req *UpdateAdminNoticeReq }

// NewUpdateAdminNoticeReqBuilder creates a request builder for UpdateAdminNotice.
func NewUpdateAdminNoticeReqBuilder() *UpdateAdminNoticeReqBuilder {
	return &UpdateAdminNoticeReqBuilder{req: &UpdateAdminNoticeReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *UpdateAdminNoticeReqBuilder) Id(v string) *UpdateAdminNoticeReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Body sets the request body.
func (b *UpdateAdminNoticeReqBuilder) Body(body *models.UpdateAdminNoticeRequestBody) *UpdateAdminNoticeReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *UpdateAdminNoticeReqBuilder) Build() *UpdateAdminNoticeReq { return b.req }

// UpdateAdminNoticeResp is the response for UpdateAdminNotice.
type UpdateAdminNoticeResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.AdminNotice `json:"data"`
}

// UpdateAdminNotice calls PUT /hduhelp-neo/admin/notices/{id}.
func (s *Service) UpdateAdminNotice(ctx context.Context, req *UpdateAdminNoticeReq, opts ...core.RequestOption) (*UpdateAdminNoticeResp, error) {
	resp := &UpdateAdminNoticeResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/notices/{id}",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// CancelAdminNoticeReq is the request for CancelAdminNotice.
type CancelAdminNoticeReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// CancelAdminNoticeReqBuilder builds a CancelAdminNoticeReq with a fluent setter per field.
type CancelAdminNoticeReqBuilder struct{ req *CancelAdminNoticeReq }

// NewCancelAdminNoticeReqBuilder creates a request builder for CancelAdminNotice.
func NewCancelAdminNoticeReqBuilder() *CancelAdminNoticeReqBuilder {
	return &CancelAdminNoticeReqBuilder{req: &CancelAdminNoticeReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *CancelAdminNoticeReqBuilder) Id(v string) *CancelAdminNoticeReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Body sets the request body.
func (b *CancelAdminNoticeReqBuilder) Body(body *models.CancelAdminNoticeRequestBody) *CancelAdminNoticeReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *CancelAdminNoticeReqBuilder) Build() *CancelAdminNoticeReq { return b.req }

// CancelAdminNoticeResp is the response for CancelAdminNotice.
type CancelAdminNoticeResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.AdminNotice `json:"data"`
}

// CancelAdminNotice calls POST /hduhelp-neo/admin/notices/{id}/cancel.
func (s *Service) CancelAdminNotice(ctx context.Context, req *CancelAdminNoticeReq, opts ...core.RequestOption) (*CancelAdminNoticeResp, error) {
	resp := &CancelAdminNoticeResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/notices/{id}/cancel",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// RetryAdminNoticeDispatchReq is the request for RetryAdminNoticeDispatch.
type RetryAdminNoticeDispatchReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// RetryAdminNoticeDispatchReqBuilder builds a RetryAdminNoticeDispatchReq with a fluent setter per field.
type RetryAdminNoticeDispatchReqBuilder struct{ req *RetryAdminNoticeDispatchReq }

// NewRetryAdminNoticeDispatchReqBuilder creates a request builder for RetryAdminNoticeDispatch.
func NewRetryAdminNoticeDispatchReqBuilder() *RetryAdminNoticeDispatchReqBuilder {
	return &RetryAdminNoticeDispatchReqBuilder{req: &RetryAdminNoticeDispatchReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *RetryAdminNoticeDispatchReqBuilder) Id(v string) *RetryAdminNoticeDispatchReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Build finalizes the request.
func (b *RetryAdminNoticeDispatchReqBuilder) Build() *RetryAdminNoticeDispatchReq { return b.req }

// RetryAdminNoticeDispatchResp is the response for RetryAdminNoticeDispatch.
type RetryAdminNoticeDispatchResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.AdminNotice `json:"data"`
}

// RetryAdminNoticeDispatch calls POST /hduhelp-neo/admin/notices/{id}/retry-dispatch.
func (s *Service) RetryAdminNoticeDispatch(ctx context.Context, req *RetryAdminNoticeDispatchReq, opts ...core.RequestOption) (*RetryAdminNoticeDispatchResp, error) {
	resp := &RetryAdminNoticeDispatchResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/notices/{id}/retry-dispatch",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ReviewAdminNoticeReq is the request for ReviewAdminNotice.
type ReviewAdminNoticeReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ReviewAdminNoticeReqBuilder builds a ReviewAdminNoticeReq with a fluent setter per field.
type ReviewAdminNoticeReqBuilder struct{ req *ReviewAdminNoticeReq }

// NewReviewAdminNoticeReqBuilder creates a request builder for ReviewAdminNotice.
func NewReviewAdminNoticeReqBuilder() *ReviewAdminNoticeReqBuilder {
	return &ReviewAdminNoticeReqBuilder{req: &ReviewAdminNoticeReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *ReviewAdminNoticeReqBuilder) Id(v string) *ReviewAdminNoticeReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Body sets the request body.
func (b *ReviewAdminNoticeReqBuilder) Body(body *models.ReviewAdminNoticeRequestBody) *ReviewAdminNoticeReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *ReviewAdminNoticeReqBuilder) Build() *ReviewAdminNoticeReq { return b.req }

// ReviewAdminNoticeResp is the response for ReviewAdminNotice.
type ReviewAdminNoticeResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.AdminNotice `json:"data"`
}

// ReviewAdminNotice calls POST /hduhelp-neo/admin/notices/{id}/review.
func (s *Service) ReviewAdminNotice(ctx context.Context, req *ReviewAdminNoticeReq, opts ...core.RequestOption) (*ReviewAdminNoticeResp, error) {
	resp := &ReviewAdminNoticeResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/notices/{id}/review",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// SubmitAdminNoticeReq is the request for SubmitAdminNotice.
type SubmitAdminNoticeReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// SubmitAdminNoticeReqBuilder builds a SubmitAdminNoticeReq with a fluent setter per field.
type SubmitAdminNoticeReqBuilder struct{ req *SubmitAdminNoticeReq }

// NewSubmitAdminNoticeReqBuilder creates a request builder for SubmitAdminNotice.
func NewSubmitAdminNoticeReqBuilder() *SubmitAdminNoticeReqBuilder {
	return &SubmitAdminNoticeReqBuilder{req: &SubmitAdminNoticeReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *SubmitAdminNoticeReqBuilder) Id(v string) *SubmitAdminNoticeReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Body sets the request body.
func (b *SubmitAdminNoticeReqBuilder) Body(body *models.AdminNoticeVersionRequestBody) *SubmitAdminNoticeReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *SubmitAdminNoticeReqBuilder) Build() *SubmitAdminNoticeReq { return b.req }

// SubmitAdminNoticeResp is the response for SubmitAdminNotice.
type SubmitAdminNoticeResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.AdminNotice `json:"data"`
}

// SubmitAdminNotice calls POST /hduhelp-neo/admin/notices/{id}/submit.
func (s *Service) SubmitAdminNotice(ctx context.Context, req *SubmitAdminNoticeReq, opts ...core.RequestOption) (*SubmitAdminNoticeResp, error) {
	resp := &SubmitAdminNoticeResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/notices/{id}/submit",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}
