// Code generated by internal/gen; DO NOT EDIT.

package admin

import (
	"context"
	"strconv"

	"github.com/hduhelp/hduhelp-neo-sdk-go/core"
	"github.com/hduhelp/hduhelp-neo-sdk-go/models"
)

// Service groups the Admin endpoints.
type Service struct{ config *core.Config }

// NewService binds the Admin service to a client config.
func NewService(config *core.Config) *Service { return &Service{config: config} }

// ListAppsReq is the request for ListApps.
type ListAppsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListAppsReqBuilder builds a ListAppsReq with a fluent setter per field.
type ListAppsReqBuilder struct{ req *ListAppsReq }

// NewListAppsReqBuilder creates a request builder for ListApps.
func NewListAppsReqBuilder() *ListAppsReqBuilder {
	return &ListAppsReqBuilder{req: &ListAppsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *ListAppsReqBuilder) Build() *ListAppsReq { return b.req }

// ListAppsResp is the response for ListApps.
type ListAppsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.AdminAppInfo `json:"data"`
}

// ListApps: OAuth应用列表
func (s *Service) ListApps(ctx context.Context, req *ListAppsReq, opts ...core.RequestOption) (*ListAppsResp, error) {
	resp := &ListAppsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/apps",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// CreateAppReq is the request for CreateApp.
type CreateAppReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// CreateAppReqBuilder builds a CreateAppReq with a fluent setter per field.
type CreateAppReqBuilder struct{ req *CreateAppReq }

// NewCreateAppReqBuilder creates a request builder for CreateApp.
func NewCreateAppReqBuilder() *CreateAppReqBuilder {
	return &CreateAppReqBuilder{req: &CreateAppReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *CreateAppReqBuilder) Body(body *models.CreateAppRequestBody) *CreateAppReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *CreateAppReqBuilder) Build() *CreateAppReq { return b.req }

// CreateAppResp is the response for CreateApp.
type CreateAppResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.CreateAppData `json:"data"`
}

// CreateApp: 创建OAuth应用
func (s *Service) CreateApp(ctx context.Context, req *CreateAppReq, opts ...core.RequestOption) (*CreateAppResp, error) {
	resp := &CreateAppResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/apps",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// DisableAppReq is the request for DisableApp.
type DisableAppReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// DisableAppReqBuilder builds a DisableAppReq with a fluent setter per field.
type DisableAppReqBuilder struct{ req *DisableAppReq }

// NewDisableAppReqBuilder creates a request builder for DisableApp.
func NewDisableAppReqBuilder() *DisableAppReqBuilder {
	return &DisableAppReqBuilder{req: &DisableAppReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *DisableAppReqBuilder) Body(body *models.DisableAppRequestBody) *DisableAppReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *DisableAppReqBuilder) Build() *DisableAppReq { return b.req }

// DisableAppResp is the response for DisableApp.
type DisableAppResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// DisableApp: 停用OAuth应用
func (s *Service) DisableApp(ctx context.Context, req *DisableAppReq, opts ...core.RequestOption) (*DisableAppResp, error) {
	resp := &DisableAppResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/apps/disable",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// EnableAppReq is the request for EnableApp.
type EnableAppReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// EnableAppReqBuilder builds a EnableAppReq with a fluent setter per field.
type EnableAppReqBuilder struct{ req *EnableAppReq }

// NewEnableAppReqBuilder creates a request builder for EnableApp.
func NewEnableAppReqBuilder() *EnableAppReqBuilder {
	return &EnableAppReqBuilder{req: &EnableAppReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *EnableAppReqBuilder) Body(body *models.EnableAppRequestBody) *EnableAppReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *EnableAppReqBuilder) Build() *EnableAppReq { return b.req }

// EnableAppResp is the response for EnableApp.
type EnableAppResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// EnableApp: 启用OAuth应用
func (s *Service) EnableApp(ctx context.Context, req *EnableAppReq, opts ...core.RequestOption) (*EnableAppResp, error) {
	resp := &EnableAppResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/apps/enable",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// GetAppReq is the request for GetApp.
type GetAppReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// GetAppReqBuilder builds a GetAppReq with a fluent setter per field.
type GetAppReqBuilder struct{ req *GetAppReq }

// NewGetAppReqBuilder creates a request builder for GetApp.
func NewGetAppReqBuilder() *GetAppReqBuilder {
	return &GetAppReqBuilder{req: &GetAppReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" query parameter.
func (b *GetAppReqBuilder) Id(v string) *GetAppReqBuilder {
	b.req.queryParams["id"] = v
	return b
}

// Build finalizes the request.
func (b *GetAppReqBuilder) Build() *GetAppReq { return b.req }

// GetAppResp is the response for GetApp.
type GetAppResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.AdminAppDetail `json:"data"`
}

// GetApp: OAuth应用详情
func (s *Service) GetApp(ctx context.Context, req *GetAppReq, opts ...core.RequestOption) (*GetAppResp, error) {
	resp := &GetAppResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/apps/get",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// SetAppPermissionsReq is the request for SetAppPermissions.
type SetAppPermissionsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// SetAppPermissionsReqBuilder builds a SetAppPermissionsReq with a fluent setter per field.
type SetAppPermissionsReqBuilder struct{ req *SetAppPermissionsReq }

// NewSetAppPermissionsReqBuilder creates a request builder for SetAppPermissions.
func NewSetAppPermissionsReqBuilder() *SetAppPermissionsReqBuilder {
	return &SetAppPermissionsReqBuilder{req: &SetAppPermissionsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *SetAppPermissionsReqBuilder) Body(body *models.SetAppPermissionsRequestBody) *SetAppPermissionsReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *SetAppPermissionsReqBuilder) Build() *SetAppPermissionsReq { return b.req }

// SetAppPermissionsResp is the response for SetAppPermissions.
type SetAppPermissionsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// SetAppPermissions: 设置应用权限和用户权限
func (s *Service) SetAppPermissions(ctx context.Context, req *SetAppPermissionsReq, opts ...core.RequestOption) (*SetAppPermissionsResp, error) {
	resp := &SetAppPermissionsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/apps/permissions",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// UpdateAppReq is the request for UpdateApp.
type UpdateAppReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// UpdateAppReqBuilder builds a UpdateAppReq with a fluent setter per field.
type UpdateAppReqBuilder struct{ req *UpdateAppReq }

// NewUpdateAppReqBuilder creates a request builder for UpdateApp.
func NewUpdateAppReqBuilder() *UpdateAppReqBuilder {
	return &UpdateAppReqBuilder{req: &UpdateAppReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *UpdateAppReqBuilder) Body(body *models.UpdateAppRequestBody) *UpdateAppReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *UpdateAppReqBuilder) Build() *UpdateAppReq { return b.req }

// UpdateAppResp is the response for UpdateApp.
type UpdateAppResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.AdminAppDetail `json:"data"`
}

// UpdateApp: 编辑OAuth应用
func (s *Service) UpdateApp(ctx context.Context, req *UpdateAppReq, opts ...core.RequestOption) (*UpdateAppResp, error) {
	resp := &UpdateAppResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/apps/update",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminMeReq is the request for AdminMe.
type AdminMeReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminMeReqBuilder builds a AdminMeReq with a fluent setter per field.
type AdminMeReqBuilder struct{ req *AdminMeReq }

// NewAdminMeReqBuilder creates a request builder for AdminMe.
func NewAdminMeReqBuilder() *AdminMeReqBuilder {
	return &AdminMeReqBuilder{req: &AdminMeReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *AdminMeReqBuilder) Build() *AdminMeReq { return b.req }

// AdminMeResp is the response for AdminMe.
type AdminMeResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.OperatorInfo `json:"data"`
}

// AdminMe: 当前运营者信息
func (s *Service) AdminMe(ctx context.Context, req *AdminMeReq, opts ...core.RequestOption) (*AdminMeResp, error) {
	resp := &AdminMeResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/auth/me",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminChangePasswordReq is the request for AdminChangePassword.
type AdminChangePasswordReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminChangePasswordReqBuilder builds a AdminChangePasswordReq with a fluent setter per field.
type AdminChangePasswordReqBuilder struct{ req *AdminChangePasswordReq }

// NewAdminChangePasswordReqBuilder creates a request builder for AdminChangePassword.
func NewAdminChangePasswordReqBuilder() *AdminChangePasswordReqBuilder {
	return &AdminChangePasswordReqBuilder{req: &AdminChangePasswordReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *AdminChangePasswordReqBuilder) Body(body *models.ChangePasswordRequestBody) *AdminChangePasswordReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *AdminChangePasswordReqBuilder) Build() *AdminChangePasswordReq { return b.req }

// AdminChangePasswordResp is the response for AdminChangePassword.
type AdminChangePasswordResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// AdminChangePassword: 修改自己的口令
func (s *Service) AdminChangePassword(ctx context.Context, req *AdminChangePasswordReq, opts ...core.RequestOption) (*AdminChangePasswordResp, error) {
	resp := &AdminChangePasswordResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/auth/password/change",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListAuthorizationsReq is the request for ListAuthorizations.
type ListAuthorizationsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListAuthorizationsReqBuilder builds a ListAuthorizationsReq with a fluent setter per field.
type ListAuthorizationsReqBuilder struct{ req *ListAuthorizationsReq }

// NewListAuthorizationsReqBuilder creates a request builder for ListAuthorizations.
func NewListAuthorizationsReqBuilder() *ListAuthorizationsReqBuilder {
	return &ListAuthorizationsReqBuilder{req: &ListAuthorizationsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// AppId sets the "app_id" query parameter.
func (b *ListAuthorizationsReqBuilder) AppId(v string) *ListAuthorizationsReqBuilder {
	b.req.queryParams["app_id"] = v
	return b
}

// UserId sets the "user_id" query parameter.
func (b *ListAuthorizationsReqBuilder) UserId(v string) *ListAuthorizationsReqBuilder {
	b.req.queryParams["user_id"] = v
	return b
}

// Build finalizes the request.
func (b *ListAuthorizationsReqBuilder) Build() *ListAuthorizationsReq { return b.req }

// ListAuthorizationsResp is the response for ListAuthorizations.
type ListAuthorizationsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.AdminAuthorizationInfo `json:"data"`
}

// ListAuthorizations: 用户授权列表
func (s *Service) ListAuthorizations(ctx context.Context, req *ListAuthorizationsReq, opts ...core.RequestOption) (*ListAuthorizationsResp, error) {
	resp := &ListAuthorizationsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/authorizations",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// RevokeAuthorizationReq is the request for RevokeAuthorization.
type RevokeAuthorizationReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// RevokeAuthorizationReqBuilder builds a RevokeAuthorizationReq with a fluent setter per field.
type RevokeAuthorizationReqBuilder struct{ req *RevokeAuthorizationReq }

// NewRevokeAuthorizationReqBuilder creates a request builder for RevokeAuthorization.
func NewRevokeAuthorizationReqBuilder() *RevokeAuthorizationReqBuilder {
	return &RevokeAuthorizationReqBuilder{req: &RevokeAuthorizationReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *RevokeAuthorizationReqBuilder) Body(body *models.RevokeAuthorizationRequestBody) *RevokeAuthorizationReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *RevokeAuthorizationReqBuilder) Build() *RevokeAuthorizationReq { return b.req }

// RevokeAuthorizationResp is the response for RevokeAuthorization.
type RevokeAuthorizationResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// RevokeAuthorization: 撤销用户授权
func (s *Service) RevokeAuthorization(ctx context.Context, req *RevokeAuthorizationReq, opts ...core.RequestOption) (*RevokeAuthorizationResp, error) {
	resp := &RevokeAuthorizationResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/authorizations/revoke",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListCampusesReq is the request for ListCampuses.
type ListCampusesReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListCampusesReqBuilder builds a ListCampusesReq with a fluent setter per field.
type ListCampusesReqBuilder struct{ req *ListCampusesReq }

// NewListCampusesReqBuilder creates a request builder for ListCampuses.
func NewListCampusesReqBuilder() *ListCampusesReqBuilder {
	return &ListCampusesReqBuilder{req: &ListCampusesReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *ListCampusesReqBuilder) Build() *ListCampusesReq { return b.req }

// ListCampusesResp is the response for ListCampuses.
type ListCampusesResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.AdminCampusInfo `json:"data"`
}

// ListCampuses: 校区列表
func (s *Service) ListCampuses(ctx context.Context, req *ListCampusesReq, opts ...core.RequestOption) (*ListCampusesResp, error) {
	resp := &ListCampusesResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/campuses",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// CreateCampusReq is the request for CreateCampus.
type CreateCampusReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// CreateCampusReqBuilder builds a CreateCampusReq with a fluent setter per field.
type CreateCampusReqBuilder struct{ req *CreateCampusReq }

// NewCreateCampusReqBuilder creates a request builder for CreateCampus.
func NewCreateCampusReqBuilder() *CreateCampusReqBuilder {
	return &CreateCampusReqBuilder{req: &CreateCampusReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *CreateCampusReqBuilder) Body(body *models.CreateCampusRequestBody) *CreateCampusReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *CreateCampusReqBuilder) Build() *CreateCampusReq { return b.req }

// CreateCampusResp is the response for CreateCampus.
type CreateCampusResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.AdminCampusInfo `json:"data"`
}

// CreateCampus: 新建校区
func (s *Service) CreateCampus(ctx context.Context, req *CreateCampusReq, opts ...core.RequestOption) (*CreateCampusResp, error) {
	resp := &CreateCampusResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/campuses",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// UpdateCampusReq is the request for UpdateCampus.
type UpdateCampusReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// UpdateCampusReqBuilder builds a UpdateCampusReq with a fluent setter per field.
type UpdateCampusReqBuilder struct{ req *UpdateCampusReq }

// NewUpdateCampusReqBuilder creates a request builder for UpdateCampus.
func NewUpdateCampusReqBuilder() *UpdateCampusReqBuilder {
	return &UpdateCampusReqBuilder{req: &UpdateCampusReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *UpdateCampusReqBuilder) Body(body *models.UpdateCampusRequestBody) *UpdateCampusReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *UpdateCampusReqBuilder) Build() *UpdateCampusReq { return b.req }

// UpdateCampusResp is the response for UpdateCampus.
type UpdateCampusResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.AdminCampusInfo `json:"data"`
}

// UpdateCampus: 编辑校区
func (s *Service) UpdateCampus(ctx context.Context, req *UpdateCampusReq, opts ...core.RequestOption) (*UpdateCampusResp, error) {
	resp := &UpdateCampusResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/campuses",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// DeleteCampusReq is the request for DeleteCampus.
type DeleteCampusReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// DeleteCampusReqBuilder builds a DeleteCampusReq with a fluent setter per field.
type DeleteCampusReqBuilder struct{ req *DeleteCampusReq }

// NewDeleteCampusReqBuilder creates a request builder for DeleteCampus.
func NewDeleteCampusReqBuilder() *DeleteCampusReqBuilder {
	return &DeleteCampusReqBuilder{req: &DeleteCampusReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *DeleteCampusReqBuilder) Build() *DeleteCampusReq { return b.req }

// DeleteCampusResp is the response for DeleteCampus.
type DeleteCampusResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// DeleteCampus: 删除校区
func (s *Service) DeleteCampus(ctx context.Context, req *DeleteCampusReq, opts ...core.RequestOption) (*DeleteCampusResp, error) {
	resp := &DeleteCampusResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "DELETE",
		PathTemplate: "/hduhelp-neo/admin/campuses",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// GetConfigReq is the request for GetConfig.
type GetConfigReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// GetConfigReqBuilder builds a GetConfigReq with a fluent setter per field.
type GetConfigReqBuilder struct{ req *GetConfigReq }

// NewGetConfigReqBuilder creates a request builder for GetConfig.
func NewGetConfigReqBuilder() *GetConfigReqBuilder {
	return &GetConfigReqBuilder{req: &GetConfigReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Key sets the "key" query parameter.
func (b *GetConfigReqBuilder) Key(v string) *GetConfigReqBuilder {
	b.req.queryParams["key"] = v
	return b
}

// Build finalizes the request.
func (b *GetConfigReqBuilder) Build() *GetConfigReq { return b.req }

// GetConfigResp is the response for GetConfig.
type GetConfigResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.ConfigItem `json:"data"`
}

// GetConfig: 获取单项系统配置
func (s *Service) GetConfig(ctx context.Context, req *GetConfigReq, opts ...core.RequestOption) (*GetConfigResp, error) {
	resp := &GetConfigResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/config",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// GetCaiyunConfigReq is the request for GetCaiyunConfig.
type GetCaiyunConfigReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// GetCaiyunConfigReqBuilder builds a GetCaiyunConfigReq with a fluent setter per field.
type GetCaiyunConfigReqBuilder struct{ req *GetCaiyunConfigReq }

// NewGetCaiyunConfigReqBuilder creates a request builder for GetCaiyunConfig.
func NewGetCaiyunConfigReqBuilder() *GetCaiyunConfigReqBuilder {
	return &GetCaiyunConfigReqBuilder{req: &GetCaiyunConfigReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *GetCaiyunConfigReqBuilder) Build() *GetCaiyunConfigReq { return b.req }

// GetCaiyunConfigResp is the response for GetCaiyunConfig.
type GetCaiyunConfigResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.CaiyunConfigData `json:"data"`
}

// GetCaiyunConfig: 获取彩云天气配置
func (s *Service) GetCaiyunConfig(ctx context.Context, req *GetCaiyunConfigReq, opts ...core.RequestOption) (*GetCaiyunConfigResp, error) {
	resp := &GetCaiyunConfigResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/config/caiyun",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// SetCaiyunConfigReq is the request for SetCaiyunConfig.
type SetCaiyunConfigReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// SetCaiyunConfigReqBuilder builds a SetCaiyunConfigReq with a fluent setter per field.
type SetCaiyunConfigReqBuilder struct{ req *SetCaiyunConfigReq }

// NewSetCaiyunConfigReqBuilder creates a request builder for SetCaiyunConfig.
func NewSetCaiyunConfigReqBuilder() *SetCaiyunConfigReqBuilder {
	return &SetCaiyunConfigReqBuilder{req: &SetCaiyunConfigReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *SetCaiyunConfigReqBuilder) Body(body *models.SetCaiyunConfigRequestBody) *SetCaiyunConfigReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *SetCaiyunConfigReqBuilder) Build() *SetCaiyunConfigReq { return b.req }

// SetCaiyunConfigResp is the response for SetCaiyunConfig.
type SetCaiyunConfigResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// SetCaiyunConfig: 设置彩云天气配置
func (s *Service) SetCaiyunConfig(ctx context.Context, req *SetCaiyunConfigReq, opts ...core.RequestOption) (*SetCaiyunConfigResp, error) {
	resp := &SetCaiyunConfigResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/config/caiyun",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListConfigsReq is the request for ListConfigs.
type ListConfigsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListConfigsReqBuilder builds a ListConfigsReq with a fluent setter per field.
type ListConfigsReqBuilder struct{ req *ListConfigsReq }

// NewListConfigsReqBuilder creates a request builder for ListConfigs.
func NewListConfigsReqBuilder() *ListConfigsReqBuilder {
	return &ListConfigsReqBuilder{req: &ListConfigsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Group sets the "group" query parameter.
func (b *ListConfigsReqBuilder) Group(v string) *ListConfigsReqBuilder {
	b.req.queryParams["group"] = v
	return b
}

// Build finalizes the request.
func (b *ListConfigsReqBuilder) Build() *ListConfigsReq { return b.req }

// ListConfigsResp is the response for ListConfigs.
type ListConfigsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.ConfigItem `json:"data"`
}

// ListConfigs: 系统配置列表
func (s *Service) ListConfigs(ctx context.Context, req *ListConfigsReq, opts ...core.RequestOption) (*ListConfigsResp, error) {
	resp := &ListConfigsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/configs",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// SetConfigReq is the request for SetConfig.
type SetConfigReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// SetConfigReqBuilder builds a SetConfigReq with a fluent setter per field.
type SetConfigReqBuilder struct{ req *SetConfigReq }

// NewSetConfigReqBuilder creates a request builder for SetConfig.
func NewSetConfigReqBuilder() *SetConfigReqBuilder {
	return &SetConfigReqBuilder{req: &SetConfigReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *SetConfigReqBuilder) Body(body *models.SetConfigRequestBody) *SetConfigReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *SetConfigReqBuilder) Build() *SetConfigReq { return b.req }

// SetConfigResp is the response for SetConfig.
type SetConfigResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// SetConfig: 设置系统配置
func (s *Service) SetConfig(ctx context.Context, req *SetConfigReq, opts ...core.RequestOption) (*SetConfigResp, error) {
	resp := &SetConfigResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/configs",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// TestConnectionReq is the request for TestConnection.
type TestConnectionReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// TestConnectionReqBuilder builds a TestConnectionReq with a fluent setter per field.
type TestConnectionReqBuilder struct{ req *TestConnectionReq }

// NewTestConnectionReqBuilder creates a request builder for TestConnection.
func NewTestConnectionReqBuilder() *TestConnectionReqBuilder {
	return &TestConnectionReqBuilder{req: &TestConnectionReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *TestConnectionReqBuilder) Body(body *models.TestConnectionRequestBody) *TestConnectionReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *TestConnectionReqBuilder) Build() *TestConnectionReq { return b.req }

// TestConnectionResp is the response for TestConnection.
type TestConnectionResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// TestConnection: 测试配置连通性
func (s *Service) TestConnection(ctx context.Context, req *TestConnectionReq, opts ...core.RequestOption) (*TestConnectionResp, error) {
	resp := &TestConnectionResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/configs/test",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListCronTasksReq is the request for ListCronTasks.
type ListCronTasksReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListCronTasksReqBuilder builds a ListCronTasksReq with a fluent setter per field.
type ListCronTasksReqBuilder struct{ req *ListCronTasksReq }

// NewListCronTasksReqBuilder creates a request builder for ListCronTasks.
func NewListCronTasksReqBuilder() *ListCronTasksReqBuilder {
	return &ListCronTasksReqBuilder{req: &ListCronTasksReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *ListCronTasksReqBuilder) Build() *ListCronTasksReq { return b.req }

// ListCronTasksResp is the response for ListCronTasks.
type ListCronTasksResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.CronTaskInfo `json:"data"`
}

// ListCronTasks: 定时任务列表
func (s *Service) ListCronTasks(ctx context.Context, req *ListCronTasksReq, opts ...core.RequestOption) (*ListCronTasksResp, error) {
	resp := &ListCronTasksResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/cron",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// UpdateCronTaskReq is the request for UpdateCronTask.
type UpdateCronTaskReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// UpdateCronTaskReqBuilder builds a UpdateCronTaskReq with a fluent setter per field.
type UpdateCronTaskReqBuilder struct{ req *UpdateCronTaskReq }

// NewUpdateCronTaskReqBuilder creates a request builder for UpdateCronTask.
func NewUpdateCronTaskReqBuilder() *UpdateCronTaskReqBuilder {
	return &UpdateCronTaskReqBuilder{req: &UpdateCronTaskReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *UpdateCronTaskReqBuilder) Body(body *models.UpdateCronTaskRequestBody) *UpdateCronTaskReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *UpdateCronTaskReqBuilder) Build() *UpdateCronTaskReq { return b.req }

// UpdateCronTaskResp is the response for UpdateCronTask.
type UpdateCronTaskResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// UpdateCronTask: 更新定时任务
func (s *Service) UpdateCronTask(ctx context.Context, req *UpdateCronTaskReq, opts ...core.RequestOption) (*UpdateCronTaskResp, error) {
	resp := &UpdateCronTaskResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/cron",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// RunCronTaskReq is the request for RunCronTask.
type RunCronTaskReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// RunCronTaskReqBuilder builds a RunCronTaskReq with a fluent setter per field.
type RunCronTaskReqBuilder struct{ req *RunCronTaskReq }

// NewRunCronTaskReqBuilder creates a request builder for RunCronTask.
func NewRunCronTaskReqBuilder() *RunCronTaskReqBuilder {
	return &RunCronTaskReqBuilder{req: &RunCronTaskReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *RunCronTaskReqBuilder) Body(body *models.RunCronTaskRequestBody) *RunCronTaskReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *RunCronTaskReqBuilder) Build() *RunCronTaskReq { return b.req }

// RunCronTaskResp is the response for RunCronTask.
type RunCronTaskResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// RunCronTask: 立即执行定时任务
func (s *Service) RunCronTask(ctx context.Context, req *RunCronTaskReq, opts ...core.RequestOption) (*RunCronTaskResp, error) {
	resp := &RunCronTaskResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/cron/run",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListElectricityMetersReq is the request for ListElectricityMeters.
type ListElectricityMetersReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListElectricityMetersReqBuilder builds a ListElectricityMetersReq with a fluent setter per field.
type ListElectricityMetersReqBuilder struct{ req *ListElectricityMetersReq }

// NewListElectricityMetersReqBuilder creates a request builder for ListElectricityMeters.
func NewListElectricityMetersReqBuilder() *ListElectricityMetersReqBuilder {
	return &ListElectricityMetersReqBuilder{req: &ListElectricityMetersReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Keyword sets the "keyword" query parameter.
func (b *ListElectricityMetersReqBuilder) Keyword(v string) *ListElectricityMetersReqBuilder {
	b.req.queryParams["keyword"] = v
	return b
}

// BuildingId sets the "building_id" query parameter.
func (b *ListElectricityMetersReqBuilder) BuildingId(v int64) *ListElectricityMetersReqBuilder {
	b.req.queryParams["building_id"] = strconv.FormatInt(v, 10)
	return b
}

// FloorId sets the "floor_id" query parameter.
func (b *ListElectricityMetersReqBuilder) FloorId(v int64) *ListElectricityMetersReqBuilder {
	b.req.queryParams["floor_id"] = strconv.FormatInt(v, 10)
	return b
}

// Page sets the "page" query parameter.
func (b *ListElectricityMetersReqBuilder) Page(v int32) *ListElectricityMetersReqBuilder {
	b.req.queryParams["page"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Size sets the "size" query parameter.
func (b *ListElectricityMetersReqBuilder) Size(v int32) *ListElectricityMetersReqBuilder {
	b.req.queryParams["size"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Build finalizes the request.
func (b *ListElectricityMetersReqBuilder) Build() *ListElectricityMetersReq { return b.req }

// ListElectricityMetersResp is the response for ListElectricityMeters.
type ListElectricityMetersResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.ElectricityMeterPage `json:"data"`
}

// ListElectricityMeters: 电表主数据列表
func (s *Service) ListElectricityMeters(ctx context.Context, req *ListElectricityMetersReq, opts ...core.RequestOption) (*ListElectricityMetersResp, error) {
	resp := &ListElectricityMetersResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/electricity/meters",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// CreateElectricityMeterReq is the request for CreateElectricityMeter.
type CreateElectricityMeterReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// CreateElectricityMeterReqBuilder builds a CreateElectricityMeterReq with a fluent setter per field.
type CreateElectricityMeterReqBuilder struct{ req *CreateElectricityMeterReq }

// NewCreateElectricityMeterReqBuilder creates a request builder for CreateElectricityMeter.
func NewCreateElectricityMeterReqBuilder() *CreateElectricityMeterReqBuilder {
	return &CreateElectricityMeterReqBuilder{req: &CreateElectricityMeterReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *CreateElectricityMeterReqBuilder) Body(body *models.CreateElectricityMeterRequestBody) *CreateElectricityMeterReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *CreateElectricityMeterReqBuilder) Build() *CreateElectricityMeterReq { return b.req }

// CreateElectricityMeterResp is the response for CreateElectricityMeter.
type CreateElectricityMeterResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.AdminElectricityMeter `json:"data"`
}

// CreateElectricityMeter: 新增电表主数据
func (s *Service) CreateElectricityMeter(ctx context.Context, req *CreateElectricityMeterReq, opts ...core.RequestOption) (*CreateElectricityMeterResp, error) {
	resp := &CreateElectricityMeterResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/electricity/meters",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// UpdateElectricityMeterReq is the request for UpdateElectricityMeter.
type UpdateElectricityMeterReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// UpdateElectricityMeterReqBuilder builds a UpdateElectricityMeterReq with a fluent setter per field.
type UpdateElectricityMeterReqBuilder struct{ req *UpdateElectricityMeterReq }

// NewUpdateElectricityMeterReqBuilder creates a request builder for UpdateElectricityMeter.
func NewUpdateElectricityMeterReqBuilder() *UpdateElectricityMeterReqBuilder {
	return &UpdateElectricityMeterReqBuilder{req: &UpdateElectricityMeterReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *UpdateElectricityMeterReqBuilder) Id(v string) *UpdateElectricityMeterReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Body sets the request body.
func (b *UpdateElectricityMeterReqBuilder) Body(body *models.UpdateElectricityMeterRequestBody) *UpdateElectricityMeterReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *UpdateElectricityMeterReqBuilder) Build() *UpdateElectricityMeterReq { return b.req }

// UpdateElectricityMeterResp is the response for UpdateElectricityMeter.
type UpdateElectricityMeterResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.AdminElectricityMeter `json:"data"`
}

// UpdateElectricityMeter: 编辑电表主数据
func (s *Service) UpdateElectricityMeter(ctx context.Context, req *UpdateElectricityMeterReq, opts ...core.RequestOption) (*UpdateElectricityMeterResp, error) {
	resp := &UpdateElectricityMeterResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/electricity/meters/{id}",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// DeleteElectricityMeterReq is the request for DeleteElectricityMeter.
type DeleteElectricityMeterReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// DeleteElectricityMeterReqBuilder builds a DeleteElectricityMeterReq with a fluent setter per field.
type DeleteElectricityMeterReqBuilder struct{ req *DeleteElectricityMeterReq }

// NewDeleteElectricityMeterReqBuilder creates a request builder for DeleteElectricityMeter.
func NewDeleteElectricityMeterReqBuilder() *DeleteElectricityMeterReqBuilder {
	return &DeleteElectricityMeterReqBuilder{req: &DeleteElectricityMeterReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" path parameter.
func (b *DeleteElectricityMeterReqBuilder) Id(v string) *DeleteElectricityMeterReqBuilder {
	b.req.pathParams["id"] = v
	return b
}

// Build finalizes the request.
func (b *DeleteElectricityMeterReqBuilder) Build() *DeleteElectricityMeterReq { return b.req }

// DeleteElectricityMeterResp is the response for DeleteElectricityMeter.
type DeleteElectricityMeterResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// DeleteElectricityMeter: 删除电表主数据
func (s *Service) DeleteElectricityMeter(ctx context.Context, req *DeleteElectricityMeterReq, opts ...core.RequestOption) (*DeleteElectricityMeterResp, error) {
	resp := &DeleteElectricityMeterResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "DELETE",
		PathTemplate: "/hduhelp-neo/admin/electricity/meters/{id}",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminLoginReq is the request for AdminLogin.
type AdminLoginReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminLoginReqBuilder builds a AdminLoginReq with a fluent setter per field.
type AdminLoginReqBuilder struct{ req *AdminLoginReq }

// NewAdminLoginReqBuilder creates a request builder for AdminLogin.
func NewAdminLoginReqBuilder() *AdminLoginReqBuilder {
	return &AdminLoginReqBuilder{req: &AdminLoginReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *AdminLoginReqBuilder) Body(body *models.AdminLoginRequestBody) *AdminLoginReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *AdminLoginReqBuilder) Build() *AdminLoginReq { return b.req }

// AdminLoginResp is the response for AdminLogin.
type AdminLoginResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.AdminLoginData `json:"data"`
}

// AdminLogin: 运营者登录
func (s *Service) AdminLogin(ctx context.Context, req *AdminLoginReq, opts ...core.RequestOption) (*AdminLoginResp, error) {
	resp := &AdminLoginResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/login",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListLoginClientsReq is the request for ListLoginClients.
type ListLoginClientsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListLoginClientsReqBuilder builds a ListLoginClientsReq with a fluent setter per field.
type ListLoginClientsReqBuilder struct{ req *ListLoginClientsReq }

// NewListLoginClientsReqBuilder creates a request builder for ListLoginClients.
func NewListLoginClientsReqBuilder() *ListLoginClientsReqBuilder {
	return &ListLoginClientsReqBuilder{req: &ListLoginClientsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *ListLoginClientsReqBuilder) Build() *ListLoginClientsReq { return b.req }

// ListLoginClientsResp is the response for ListLoginClients.
type ListLoginClientsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.AdminLoginClientInfo `json:"data"`
}

// ListLoginClients: 登录客户端列表
func (s *Service) ListLoginClients(ctx context.Context, req *ListLoginClientsReq, opts ...core.RequestOption) (*ListLoginClientsResp, error) {
	resp := &ListLoginClientsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/login-clients",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// CreateLoginClientReq is the request for CreateLoginClient.
type CreateLoginClientReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// CreateLoginClientReqBuilder builds a CreateLoginClientReq with a fluent setter per field.
type CreateLoginClientReqBuilder struct{ req *CreateLoginClientReq }

// NewCreateLoginClientReqBuilder creates a request builder for CreateLoginClient.
func NewCreateLoginClientReqBuilder() *CreateLoginClientReqBuilder {
	return &CreateLoginClientReqBuilder{req: &CreateLoginClientReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *CreateLoginClientReqBuilder) Body(body *models.CreateLoginClientRequestBody) *CreateLoginClientReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *CreateLoginClientReqBuilder) Build() *CreateLoginClientReq { return b.req }

// CreateLoginClientResp is the response for CreateLoginClient.
type CreateLoginClientResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.AdminLoginClientInfo `json:"data"`
}

// CreateLoginClient: 创建登录客户端
func (s *Service) CreateLoginClient(ctx context.Context, req *CreateLoginClientReq, opts ...core.RequestOption) (*CreateLoginClientResp, error) {
	resp := &CreateLoginClientResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/login-clients",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// UpdateLoginClientReq is the request for UpdateLoginClient.
type UpdateLoginClientReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// UpdateLoginClientReqBuilder builds a UpdateLoginClientReq with a fluent setter per field.
type UpdateLoginClientReqBuilder struct{ req *UpdateLoginClientReq }

// NewUpdateLoginClientReqBuilder creates a request builder for UpdateLoginClient.
func NewUpdateLoginClientReqBuilder() *UpdateLoginClientReqBuilder {
	return &UpdateLoginClientReqBuilder{req: &UpdateLoginClientReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *UpdateLoginClientReqBuilder) Body(body *models.UpdateLoginClientRequestBody) *UpdateLoginClientReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *UpdateLoginClientReqBuilder) Build() *UpdateLoginClientReq { return b.req }

// UpdateLoginClientResp is the response for UpdateLoginClient.
type UpdateLoginClientResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.AdminLoginClientInfo `json:"data"`
}

// UpdateLoginClient: 编辑登录客户端
func (s *Service) UpdateLoginClient(ctx context.Context, req *UpdateLoginClientReq, opts ...core.RequestOption) (*UpdateLoginClientResp, error) {
	resp := &UpdateLoginClientResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/login-clients",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// DeleteLoginClientReq is the request for DeleteLoginClient.
type DeleteLoginClientReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// DeleteLoginClientReqBuilder builds a DeleteLoginClientReq with a fluent setter per field.
type DeleteLoginClientReqBuilder struct{ req *DeleteLoginClientReq }

// NewDeleteLoginClientReqBuilder creates a request builder for DeleteLoginClient.
func NewDeleteLoginClientReqBuilder() *DeleteLoginClientReqBuilder {
	return &DeleteLoginClientReqBuilder{req: &DeleteLoginClientReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" query parameter.
func (b *DeleteLoginClientReqBuilder) Id(v string) *DeleteLoginClientReqBuilder {
	b.req.queryParams["id"] = v
	return b
}

// Build finalizes the request.
func (b *DeleteLoginClientReqBuilder) Build() *DeleteLoginClientReq { return b.req }

// DeleteLoginClientResp is the response for DeleteLoginClient.
type DeleteLoginClientResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// DeleteLoginClient: 删除登录客户端
func (s *Service) DeleteLoginClient(ctx context.Context, req *DeleteLoginClientReq, opts ...core.RequestOption) (*DeleteLoginClientResp, error) {
	resp := &DeleteLoginClientResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "DELETE",
		PathTemplate: "/hduhelp-neo/admin/login-clients",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// GetLoginClientReq is the request for GetLoginClient.
type GetLoginClientReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// GetLoginClientReqBuilder builds a GetLoginClientReq with a fluent setter per field.
type GetLoginClientReqBuilder struct{ req *GetLoginClientReq }

// NewGetLoginClientReqBuilder creates a request builder for GetLoginClient.
func NewGetLoginClientReqBuilder() *GetLoginClientReqBuilder {
	return &GetLoginClientReqBuilder{req: &GetLoginClientReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Id sets the "id" query parameter.
func (b *GetLoginClientReqBuilder) Id(v string) *GetLoginClientReqBuilder {
	b.req.queryParams["id"] = v
	return b
}

// Build finalizes the request.
func (b *GetLoginClientReqBuilder) Build() *GetLoginClientReq { return b.req }

// GetLoginClientResp is the response for GetLoginClient.
type GetLoginClientResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.AdminLoginClientInfo `json:"data"`
}

// GetLoginClient: 登录客户端详情
func (s *Service) GetLoginClient(ctx context.Context, req *GetLoginClientReq, opts ...core.RequestOption) (*GetLoginClientResp, error) {
	resp := &GetLoginClientResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/login-clients/get",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListLoginMethodsReq is the request for ListLoginMethods.
type ListLoginMethodsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListLoginMethodsReqBuilder builds a ListLoginMethodsReq with a fluent setter per field.
type ListLoginMethodsReqBuilder struct{ req *ListLoginMethodsReq }

// NewListLoginMethodsReqBuilder creates a request builder for ListLoginMethods.
func NewListLoginMethodsReqBuilder() *ListLoginMethodsReqBuilder {
	return &ListLoginMethodsReqBuilder{req: &ListLoginMethodsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *ListLoginMethodsReqBuilder) Build() *ListLoginMethodsReq { return b.req }

// ListLoginMethodsResp is the response for ListLoginMethods.
type ListLoginMethodsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.LoginMethodItem `json:"data"`
}

// ListLoginMethods: 登录方式列表
func (s *Service) ListLoginMethods(ctx context.Context, req *ListLoginMethodsReq, opts ...core.RequestOption) (*ListLoginMethodsResp, error) {
	resp := &ListLoginMethodsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/login-methods",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// SetLoginMethodsReq is the request for SetLoginMethods.
type SetLoginMethodsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// SetLoginMethodsReqBuilder builds a SetLoginMethodsReq with a fluent setter per field.
type SetLoginMethodsReqBuilder struct{ req *SetLoginMethodsReq }

// NewSetLoginMethodsReqBuilder creates a request builder for SetLoginMethods.
func NewSetLoginMethodsReqBuilder() *SetLoginMethodsReqBuilder {
	return &SetLoginMethodsReqBuilder{req: &SetLoginMethodsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *SetLoginMethodsReqBuilder) Body(body *models.SetLoginMethodsRequestBody) *SetLoginMethodsReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *SetLoginMethodsReqBuilder) Build() *SetLoginMethodsReq { return b.req }

// SetLoginMethodsResp is the response for SetLoginMethods.
type SetLoginMethodsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// SetLoginMethods: 设置登录方式启用状态
func (s *Service) SetLoginMethods(ctx context.Context, req *SetLoginMethodsReq, opts ...core.RequestOption) (*SetLoginMethodsResp, error) {
	resp := &SetLoginMethodsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/login-methods",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminLogoutReq is the request for AdminLogout.
type AdminLogoutReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminLogoutReqBuilder builds a AdminLogoutReq with a fluent setter per field.
type AdminLogoutReqBuilder struct{ req *AdminLogoutReq }

// NewAdminLogoutReqBuilder creates a request builder for AdminLogout.
func NewAdminLogoutReqBuilder() *AdminLogoutReqBuilder {
	return &AdminLogoutReqBuilder{req: &AdminLogoutReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *AdminLogoutReqBuilder) Build() *AdminLogoutReq { return b.req }

// AdminLogoutResp is the response for AdminLogout.
type AdminLogoutResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// AdminLogout: 运营者登出
func (s *Service) AdminLogout(ctx context.Context, req *AdminLogoutReq, opts ...core.RequestOption) (*AdminLogoutResp, error) {
	resp := &AdminLogoutResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/logout",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListOperatorsReq is the request for ListOperators.
type ListOperatorsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListOperatorsReqBuilder builds a ListOperatorsReq with a fluent setter per field.
type ListOperatorsReqBuilder struct{ req *ListOperatorsReq }

// NewListOperatorsReqBuilder creates a request builder for ListOperators.
func NewListOperatorsReqBuilder() *ListOperatorsReqBuilder {
	return &ListOperatorsReqBuilder{req: &ListOperatorsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *ListOperatorsReqBuilder) Build() *ListOperatorsReq { return b.req }

// ListOperatorsResp is the response for ListOperators.
type ListOperatorsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.OperatorInfo `json:"data"`
}

// ListOperators: 运营者列表
func (s *Service) ListOperators(ctx context.Context, req *ListOperatorsReq, opts ...core.RequestOption) (*ListOperatorsResp, error) {
	resp := &ListOperatorsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/operators",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// CreateOperatorReq is the request for CreateOperator.
type CreateOperatorReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// CreateOperatorReqBuilder builds a CreateOperatorReq with a fluent setter per field.
type CreateOperatorReqBuilder struct{ req *CreateOperatorReq }

// NewCreateOperatorReqBuilder creates a request builder for CreateOperator.
func NewCreateOperatorReqBuilder() *CreateOperatorReqBuilder {
	return &CreateOperatorReqBuilder{req: &CreateOperatorReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *CreateOperatorReqBuilder) Body(body *models.CreateOperatorRequestBody) *CreateOperatorReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *CreateOperatorReqBuilder) Build() *CreateOperatorReq { return b.req }

// CreateOperatorResp is the response for CreateOperator.
type CreateOperatorResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.OperatorInfo `json:"data"`
}

// CreateOperator: 创建运营者
func (s *Service) CreateOperator(ctx context.Context, req *CreateOperatorReq, opts ...core.RequestOption) (*CreateOperatorResp, error) {
	resp := &CreateOperatorResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/operators",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// DisableOperatorReq is the request for DisableOperator.
type DisableOperatorReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// DisableOperatorReqBuilder builds a DisableOperatorReq with a fluent setter per field.
type DisableOperatorReqBuilder struct{ req *DisableOperatorReq }

// NewDisableOperatorReqBuilder creates a request builder for DisableOperator.
func NewDisableOperatorReqBuilder() *DisableOperatorReqBuilder {
	return &DisableOperatorReqBuilder{req: &DisableOperatorReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *DisableOperatorReqBuilder) Body(body *models.DisableOperatorRequestBody) *DisableOperatorReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *DisableOperatorReqBuilder) Build() *DisableOperatorReq { return b.req }

// DisableOperatorResp is the response for DisableOperator.
type DisableOperatorResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// DisableOperator: 停用运营者
func (s *Service) DisableOperator(ctx context.Context, req *DisableOperatorReq, opts ...core.RequestOption) (*DisableOperatorResp, error) {
	resp := &DisableOperatorResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/operators/disable",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// EnableOperatorReq is the request for EnableOperator.
type EnableOperatorReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// EnableOperatorReqBuilder builds a EnableOperatorReq with a fluent setter per field.
type EnableOperatorReqBuilder struct{ req *EnableOperatorReq }

// NewEnableOperatorReqBuilder creates a request builder for EnableOperator.
func NewEnableOperatorReqBuilder() *EnableOperatorReqBuilder {
	return &EnableOperatorReqBuilder{req: &EnableOperatorReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *EnableOperatorReqBuilder) Body(body *models.EnableOperatorRequestBody) *EnableOperatorReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *EnableOperatorReqBuilder) Build() *EnableOperatorReq { return b.req }

// EnableOperatorResp is the response for EnableOperator.
type EnableOperatorResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// EnableOperator: 启用运营者
func (s *Service) EnableOperator(ctx context.Context, req *EnableOperatorReq, opts ...core.RequestOption) (*EnableOperatorResp, error) {
	resp := &EnableOperatorResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/operators/enable",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ResetOperatorPasswordReq is the request for ResetOperatorPassword.
type ResetOperatorPasswordReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ResetOperatorPasswordReqBuilder builds a ResetOperatorPasswordReq with a fluent setter per field.
type ResetOperatorPasswordReqBuilder struct{ req *ResetOperatorPasswordReq }

// NewResetOperatorPasswordReqBuilder creates a request builder for ResetOperatorPassword.
func NewResetOperatorPasswordReqBuilder() *ResetOperatorPasswordReqBuilder {
	return &ResetOperatorPasswordReqBuilder{req: &ResetOperatorPasswordReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *ResetOperatorPasswordReqBuilder) Body(body *models.ResetOperatorPasswordRequestBody) *ResetOperatorPasswordReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *ResetOperatorPasswordReqBuilder) Build() *ResetOperatorPasswordReq { return b.req }

// ResetOperatorPasswordResp is the response for ResetOperatorPassword.
type ResetOperatorPasswordResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// ResetOperatorPassword: 重置运营者口令
func (s *Service) ResetOperatorPassword(ctx context.Context, req *ResetOperatorPasswordReq, opts ...core.RequestOption) (*ResetOperatorPasswordResp, error) {
	resp := &ResetOperatorPasswordResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/operators/password/reset",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// AdminRefreshReq is the request for AdminRefresh.
type AdminRefreshReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// AdminRefreshReqBuilder builds a AdminRefreshReq with a fluent setter per field.
type AdminRefreshReqBuilder struct{ req *AdminRefreshReq }

// NewAdminRefreshReqBuilder creates a request builder for AdminRefresh.
func NewAdminRefreshReqBuilder() *AdminRefreshReqBuilder {
	return &AdminRefreshReqBuilder{req: &AdminRefreshReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *AdminRefreshReqBuilder) Body(body *models.AdminRefreshRequestBody) *AdminRefreshReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *AdminRefreshReqBuilder) Build() *AdminRefreshReq { return b.req }

// AdminRefreshResp is the response for AdminRefresh.
type AdminRefreshResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.AdminLoginData `json:"data"`
}

// AdminRefresh: 刷新运营者令牌
func (s *Service) AdminRefresh(ctx context.Context, req *AdminRefreshReq, opts ...core.RequestOption) (*AdminRefreshResp, error) {
	resp := &AdminRefreshResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/refresh",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListScopesReq is the request for ListScopes.
type ListScopesReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListScopesReqBuilder builds a ListScopesReq with a fluent setter per field.
type ListScopesReqBuilder struct{ req *ListScopesReq }

// NewListScopesReqBuilder creates a request builder for ListScopes.
func NewListScopesReqBuilder() *ListScopesReqBuilder {
	return &ListScopesReqBuilder{req: &ListScopesReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *ListScopesReqBuilder) Build() *ListScopesReq { return b.req }

// ListScopesResp is the response for ListScopes.
type ListScopesResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.AdminScopeDef `json:"data"`
}

// ListScopes: scope能力目录
func (s *Service) ListScopes(ctx context.Context, req *ListScopesReq, opts ...core.RequestOption) (*ListScopesResp, error) {
	resp := &ListScopesResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/scopes",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// ListTenantsReq is the request for ListTenants.
type ListTenantsReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// ListTenantsReqBuilder builds a ListTenantsReq with a fluent setter per field.
type ListTenantsReqBuilder struct{ req *ListTenantsReq }

// NewListTenantsReqBuilder creates a request builder for ListTenants.
func NewListTenantsReqBuilder() *ListTenantsReqBuilder {
	return &ListTenantsReqBuilder{req: &ListTenantsReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Build finalizes the request.
func (b *ListTenantsReqBuilder) Build() *ListTenantsReq { return b.req }

// ListTenantsResp is the response for ListTenants.
type ListTenantsResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.AdminTenantInfo `json:"data"`
}

// ListTenants: 租户列表
func (s *Service) ListTenants(ctx context.Context, req *ListTenantsReq, opts ...core.RequestOption) (*ListTenantsResp, error) {
	resp := &ListTenantsResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/tenants",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// CreateTenantReq is the request for CreateTenant.
type CreateTenantReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// CreateTenantReqBuilder builds a CreateTenantReq with a fluent setter per field.
type CreateTenantReqBuilder struct{ req *CreateTenantReq }

// NewCreateTenantReqBuilder creates a request builder for CreateTenant.
func NewCreateTenantReqBuilder() *CreateTenantReqBuilder {
	return &CreateTenantReqBuilder{req: &CreateTenantReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *CreateTenantReqBuilder) Body(body *models.CreateTenantRequestBody) *CreateTenantReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *CreateTenantReqBuilder) Build() *CreateTenantReq { return b.req }

// CreateTenantResp is the response for CreateTenant.
type CreateTenantResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.AdminTenantInfo `json:"data"`
}

// CreateTenant: 创建租户
func (s *Service) CreateTenant(ctx context.Context, req *CreateTenantReq, opts ...core.RequestOption) (*CreateTenantResp, error) {
	resp := &CreateTenantResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "POST",
		PathTemplate: "/hduhelp-neo/admin/tenants",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// DisableTenantReq is the request for DisableTenant.
type DisableTenantReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// DisableTenantReqBuilder builds a DisableTenantReq with a fluent setter per field.
type DisableTenantReqBuilder struct{ req *DisableTenantReq }

// NewDisableTenantReqBuilder creates a request builder for DisableTenant.
func NewDisableTenantReqBuilder() *DisableTenantReqBuilder {
	return &DisableTenantReqBuilder{req: &DisableTenantReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *DisableTenantReqBuilder) Body(body *models.DisableTenantRequestBody) *DisableTenantReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *DisableTenantReqBuilder) Build() *DisableTenantReq { return b.req }

// DisableTenantResp is the response for DisableTenant.
type DisableTenantResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// DisableTenant: 停用租户
func (s *Service) DisableTenant(ctx context.Context, req *DisableTenantReq, opts ...core.RequestOption) (*DisableTenantResp, error) {
	resp := &DisableTenantResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/tenants/disable",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// EnableTenantReq is the request for EnableTenant.
type EnableTenantReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// EnableTenantReqBuilder builds a EnableTenantReq with a fluent setter per field.
type EnableTenantReqBuilder struct{ req *EnableTenantReq }

// NewEnableTenantReqBuilder creates a request builder for EnableTenant.
func NewEnableTenantReqBuilder() *EnableTenantReqBuilder {
	return &EnableTenantReqBuilder{req: &EnableTenantReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *EnableTenantReqBuilder) Body(body *models.EnableTenantRequestBody) *EnableTenantReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *EnableTenantReqBuilder) Build() *EnableTenantReq { return b.req }

// EnableTenantResp is the response for EnableTenant.
type EnableTenantResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// EnableTenant: 启用租户
func (s *Service) EnableTenant(ctx context.Context, req *EnableTenantReq, opts ...core.RequestOption) (*EnableTenantResp, error) {
	resp := &EnableTenantResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/tenants/enable",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// SearchUsersReq is the request for SearchUsers.
type SearchUsersReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// SearchUsersReqBuilder builds a SearchUsersReq with a fluent setter per field.
type SearchUsersReqBuilder struct{ req *SearchUsersReq }

// NewSearchUsersReqBuilder creates a request builder for SearchUsers.
func NewSearchUsersReqBuilder() *SearchUsersReqBuilder {
	return &SearchUsersReqBuilder{req: &SearchUsersReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Keyword sets the "keyword" query parameter.
func (b *SearchUsersReqBuilder) Keyword(v string) *SearchUsersReqBuilder {
	b.req.queryParams["keyword"] = v
	return b
}

// Status sets the "status" query parameter.
func (b *SearchUsersReqBuilder) Status(v string) *SearchUsersReqBuilder {
	b.req.queryParams["status"] = v
	return b
}

// Page sets the "page" query parameter.
func (b *SearchUsersReqBuilder) Page(v int32) *SearchUsersReqBuilder {
	b.req.queryParams["page"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Size sets the "size" query parameter.
func (b *SearchUsersReqBuilder) Size(v int32) *SearchUsersReqBuilder {
	b.req.queryParams["size"] = strconv.FormatInt(int64(v), 10)
	return b
}

// Build finalizes the request.
func (b *SearchUsersReqBuilder) Build() *SearchUsersReq { return b.req }

// SearchUsersResp is the response for SearchUsers.
type SearchUsersResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data []models.AdminUserInfo `json:"data"`
}

// SearchUsers: 搜索用户
func (s *Service) SearchUsers(ctx context.Context, req *SearchUsersReq, opts ...core.RequestOption) (*SearchUsersResp, error) {
	resp := &SearchUsersResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/users",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// BanUserReq is the request for BanUser.
type BanUserReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// BanUserReqBuilder builds a BanUserReq with a fluent setter per field.
type BanUserReqBuilder struct{ req *BanUserReq }

// NewBanUserReqBuilder creates a request builder for BanUser.
func NewBanUserReqBuilder() *BanUserReqBuilder {
	return &BanUserReqBuilder{req: &BanUserReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *BanUserReqBuilder) Body(body *models.BanUserRequestBody) *BanUserReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *BanUserReqBuilder) Build() *BanUserReq { return b.req }

// BanUserResp is the response for BanUser.
type BanUserResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// BanUser: 封禁用户
func (s *Service) BanUser(ctx context.Context, req *BanUserReq, opts ...core.RequestOption) (*BanUserResp, error) {
	resp := &BanUserResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/users/ban",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// UpsertUserCampusIdentityReq is the request for UpsertUserCampusIdentity.
type UpsertUserCampusIdentityReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// UpsertUserCampusIdentityReqBuilder builds a UpsertUserCampusIdentityReq with a fluent setter per field.
type UpsertUserCampusIdentityReqBuilder struct{ req *UpsertUserCampusIdentityReq }

// NewUpsertUserCampusIdentityReqBuilder creates a request builder for UpsertUserCampusIdentity.
func NewUpsertUserCampusIdentityReqBuilder() *UpsertUserCampusIdentityReqBuilder {
	return &UpsertUserCampusIdentityReqBuilder{req: &UpsertUserCampusIdentityReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *UpsertUserCampusIdentityReqBuilder) Body(body *models.UpsertUserCampusIdentityRequestBody) *UpsertUserCampusIdentityReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *UpsertUserCampusIdentityReqBuilder) Build() *UpsertUserCampusIdentityReq { return b.req }

// UpsertUserCampusIdentityResp is the response for UpsertUserCampusIdentity.
type UpsertUserCampusIdentityResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// UpsertUserCampusIdentity: 调整用户校园身份
func (s *Service) UpsertUserCampusIdentity(ctx context.Context, req *UpsertUserCampusIdentityReq, opts ...core.RequestOption) (*UpsertUserCampusIdentityResp, error) {
	resp := &UpsertUserCampusIdentityResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/users/bindings/campus",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// DeleteUserCampusIdentityReq is the request for DeleteUserCampusIdentity.
type DeleteUserCampusIdentityReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// DeleteUserCampusIdentityReqBuilder builds a DeleteUserCampusIdentityReq with a fluent setter per field.
type DeleteUserCampusIdentityReqBuilder struct{ req *DeleteUserCampusIdentityReq }

// NewDeleteUserCampusIdentityReqBuilder creates a request builder for DeleteUserCampusIdentity.
func NewDeleteUserCampusIdentityReqBuilder() *DeleteUserCampusIdentityReqBuilder {
	return &DeleteUserCampusIdentityReqBuilder{req: &DeleteUserCampusIdentityReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// UserId sets the "user_id" query parameter.
func (b *DeleteUserCampusIdentityReqBuilder) UserId(v string) *DeleteUserCampusIdentityReqBuilder {
	b.req.queryParams["user_id"] = v
	return b
}

// IdentityId sets the "identity_id" query parameter.
func (b *DeleteUserCampusIdentityReqBuilder) IdentityId(v string) *DeleteUserCampusIdentityReqBuilder {
	b.req.queryParams["identity_id"] = v
	return b
}

// Build finalizes the request.
func (b *DeleteUserCampusIdentityReqBuilder) Build() *DeleteUserCampusIdentityReq { return b.req }

// DeleteUserCampusIdentityResp is the response for DeleteUserCampusIdentity.
type DeleteUserCampusIdentityResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// DeleteUserCampusIdentity: 删除用户校园身份
func (s *Service) DeleteUserCampusIdentity(ctx context.Context, req *DeleteUserCampusIdentityReq, opts ...core.RequestOption) (*DeleteUserCampusIdentityResp, error) {
	resp := &DeleteUserCampusIdentityResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "DELETE",
		PathTemplate: "/hduhelp-neo/admin/users/bindings/campus",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// UpsertUserSocialIdentityReq is the request for UpsertUserSocialIdentity.
type UpsertUserSocialIdentityReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// UpsertUserSocialIdentityReqBuilder builds a UpsertUserSocialIdentityReq with a fluent setter per field.
type UpsertUserSocialIdentityReqBuilder struct{ req *UpsertUserSocialIdentityReq }

// NewUpsertUserSocialIdentityReqBuilder creates a request builder for UpsertUserSocialIdentity.
func NewUpsertUserSocialIdentityReqBuilder() *UpsertUserSocialIdentityReqBuilder {
	return &UpsertUserSocialIdentityReqBuilder{req: &UpsertUserSocialIdentityReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *UpsertUserSocialIdentityReqBuilder) Body(body *models.UpsertUserSocialIdentityRequestBody) *UpsertUserSocialIdentityReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *UpsertUserSocialIdentityReqBuilder) Build() *UpsertUserSocialIdentityReq { return b.req }

// UpsertUserSocialIdentityResp is the response for UpsertUserSocialIdentity.
type UpsertUserSocialIdentityResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// UpsertUserSocialIdentity: 调整用户第三方绑定
func (s *Service) UpsertUserSocialIdentity(ctx context.Context, req *UpsertUserSocialIdentityReq, opts ...core.RequestOption) (*UpsertUserSocialIdentityResp, error) {
	resp := &UpsertUserSocialIdentityResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/users/bindings/social",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// DeleteUserSocialIdentityReq is the request for DeleteUserSocialIdentity.
type DeleteUserSocialIdentityReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// DeleteUserSocialIdentityReqBuilder builds a DeleteUserSocialIdentityReq with a fluent setter per field.
type DeleteUserSocialIdentityReqBuilder struct{ req *DeleteUserSocialIdentityReq }

// NewDeleteUserSocialIdentityReqBuilder creates a request builder for DeleteUserSocialIdentity.
func NewDeleteUserSocialIdentityReqBuilder() *DeleteUserSocialIdentityReqBuilder {
	return &DeleteUserSocialIdentityReqBuilder{req: &DeleteUserSocialIdentityReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// UserId sets the "user_id" query parameter.
func (b *DeleteUserSocialIdentityReqBuilder) UserId(v string) *DeleteUserSocialIdentityReqBuilder {
	b.req.queryParams["user_id"] = v
	return b
}

// IdentityId sets the "identity_id" query parameter.
func (b *DeleteUserSocialIdentityReqBuilder) IdentityId(v string) *DeleteUserSocialIdentityReqBuilder {
	b.req.queryParams["identity_id"] = v
	return b
}

// Build finalizes the request.
func (b *DeleteUserSocialIdentityReqBuilder) Build() *DeleteUserSocialIdentityReq { return b.req }

// DeleteUserSocialIdentityResp is the response for DeleteUserSocialIdentity.
type DeleteUserSocialIdentityResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// DeleteUserSocialIdentity: 删除用户第三方绑定
func (s *Service) DeleteUserSocialIdentity(ctx context.Context, req *DeleteUserSocialIdentityReq, opts ...core.RequestOption) (*DeleteUserSocialIdentityResp, error) {
	resp := &DeleteUserSocialIdentityResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "DELETE",
		PathTemplate: "/hduhelp-neo/admin/users/bindings/social",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// SetUserDefaultIdentityReq is the request for SetUserDefaultIdentity.
type SetUserDefaultIdentityReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// SetUserDefaultIdentityReqBuilder builds a SetUserDefaultIdentityReq with a fluent setter per field.
type SetUserDefaultIdentityReqBuilder struct{ req *SetUserDefaultIdentityReq }

// NewSetUserDefaultIdentityReqBuilder creates a request builder for SetUserDefaultIdentity.
func NewSetUserDefaultIdentityReqBuilder() *SetUserDefaultIdentityReqBuilder {
	return &SetUserDefaultIdentityReqBuilder{req: &SetUserDefaultIdentityReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *SetUserDefaultIdentityReqBuilder) Body(body *models.SetUserDefaultIdentityRequestBody) *SetUserDefaultIdentityReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *SetUserDefaultIdentityReqBuilder) Build() *SetUserDefaultIdentityReq { return b.req }

// SetUserDefaultIdentityResp is the response for SetUserDefaultIdentity.
type SetUserDefaultIdentityResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// SetUserDefaultIdentity: 设置用户主身份
func (s *Service) SetUserDefaultIdentity(ctx context.Context, req *SetUserDefaultIdentityReq, opts ...core.RequestOption) (*SetUserDefaultIdentityResp, error) {
	resp := &SetUserDefaultIdentityResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/users/default-identity",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// GetUserDetailReq is the request for GetUserDetail.
type GetUserDetailReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// GetUserDetailReqBuilder builds a GetUserDetailReq with a fluent setter per field.
type GetUserDetailReqBuilder struct{ req *GetUserDetailReq }

// NewGetUserDetailReqBuilder creates a request builder for GetUserDetail.
func NewGetUserDetailReqBuilder() *GetUserDetailReqBuilder {
	return &GetUserDetailReqBuilder{req: &GetUserDetailReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// UserId sets the "user_id" query parameter.
func (b *GetUserDetailReqBuilder) UserId(v string) *GetUserDetailReqBuilder {
	b.req.queryParams["user_id"] = v
	return b
}

// Build finalizes the request.
func (b *GetUserDetailReqBuilder) Build() *GetUserDetailReq { return b.req }

// GetUserDetailResp is the response for GetUserDetail.
type GetUserDetailResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
	Data *models.AdminUserDetail `json:"data"`
}

// GetUserDetail: 用户详情
func (s *Service) GetUserDetail(ctx context.Context, req *GetUserDetailReq, opts ...core.RequestOption) (*GetUserDetailResp, error) {
	resp := &GetUserDetailResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "GET",
		PathTemplate: "/hduhelp-neo/admin/users/detail",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}

// UnbanUserReq is the request for UnbanUser.
type UnbanUserReq struct {
	pathParams  map[string]string
	queryParams map[string]string
	headers     map[string]string
	body        any
}

// UnbanUserReqBuilder builds a UnbanUserReq with a fluent setter per field.
type UnbanUserReqBuilder struct{ req *UnbanUserReq }

// NewUnbanUserReqBuilder creates a request builder for UnbanUser.
func NewUnbanUserReqBuilder() *UnbanUserReqBuilder {
	return &UnbanUserReqBuilder{req: &UnbanUserReq{pathParams: map[string]string{}, queryParams: map[string]string{}, headers: map[string]string{}}}
}

// Body sets the request body.
func (b *UnbanUserReqBuilder) Body(body *models.UnbanUserRequestBody) *UnbanUserReqBuilder {
	b.req.body = body
	return b
}

// Build finalizes the request.
func (b *UnbanUserReqBuilder) Build() *UnbanUserReq { return b.req }

// UnbanUserResp is the response for UnbanUser.
type UnbanUserResp struct {
	core.APIResp `json:"-"`
	core.CodeMsg
}

// UnbanUser: 解封用户
func (s *Service) UnbanUser(ctx context.Context, req *UnbanUserReq, opts ...core.RequestOption) (*UnbanUserResp, error) {
	resp := &UnbanUserResp{}
	err := s.config.Do(ctx, &core.APIReq{
		HTTPMethod:   "PUT",
		PathTemplate: "/hduhelp-neo/admin/users/unban",
		PathParams:   req.pathParams,
		QueryParams:  req.queryParams,
		Headers:      req.headers,
		Body:         req.body,
	}, resp, opts...)
	return resp, err
}
